// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package types

import (
	"encoding/json"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"
)

type AnimationType string

const (
	AnimationTypeBRAND       AnimationType = "BRAND"
	AnimationTypePRODUCT     AnimationType = "PRODUCT"
	AnimationTypeTEXT        AnimationType = "TEXT"
	AnimationTypeVISUAL      AnimationType = "VISUAL"
	AnimationTypeSTATS       AnimationType = "STATS"
	AnimationTypeCHART       AnimationType = "CHART"
	AnimationTypeSIMPLE_TEXT AnimationType = "SIMPLE_TEXT"
)

// Values returns all allowed values for the AnimationType type.
func (AnimationType) Values() []AnimationType {
	return []AnimationType{
		AnimationTypeBRAND,
		AnimationTypePRODUCT,
		AnimationTypeTEXT,
		AnimationTypeVISUAL,
		AnimationTypeSTATS,
		AnimationTypeCHART,
		AnimationTypeSIMPLE_TEXT,
	}
}

// IsValid checks whether the given AnimationType value is valid.
func (e AnimationType) IsValid() bool {

	for _, v := range e.Values() {
		if e == v {
			return true
		}
	}
	return false

}

// MarshalJSON customizes JSON marshaling for AnimationType.
func (e AnimationType) MarshalJSON() ([]byte, error) {
	if !e.IsValid() {
		return nil, fmt.Errorf("invalid AnimationType: %q", e)
	}
	return json.Marshal(string(e))
}

// UnmarshalJSON customizes JSON unmarshaling for AnimationType.
func (e *AnimationType) UnmarshalJSON(data []byte) error {
	var s string
	if err := json.Unmarshal(data, &s); err != nil {
		return err
	}
	*e = AnimationType(s)
	if !e.IsValid() {
		return fmt.Errorf("invalid AnimationType: %q", s)
	}
	return nil
}

func (e *AnimationType) Decode(holder *cffi.CFFIValueEnum, typeMap baml.TypeMap) {
	name := holder.Name
	if name.Name != "AnimationType" && name.Namespace != cffi.CFFITypeNamespace_TYPES {
		panic(fmt.Sprintf("expected types.AnimationType, got %s.%s", string(name.Namespace.String()), string(name.Name)))
	}
	value := holder.Value
	*e = AnimationType(value)
}

func (e AnimationType) Encode() (*cffi.HostValue, error) {
	return baml.EncodeEnum("AnimationType", string(e), false)
}

func (e AnimationType) BamlTypeName() string {
	return "AnimationType"
}
