syntax = "proto3";

package coasterai.core.v1;
import "google/protobuf/timestamp.proto";
import "google/protobuf/struct.proto";

option go_package = "github.com/shank318/coasterai/pb/coasterai/core/v1;pbcore";

enum AIModel {
    AI_MODEL_UNSPECIFIED = 0;
    AI_MODEL_GEMINI_3_PRO = 1;
    AI_MODEL_GPT_5_5 = 2;
}

enum ConversationRole {
  CONVERSATION_ROLE_UNSPECIFIED = 0;
  CONVERSATION_ROLE_USER = 1;
  CONVERSATION_ROLE_ASSISTANT = 2;
  CONVERSATION_ROLE_TOOL = 3;
}

enum ConversationMessageType {
  CONVERSATION_MESSAGE_TYPE = 0;
  CONVERSATION_MESSAGE_THINKING = 1; // Thinking before the code, eg tool calls etc
  CONVERSATION_MESSAGE_FINAL_THINKING = 2; // Thinking for the code is generated
  CONVERSATION_MESSAGE_MANUAL_EDITS = 3;
}


message ConversationMessage {
  ConversationRole role = 1;
  string message = 2;
  repeated string assetIds = 3;
  /** Model used for generation */
  optional AIModel aiModel = 4;
  string codeSnapshot = 5;
  repeated string referenceIds = 6;
  .google.protobuf.Timestamp created_at = 7;
  ConversationMessageType type = 8;
  optional google.protobuf.Struct defaultCodeData = 9;
}

