syntax = "proto3";

package coasterai.core.v1;
option go_package = "github.com/shank318/coasterai/pb/coasterai/core/v1;pbcore";
import "google/protobuf/timestamp.proto";
import "coasterai/core/v1/slide.proto";
import "google/protobuf/struct.proto";

message AnimationTemplate {
  string id = 1;
  CodeRegistry codeRegistry = 2;
  string name = 3;
  string previewUrl = 4;
  google.protobuf.Struct registry = 5;
  google.protobuf.Struct edits = 6; // the GeneratedConfig
  AnimationSlidePlan plan = 7;
  float duration = 8;
}

enum AnimationCategory {
  ANIMATION_CATEGORY_UNSPECIFIED = 0;
  ANIMATION_CATEGORY_TEXT = 1;
  ANIMATION_CATEGORY_INTRO = 2;
  ANIMATION_CATEGORY_VISUALS = 3;
  ANIMATION_CATEGORY_MEDIA = 4;
  ANIMATION_CATEGORY_SOCIAL = 5;
  ANIMATION_CATEGORY_CTA = 6;
}