syntax = "proto3";

package coasterai.core.v1;
option go_package = "github.com/shank318/coasterai/pb/coasterai/core/v1;pbcore";
import "google/protobuf/timestamp.proto";
import "coasterai/core/v1/slide.proto";
import "coasterai/core/v1/brandkit.proto";

enum VideoStatus {
  VIDEO_STATUS_UNSPECIFIED = 0;  
  VIDEO_STATUS_PROCESSING = 1;
  VIDEO_STATUS_COMPLETED = 2;
  VIDEO_STATUS_FAILED = 3;
  VIDEO_STATUS_PLANNING = 4;
  VIDEO_STATUS_PLANNING_CANCELLED = 5;
  VIDEO_STATUS_USER_CANCELLED = 6;
}

enum VideoLanguage {
  VIDE_LANGUAGE_EN = 0;
}

enum ResolutionType {
  RESOLUTION_TYPE_UNSPECIFIED = 0;
  RESOLUTION_16_9 = 1;
  RESOLUTION_4_3 = 2;
  RESOLUTION_9_16 = 3;
  RESOLUTION_1_1 = 4;
}

enum StyleType {
  STYLE_TYPE_UNDEFINED = 0;
  STYLE_TYPE_SIMPLE = 1;
}

message GeneratedVideoBranding {
  repeated BrandColor colors = 1; // always there, extracted while generating video
  optional string brandLibraryID = 2;
  optional BrandIdentity brandIdentity = 3; // will be injected dynamically
}

message VideoMetadata {
    int32 fps = 1;
    optional BackgroundStyle background_style = 2;
    Resolution resolution = 3;
    float duration = 4;
    string prompt = 5;;
    VideoLanguage language = 7;
    optional string background_audio_url = 8;
    optional GeneratedVideoBranding generatedBranding = 9;
    optional string thinking_summary = 10;
}

message Video {
    string id = 1;
    string name = 2;
    VideoConfig config = 3;
    VideoMetadata metadata = 4;
    .google.protobuf.Timestamp created_at = 5;
    VideoStatus status = 6;
    int64 version = 7;
}

message VideoConfig {
  repeated Section sections = 1;
}

message Script {
  repeated ScriptItem items = 1;
}

message ScriptItem {
    string name = 1;
    optional string voiceover = 2;
    optional string reference = 3;
}

// ===================== RESOLUTION =====================

message Resolution {
  string id = 1;
  string name = 2;
  string aspect = 3;
  int32 width = 4;
  int32 height = 5;
}