// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"context"
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/shank318/coasterai/baml_client/types"
)

type parse struct{}

var Parse = &parse{}

// / Parse version of AnalyzeImage (Takes in string and returns types.AssetAnalysis)
func (*parse) AnalyzeImage(text string, opts ...CallOptionFunc) (types.AssetAnalysis, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: AnalyzeImage: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "AnalyzeImage", encoded)
	if err != nil {
		return types.AssetAnalysis{}, err
	}

	casted := (result).(types.AssetAnalysis)

	return casted, nil
}

// / Parse version of EditAnimationCode (Takes in string and returns types.EditAnimationCodeResponse)
func (*parse) EditAnimationCode(text string, opts ...CallOptionFunc) (types.EditAnimationCodeResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: EditAnimationCode: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "EditAnimationCode", encoded)
	if err != nil {
		return types.EditAnimationCodeResponse{}, err
	}

	casted := (result).(types.EditAnimationCodeResponse)

	return casted, nil
}

// / Parse version of GenerateAnimationV2 (Takes in string and returns types.GenerateAnimationCodeResponseV2)
func (*parse) GenerateAnimationV2(text string, opts ...CallOptionFunc) (types.GenerateAnimationCodeResponseV2, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateAnimationV2: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateAnimationV2", encoded)
	if err != nil {
		return types.GenerateAnimationCodeResponseV2{}, err
	}

	casted := (result).(types.GenerateAnimationCodeResponseV2)

	return casted, nil
}

// / Parse version of GeneratePlan (Takes in string and returns types.VideoGenerationPlan)
func (*parse) GeneratePlan(text string, opts ...CallOptionFunc) (types.VideoGenerationPlan, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GeneratePlan: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "GeneratePlan", encoded)
	if err != nil {
		return types.VideoGenerationPlan{}, err
	}

	casted := (result).(types.VideoGenerationPlan)

	return casted, nil
}

// / Parse version of GenerateScene (Takes in string and returns types.AddSceneResponse)
func (*parse) GenerateScene(text string, opts ...CallOptionFunc) (types.AddSceneResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: GenerateScene: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "GenerateScene", encoded)
	if err != nil {
		return types.AddSceneResponse{}, err
	}

	casted := (result).(types.AddSceneResponse)

	return casted, nil
}

// / Parse version of MatchCategories (Takes in string and returns types.MatchCategoriesResponse)
func (*parse) MatchCategories(text string, opts ...CallOptionFunc) (types.MatchCategoriesResponse, error) {

	var callOpts callOption
	for _, opt := range opts {
		opt(&callOpts)
	}

	args := baml.BamlFunctionArguments{
		Kwargs: map[string]any{"text": text, "stream": false},
		Env:    getEnvVars(callOpts.env),
	}

	if callOpts.clientRegistry != nil {
		args.ClientRegistry = callOpts.clientRegistry
	}

	if callOpts.collectors != nil {
		args.Collectors = callOpts.collectors
	}

	if callOpts.typeBuilder != nil {
		args.TypeBuilder = callOpts.typeBuilder
	}

	if callOpts.tags != nil {
		args.Tags = callOpts.tags
	}

	encoded, err := args.Encode()
	if err != nil {
		// This should never happen. if it does, please file an issue at https://github.com/boundaryml/baml/issues
		// and include the type of the args you're passing in.
		wrapped_err := fmt.Errorf("BAML INTERNAL ERROR: MatchCategories: %w", err)
		panic(wrapped_err)
	}

	result, err := bamlRuntime.CallFunctionParse(context.Background(), "MatchCategories", encoded)
	if err != nil {
		return types.MatchCategoriesResponse{}, err
	}

	casted := (result).(types.MatchCategoriesResponse)

	return casted, nil
}
