// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/shank318/coasterai/baml_client/stream_types"
	"github.com/shank318/coasterai/baml_client/types"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AnimationCategories":                  reflect.TypeOf(types.AnimationCategories{}),
	"STREAM_TYPES.AnimationCategories":           reflect.TypeOf(stream_types.AnimationCategories{}),
	"TYPES.AskUserQuestion":                      reflect.TypeOf(types.AskUserQuestion{}),
	"STREAM_TYPES.AskUserQuestion":               reflect.TypeOf(stream_types.AskUserQuestion{}),
	"TYPES.AssetAnalysis":                        reflect.TypeOf(types.AssetAnalysis{}),
	"STREAM_TYPES.AssetAnalysis":                 reflect.TypeOf(stream_types.AssetAnalysis{}),
	"TYPES.Background":                           reflect.TypeOf(types.Background{}),
	"STREAM_TYPES.Background":                    reflect.TypeOf(stream_types.Background{}),
	"TYPES.Category":                             reflect.TypeOf(types.Category{}),
	"STREAM_TYPES.Category":                      reflect.TypeOf(stream_types.Category{}),
	"TYPES.ExtractTemplateConfigRequest":         reflect.TypeOf(types.ExtractTemplateConfigRequest{}),
	"STREAM_TYPES.ExtractTemplateConfigRequest":  reflect.TypeOf(stream_types.ExtractTemplateConfigRequest{}),
	"TYPES.ExtractTemplateConfigResponse":        reflect.TypeOf(types.ExtractTemplateConfigResponse{}),
	"STREAM_TYPES.ExtractTemplateConfigResponse": reflect.TypeOf(stream_types.ExtractTemplateConfigResponse{}),
	"TYPES.GenerateAnimationCodeRequest":         reflect.TypeOf(types.GenerateAnimationCodeRequest{}),
	"STREAM_TYPES.GenerateAnimationCodeRequest":  reflect.TypeOf(stream_types.GenerateAnimationCodeRequest{}),
	"TYPES.GenerateAnimationCodeResponse":        reflect.TypeOf(types.GenerateAnimationCodeResponse{}),
	"STREAM_TYPES.GenerateAnimationCodeResponse": reflect.TypeOf(stream_types.GenerateAnimationCodeResponse{}),
	"TYPES.GeneratedVideoPlan":                   reflect.TypeOf(types.GeneratedVideoPlan{}),
	"STREAM_TYPES.GeneratedVideoPlan":            reflect.TypeOf(stream_types.GeneratedVideoPlan{}),
	"TYPES.MatchCategoriesRequest":               reflect.TypeOf(types.MatchCategoriesRequest{}),
	"STREAM_TYPES.MatchCategoriesRequest":        reflect.TypeOf(stream_types.MatchCategoriesRequest{}),
	"TYPES.MatchCategoriesResponse":              reflect.TypeOf(types.MatchCategoriesResponse{}),
	"STREAM_TYPES.MatchCategoriesResponse":       reflect.TypeOf(stream_types.MatchCategoriesResponse{}),
	"TYPES.Message":                              reflect.TypeOf(types.Message{}),
	"STREAM_TYPES.Message":                       reflect.TypeOf(stream_types.Message{}),
	"TYPES.Scene":                                reflect.TypeOf(types.Scene{}),
	"STREAM_TYPES.Scene":                         reflect.TypeOf(stream_types.Scene{}),
	"TYPES.SceneElement":                         reflect.TypeOf(types.SceneElement{}),
	"STREAM_TYPES.SceneElement":                  reflect.TypeOf(stream_types.SceneElement{}),
	"TYPES.SceneSection":                         reflect.TypeOf(types.SceneSection{}),
	"STREAM_TYPES.SceneSection":                  reflect.TypeOf(stream_types.SceneSection{}),
	"TYPES.ScriptItem":                           reflect.TypeOf(types.ScriptItem{}),
	"STREAM_TYPES.ScriptItem":                    reflect.TypeOf(stream_types.ScriptItem{}),
	"TYPES.VideoBranding":                        reflect.TypeOf(types.VideoBranding{}),
	"STREAM_TYPES.VideoBranding":                 reflect.TypeOf(stream_types.VideoBranding{}),
	"TYPES.VideoGenerationPlan":                  reflect.TypeOf(types.VideoGenerationPlan{}),
	"STREAM_TYPES.VideoGenerationPlan":           reflect.TypeOf(stream_types.VideoGenerationPlan{}),
	"TYPES.VideoGenerationPlanRequest":           reflect.TypeOf(types.VideoGenerationPlanRequest{}),
	"STREAM_TYPES.VideoGenerationPlanRequest":    reflect.TypeOf(stream_types.VideoGenerationPlanRequest{}),

	"TYPES.AskUserQuestionType": reflect.TypeOf(types.AskUserQuestionType("")),
	"TYPES.ColorToken":          reflect.TypeOf(types.ColorToken("")),

	"TYPES.AskUserQuestion__GenerateAnimationCodeResponse": reflect.TypeOf(types.Union2AskUserQuestionOrGenerateAnimationCodeResponse{}),
	"TYPES.AskUserQuestion__GeneratedVideoPlan":            reflect.TypeOf(types.Union2AskUserQuestionOrGeneratedVideoPlan{}),
	"TYPES.ColorToken__string":                             reflect.TypeOf(types.Union2ColorTokenOrString{}),
	"TYPES.string_assistant__string_tool__string_user":     reflect.TypeOf(types.Union3KassistantOrKtoolOrKuser{}),

	"STREAM_TYPES.AskUserQuestion__GenerateAnimationCodeResponse": reflect.TypeOf(stream_types.Union2AskUserQuestionOrGenerateAnimationCodeResponse{}),
	"STREAM_TYPES.AskUserQuestion__GeneratedVideoPlan":            reflect.TypeOf(stream_types.Union2AskUserQuestionOrGeneratedVideoPlan{}),
}
