// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package baml_client

import (
	"reflect"

	"github.com/shank318/coasterai/baml_client/stream_types"
	"github.com/shank318/coasterai/baml_client/types"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
)

var typeMap = map[string]reflect.Type{
	"TYPES.AnimationSlide":                         reflect.TypeOf(types.AnimationSlide{}),
	"STREAM_TYPES.AnimationSlide":                  reflect.TypeOf(stream_types.AnimationSlide{}),
	"TYPES.AskUserQuestion":                        reflect.TypeOf(types.AskUserQuestion{}),
	"STREAM_TYPES.AskUserQuestion":                 reflect.TypeOf(stream_types.AskUserQuestion{}),
	"TYPES.BrandColors":                            reflect.TypeOf(types.BrandColors{}),
	"STREAM_TYPES.BrandColors":                     reflect.TypeOf(stream_types.BrandColors{}),
	"TYPES.Category":                               reflect.TypeOf(types.Category{}),
	"STREAM_TYPES.Category":                        reflect.TypeOf(stream_types.Category{}),
	"TYPES.EditAnimationCodeRequest":               reflect.TypeOf(types.EditAnimationCodeRequest{}),
	"STREAM_TYPES.EditAnimationCodeRequest":        reflect.TypeOf(stream_types.EditAnimationCodeRequest{}),
	"TYPES.EditAnimationCodeResponse":              reflect.TypeOf(types.EditAnimationCodeResponse{}),
	"STREAM_TYPES.EditAnimationCodeResponse":       reflect.TypeOf(stream_types.EditAnimationCodeResponse{}),
	"TYPES.EditString":                             reflect.TypeOf(types.EditString{}),
	"STREAM_TYPES.EditString":                      reflect.TypeOf(stream_types.EditString{}),
	"TYPES.EnhanceAnimationPromptRequest":          reflect.TypeOf(types.EnhanceAnimationPromptRequest{}),
	"STREAM_TYPES.EnhanceAnimationPromptRequest":   reflect.TypeOf(stream_types.EnhanceAnimationPromptRequest{}),
	"TYPES.EnhanceAnimationPromptResponse":         reflect.TypeOf(types.EnhanceAnimationPromptResponse{}),
	"STREAM_TYPES.EnhanceAnimationPromptResponse":  reflect.TypeOf(stream_types.EnhanceAnimationPromptResponse{}),
	"TYPES.EnhancedAnimationPrompt":                reflect.TypeOf(types.EnhancedAnimationPrompt{}),
	"STREAM_TYPES.EnhancedAnimationPrompt":         reflect.TypeOf(stream_types.EnhancedAnimationPrompt{}),
	"TYPES.GenerateAnimationCodeRequest":           reflect.TypeOf(types.GenerateAnimationCodeRequest{}),
	"STREAM_TYPES.GenerateAnimationCodeRequest":    reflect.TypeOf(stream_types.GenerateAnimationCodeRequest{}),
	"TYPES.GenerateAnimationCodeResponse":          reflect.TypeOf(types.GenerateAnimationCodeResponse{}),
	"STREAM_TYPES.GenerateAnimationCodeResponse":   reflect.TypeOf(stream_types.GenerateAnimationCodeResponse{}),
	"TYPES.GenerateAnimationPromptRequest":         reflect.TypeOf(types.GenerateAnimationPromptRequest{}),
	"STREAM_TYPES.GenerateAnimationPromptRequest":  reflect.TypeOf(stream_types.GenerateAnimationPromptRequest{}),
	"TYPES.GenerateAnimationPromptResponse":        reflect.TypeOf(types.GenerateAnimationPromptResponse{}),
	"STREAM_TYPES.GenerateAnimationPromptResponse": reflect.TypeOf(stream_types.GenerateAnimationPromptResponse{}),
	"TYPES.Gradient":                               reflect.TypeOf(types.Gradient{}),
	"STREAM_TYPES.Gradient":                        reflect.TypeOf(stream_types.Gradient{}),
	"TYPES.GradientStop":                           reflect.TypeOf(types.GradientStop{}),
	"STREAM_TYPES.GradientStop":                    reflect.TypeOf(stream_types.GradientStop{}),
	"TYPES.MatchCategoriesRequest":                 reflect.TypeOf(types.MatchCategoriesRequest{}),
	"STREAM_TYPES.MatchCategoriesRequest":          reflect.TypeOf(stream_types.MatchCategoriesRequest{}),
	"TYPES.MatchCategoriesResponse":                reflect.TypeOf(types.MatchCategoriesResponse{}),
	"STREAM_TYPES.MatchCategoriesResponse":         reflect.TypeOf(stream_types.MatchCategoriesResponse{}),
	"TYPES.MatchTemplateRequest":                   reflect.TypeOf(types.MatchTemplateRequest{}),
	"STREAM_TYPES.MatchTemplateRequest":            reflect.TypeOf(stream_types.MatchTemplateRequest{}),
	"TYPES.MatchTemplateResponse":                  reflect.TypeOf(types.MatchTemplateResponse{}),
	"STREAM_TYPES.MatchTemplateResponse":           reflect.TypeOf(stream_types.MatchTemplateResponse{}),
	"TYPES.MediaSlide":                             reflect.TypeOf(types.MediaSlide{}),
	"STREAM_TYPES.MediaSlide":                      reflect.TypeOf(stream_types.MediaSlide{}),
	"TYPES.Message":                                reflect.TypeOf(types.Message{}),
	"STREAM_TYPES.Message":                         reflect.TypeOf(stream_types.Message{}),
	"TYPES.ReGenerateAnimationCodeRequest":         reflect.TypeOf(types.ReGenerateAnimationCodeRequest{}),
	"STREAM_TYPES.ReGenerateAnimationCodeRequest":  reflect.TypeOf(stream_types.ReGenerateAnimationCodeRequest{}),
	"TYPES.ReGenerateAnimationCodeResponse":        reflect.TypeOf(types.ReGenerateAnimationCodeResponse{}),
	"STREAM_TYPES.ReGenerateAnimationCodeResponse": reflect.TypeOf(stream_types.ReGenerateAnimationCodeResponse{}),
	"TYPES.ScriptItem":                             reflect.TypeOf(types.ScriptItem{}),
	"STREAM_TYPES.ScriptItem":                      reflect.TypeOf(stream_types.ScriptItem{}),
	"TYPES.Section":                                reflect.TypeOf(types.Section{}),
	"STREAM_TYPES.Section":                         reflect.TypeOf(stream_types.Section{}),
	"TYPES.StreamingVideoGenerationPlan":           reflect.TypeOf(types.StreamingVideoGenerationPlan{}),
	"STREAM_TYPES.StreamingVideoGenerationPlan":    reflect.TypeOf(stream_types.StreamingVideoGenerationPlan{}),
	"TYPES.TemplateConfigExtractorInput":           reflect.TypeOf(types.TemplateConfigExtractorInput{}),
	"STREAM_TYPES.TemplateConfigExtractorInput":    reflect.TypeOf(stream_types.TemplateConfigExtractorInput{}),
	"TYPES.TemplateConfigExtractorOutput":          reflect.TypeOf(types.TemplateConfigExtractorOutput{}),
	"STREAM_TYPES.TemplateConfigExtractorOutput":   reflect.TypeOf(stream_types.TemplateConfigExtractorOutput{}),
	"TYPES.TemplateItem":                           reflect.TypeOf(types.TemplateItem{}),
	"STREAM_TYPES.TemplateItem":                    reflect.TypeOf(stream_types.TemplateItem{}),
	"TYPES.VideoBackground":                        reflect.TypeOf(types.VideoBackground{}),
	"STREAM_TYPES.VideoBackground":                 reflect.TypeOf(stream_types.VideoBackground{}),
	"TYPES.VideoBranding":                          reflect.TypeOf(types.VideoBranding{}),
	"STREAM_TYPES.VideoBranding":                   reflect.TypeOf(stream_types.VideoBranding{}),
	"TYPES.VideoGenerationPlan":                    reflect.TypeOf(types.VideoGenerationPlan{}),
	"STREAM_TYPES.VideoGenerationPlan":             reflect.TypeOf(stream_types.VideoGenerationPlan{}),
	"TYPES.VideoGenerationPlanRequest":             reflect.TypeOf(types.VideoGenerationPlanRequest{}),
	"STREAM_TYPES.VideoGenerationPlanRequest":      reflect.TypeOf(stream_types.VideoGenerationPlanRequest{}),

	"TYPES.AnimationCodeEditType": reflect.TypeOf(types.AnimationCodeEditType("")),
	"TYPES.AnimationType":         reflect.TypeOf(types.AnimationType("")),

	"TYPES.AnimationSlide__MediaSlide":                 reflect.TypeOf(types.Union2AnimationSlideOrMediaSlide{}),
	"TYPES.AskUserQuestion__EnhancedAnimationPrompt":   reflect.TypeOf(types.Union2AskUserQuestionOrEnhancedAnimationPrompt{}),
	"TYPES.AskUserQuestion__VideoGenerationPlan":       reflect.TypeOf(types.Union2AskUserQuestionOrVideoGenerationPlan{}),
	"TYPES.string_assistant__string_tool__string_user": reflect.TypeOf(types.Union3KassistantOrKtoolOrKuser{}),

	"STREAM_TYPES.AnimationSlide__MediaSlide":               reflect.TypeOf(stream_types.Union2AnimationSlideOrMediaSlide{}),
	"STREAM_TYPES.AskUserQuestion__EnhancedAnimationPrompt": reflect.TypeOf(stream_types.Union2AskUserQuestionOrEnhancedAnimationPrompt{}),
	"STREAM_TYPES.AskUserQuestion__VideoGenerationPlan":     reflect.TypeOf(stream_types.Union2AskUserQuestionOrVideoGenerationPlan{}),

	"STREAM_STATE_TYPES.Optional__string": reflect.TypeOf(baml.StreamState[*string]{}),
}
