// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/portal/v1/templates.proto (package coasterai.portal.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_empty, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_coasterai_core_v1_template } from "../../core/v1/template_pb";

/**
 * Describes the file coasterai/portal/v1/templates.proto.
 */
export const file_coasterai_portal_v1_templates = /*@__PURE__*/
  fileDesc("CiNjb2FzdGVyYWkvcG9ydGFsL3YxL3RlbXBsYXRlcy5wcm90bxITY29hc3RlcmFpLnBvcnRhbC52MSJPChRHZXRUZW1wbGF0ZXNSZXNwb25zZRI3Cgl0ZW1wbGF0ZXMYASADKAsyJC5jb2FzdGVyYWkuY29yZS52MS5BbmltYXRpb25UZW1wbGF0ZSIgChJHZXRUZW1wbGF0ZVJlcXVlc3QSCgoCaWQYASABKAkidQoVVXBkYXRlVGVtcGxhdGVSZXF1ZXN0EgoKAmlkGAEgASgJEhMKC2Rlc2NyaXB0aW9uGAIgASgJEhkKEXVzYWdlX2Rlc2NyaXB0aW9uGAMgASgJEhIKCmNhdGVnb3JpZXMYBCADKAkSDAoEbmFtZRgFIAEoCUI/Wj1naXRodWIuY29tL3NoYW5rMzE4L2NvYXN0ZXJhaS9wYi9jb2FzdGVyYWkvcG9ydGFsL3YxO3BicG9ydGFsYgZwcm90bzM", [file_google_protobuf_timestamp, file_google_protobuf_empty, file_coasterai_core_v1_template]);

/**
 * Describes the message coasterai.portal.v1.GetTemplatesResponse.
 * Use `create(GetTemplatesResponseSchema)` to create a new message.
 */
export const GetTemplatesResponseSchema = /*@__PURE__*/
  messageDesc(file_coasterai_portal_v1_templates, 0);

/**
 * Describes the message coasterai.portal.v1.GetTemplateRequest.
 * Use `create(GetTemplateRequestSchema)` to create a new message.
 */
export const GetTemplateRequestSchema = /*@__PURE__*/
  messageDesc(file_coasterai_portal_v1_templates, 1);

/**
 * Describes the message coasterai.portal.v1.UpdateTemplateRequest.
 * Use `create(UpdateTemplateRequestSchema)` to create a new message.
 */
export const UpdateTemplateRequestSchema = /*@__PURE__*/
  messageDesc(file_coasterai_portal_v1_templates, 2);

