// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AnimationSlideClassView struct {
	inner baml.ClassBuilder
}

func (t *AnimationSlideClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AnimationSlideClassView) PropertyIndex() (ClassPropertyView, error) {
	return t.inner.Property("index")
}

func (t *AnimationSlideClassView) PropertyBeatDescription() (ClassPropertyView, error) {
	return t.inner.Property("beatDescription")
}

func (t *AnimationSlideClassView) PropertyAnimationType() (ClassPropertyView, error) {
	return t.inner.Property("animationType")
}

func (t *AnimationSlideClassView) PropertyCategorySearchQuery() (ClassPropertyView, error) {
	return t.inner.Property("categorySearchQuery")
}

func (t *AnimationSlideClassView) PropertyDuration() (ClassPropertyView, error) {
	return t.inner.Property("duration")
}

func (t *AnimationSlideClassView) PropertyVoiceover() (ClassPropertyView, error) {
	return t.inner.Property("voiceover")
}

func (t *AnimationSlideClassView) PropertySelectedTemplateDescription() (ClassPropertyView, error) {
	return t.inner.Property("selectedTemplateDescription")
}

func (t *TypeBuilder) AnimationSlide() (*AnimationSlideClassView, error) {
	bld, err := t.inner.Class("AnimationSlide")
	if err != nil {
		return nil, err
	}
	return &AnimationSlideClassView{inner: bld}, nil
}

func (t *AnimationSlideClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AskUserQuestionClassView struct {
	inner baml.ClassBuilder
}

func (t *AskUserQuestionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AskUserQuestionClassView) PropertyTool_name() (ClassPropertyView, error) {
	return t.inner.Property("tool_name")
}

func (t *AskUserQuestionClassView) PropertyQuestion_text() (ClassPropertyView, error) {
	return t.inner.Property("question_text")
}

func (t *AskUserQuestionClassView) PropertyOptions() (ClassPropertyView, error) {
	return t.inner.Property("options")
}

func (t *AskUserQuestionClassView) PropertyAllow_custom_entry() (ClassPropertyView, error) {
	return t.inner.Property("allow_custom_entry")
}

func (t *TypeBuilder) AskUserQuestion() (*AskUserQuestionClassView, error) {
	bld, err := t.inner.Class("AskUserQuestion")
	if err != nil {
		return nil, err
	}
	return &AskUserQuestionClassView{inner: bld}, nil
}

func (t *AskUserQuestionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type BrandColorsClassView struct {
	inner baml.ClassBuilder
}

func (t *BrandColorsClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *BrandColorsClassView) PropertyPrimary() (ClassPropertyView, error) {
	return t.inner.Property("primary")
}

func (t *BrandColorsClassView) PropertySecondary() (ClassPropertyView, error) {
	return t.inner.Property("secondary")
}

func (t *BrandColorsClassView) PropertyAccent() (ClassPropertyView, error) {
	return t.inner.Property("accent")
}

func (t *BrandColorsClassView) PropertyText() (ClassPropertyView, error) {
	return t.inner.Property("text")
}

func (t *TypeBuilder) BrandColors() (*BrandColorsClassView, error) {
	bld, err := t.inner.Class("BrandColors")
	if err != nil {
		return nil, err
	}
	return &BrandColorsClassView{inner: bld}, nil
}

func (t *BrandColorsClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CategoryClassView struct {
	inner baml.ClassBuilder
}

func (t *CategoryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CategoryClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *CategoryClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) Category() (*CategoryClassView, error) {
	bld, err := t.inner.Class("Category")
	if err != nil {
		return nil, err
	}
	return &CategoryClassView{inner: bld}, nil
}

func (t *CategoryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationCodeRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationCodeRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationCodeRequestClassView) PropertyAnimationType() (ClassPropertyView, error) {
	return t.inner.Property("animationType")
}

func (t *GenerateAnimationCodeRequestClassView) PropertyAnimationPrompt() (ClassPropertyView, error) {
	return t.inner.Property("animationPrompt")
}

func (t *GenerateAnimationCodeRequestClassView) PropertyDuration() (ClassPropertyView, error) {
	return t.inner.Property("duration")
}

func (t *GenerateAnimationCodeRequestClassView) PropertyVoiceover() (ClassPropertyView, error) {
	return t.inner.Property("voiceover")
}

func (t *GenerateAnimationCodeRequestClassView) PropertyBranding() (ClassPropertyView, error) {
	return t.inner.Property("branding")
}

func (t *GenerateAnimationCodeRequestClassView) PropertySlideBackground() (ClassPropertyView, error) {
	return t.inner.Property("slideBackground")
}

func (t *TypeBuilder) GenerateAnimationCodeRequest() (*GenerateAnimationCodeRequestClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationCodeRequest")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationCodeRequestClassView{inner: bld}, nil
}

func (t *GenerateAnimationCodeRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationCodeResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationCodeResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationCodeResponseClassView) PropertyCode() (ClassPropertyView, error) {
	return t.inner.Property("code")
}

func (t *GenerateAnimationCodeResponseClassView) PropertyConfig() (ClassPropertyView, error) {
	return t.inner.Property("config")
}

func (t *TypeBuilder) GenerateAnimationCodeResponse() (*GenerateAnimationCodeResponseClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationCodeResponse")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationCodeResponseClassView{inner: bld}, nil
}

func (t *GenerateAnimationCodeResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationPromptRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationPromptRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationPromptRequestClassView) PropertyAnimationType() (ClassPropertyView, error) {
	return t.inner.Property("animationType")
}

func (t *GenerateAnimationPromptRequestClassView) PropertyCurrentBeat() (ClassPropertyView, error) {
	return t.inner.Property("currentBeat")
}

func (t *GenerateAnimationPromptRequestClassView) PropertyPlanSoFar() (ClassPropertyView, error) {
	return t.inner.Property("planSoFar")
}

func (t *GenerateAnimationPromptRequestClassView) PropertyVoiceover() (ClassPropertyView, error) {
	return t.inner.Property("voiceover")
}

func (t *GenerateAnimationPromptRequestClassView) PropertyBranding() (ClassPropertyView, error) {
	return t.inner.Property("branding")
}

func (t *GenerateAnimationPromptRequestClassView) PropertySlideBackground() (ClassPropertyView, error) {
	return t.inner.Property("slideBackground")
}

func (t *TypeBuilder) GenerateAnimationPromptRequest() (*GenerateAnimationPromptRequestClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationPromptRequest")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationPromptRequestClassView{inner: bld}, nil
}

func (t *GenerateAnimationPromptRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationPromptResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationPromptResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationPromptResponseClassView) PropertyPrompt() (ClassPropertyView, error) {
	return t.inner.Property("prompt")
}

func (t *TypeBuilder) GenerateAnimationPromptResponse() (*GenerateAnimationPromptResponseClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationPromptResponse")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationPromptResponseClassView{inner: bld}, nil
}

func (t *GenerateAnimationPromptResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GradientClassView struct {
	inner baml.ClassBuilder
}

func (t *GradientClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GradientClassView) PropertyAngle() (ClassPropertyView, error) {
	return t.inner.Property("angle")
}

func (t *GradientClassView) PropertyStops() (ClassPropertyView, error) {
	return t.inner.Property("stops")
}

func (t *TypeBuilder) Gradient() (*GradientClassView, error) {
	bld, err := t.inner.Class("Gradient")
	if err != nil {
		return nil, err
	}
	return &GradientClassView{inner: bld}, nil
}

func (t *GradientClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GradientStopClassView struct {
	inner baml.ClassBuilder
}

func (t *GradientStopClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GradientStopClassView) PropertyColor() (ClassPropertyView, error) {
	return t.inner.Property("color")
}

func (t *GradientStopClassView) PropertyPosition() (ClassPropertyView, error) {
	return t.inner.Property("position")
}

func (t *TypeBuilder) GradientStop() (*GradientStopClassView, error) {
	bld, err := t.inner.Class("GradientStop")
	if err != nil {
		return nil, err
	}
	return &GradientStopClassView{inner: bld}, nil
}

func (t *GradientStopClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchCategoriesRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchCategoriesRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchCategoriesRequestClassView) PropertyCategories() (ClassPropertyView, error) {
	return t.inner.Property("categories")
}

func (t *MatchCategoriesRequestClassView) PropertyQuery() (ClassPropertyView, error) {
	return t.inner.Property("query")
}

func (t *TypeBuilder) MatchCategoriesRequest() (*MatchCategoriesRequestClassView, error) {
	bld, err := t.inner.Class("MatchCategoriesRequest")
	if err != nil {
		return nil, err
	}
	return &MatchCategoriesRequestClassView{inner: bld}, nil
}

func (t *MatchCategoriesRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchCategoriesResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchCategoriesResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchCategoriesResponseClassView) PropertyCategories() (ClassPropertyView, error) {
	return t.inner.Property("categories")
}

func (t *TypeBuilder) MatchCategoriesResponse() (*MatchCategoriesResponseClassView, error) {
	bld, err := t.inner.Class("MatchCategoriesResponse")
	if err != nil {
		return nil, err
	}
	return &MatchCategoriesResponseClassView{inner: bld}, nil
}

func (t *MatchCategoriesResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchTemplateRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchTemplateRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchTemplateRequestClassView) PropertyCurrentBeat() (ClassPropertyView, error) {
	return t.inner.Property("currentBeat")
}

func (t *MatchTemplateRequestClassView) PropertyPlanSoFar() (ClassPropertyView, error) {
	return t.inner.Property("planSoFar")
}

func (t *MatchTemplateRequestClassView) PropertyTemplates() (ClassPropertyView, error) {
	return t.inner.Property("templates")
}

func (t *TypeBuilder) MatchTemplateRequest() (*MatchTemplateRequestClassView, error) {
	bld, err := t.inner.Class("MatchTemplateRequest")
	if err != nil {
		return nil, err
	}
	return &MatchTemplateRequestClassView{inner: bld}, nil
}

func (t *MatchTemplateRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchTemplateResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchTemplateResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchTemplateResponseClassView) PropertyTemplates() (ClassPropertyView, error) {
	return t.inner.Property("templates")
}

func (t *TypeBuilder) MatchTemplateResponse() (*MatchTemplateResponseClassView, error) {
	bld, err := t.inner.Class("MatchTemplateResponse")
	if err != nil {
		return nil, err
	}
	return &MatchTemplateResponseClassView{inner: bld}, nil
}

func (t *MatchTemplateResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MediaSlideClassView struct {
	inner baml.ClassBuilder
}

func (t *MediaSlideClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MediaSlideClassView) PropertyIndex() (ClassPropertyView, error) {
	return t.inner.Property("index")
}

func (t *MediaSlideClassView) PropertyBeatDescription() (ClassPropertyView, error) {
	return t.inner.Property("beatDescription")
}

func (t *MediaSlideClassView) PropertyDuration() (ClassPropertyView, error) {
	return t.inner.Property("duration")
}

func (t *MediaSlideClassView) PropertySelectedTemplateDescription() (ClassPropertyView, error) {
	return t.inner.Property("selectedTemplateDescription")
}

func (t *TypeBuilder) MediaSlide() (*MediaSlideClassView, error) {
	bld, err := t.inner.Class("MediaSlide")
	if err != nil {
		return nil, err
	}
	return &MediaSlideClassView{inner: bld}, nil
}

func (t *MediaSlideClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MessageClassView struct {
	inner baml.ClassBuilder
}

func (t *MessageClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MessageClassView) PropertyRole() (ClassPropertyView, error) {
	return t.inner.Property("role")
}

func (t *MessageClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *MessageClassView) PropertyTool_call_id() (ClassPropertyView, error) {
	return t.inner.Property("tool_call_id")
}

func (t *TypeBuilder) Message() (*MessageClassView, error) {
	bld, err := t.inner.Class("Message")
	if err != nil {
		return nil, err
	}
	return &MessageClassView{inner: bld}, nil
}

func (t *MessageClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ScriptItemClassView struct {
	inner baml.ClassBuilder
}

func (t *ScriptItemClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ScriptItemClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ScriptItemClassView) PropertyVoiceover() (ClassPropertyView, error) {
	return t.inner.Property("voiceover")
}

func (t *ScriptItemClassView) PropertyReference() (ClassPropertyView, error) {
	return t.inner.Property("reference")
}

func (t *TypeBuilder) ScriptItem() (*ScriptItemClassView, error) {
	bld, err := t.inner.Class("ScriptItem")
	if err != nil {
		return nil, err
	}
	return &ScriptItemClassView{inner: bld}, nil
}

func (t *ScriptItemClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SectionClassView struct {
	inner baml.ClassBuilder
}

func (t *SectionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SectionClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *SectionClassView) PropertySlides() (ClassPropertyView, error) {
	return t.inner.Property("slides")
}

func (t *TypeBuilder) Section() (*SectionClassView, error) {
	bld, err := t.inner.Class("Section")
	if err != nil {
		return nil, err
	}
	return &SectionClassView{inner: bld}, nil
}

func (t *SectionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type StreamingVideoGenerationPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *StreamingVideoGenerationPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *StreamingVideoGenerationPlanClassView) PropertyThinking() (ClassPropertyView, error) {
	return t.inner.Property("thinking")
}

func (t *StreamingVideoGenerationPlanClassView) PropertyPlan() (ClassPropertyView, error) {
	return t.inner.Property("plan")
}

func (t *TypeBuilder) StreamingVideoGenerationPlan() (*StreamingVideoGenerationPlanClassView, error) {
	bld, err := t.inner.Class("StreamingVideoGenerationPlan")
	if err != nil {
		return nil, err
	}
	return &StreamingVideoGenerationPlanClassView{inner: bld}, nil
}

func (t *StreamingVideoGenerationPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TemplateConfigExtractorInputClassView struct {
	inner baml.ClassBuilder
}

func (t *TemplateConfigExtractorInputClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TemplateConfigExtractorInputClassView) PropertySchema() (ClassPropertyView, error) {
	return t.inner.Property("schema")
}

func (t *TemplateConfigExtractorInputClassView) PropertyBeatDescription() (ClassPropertyView, error) {
	return t.inner.Property("beatDescription")
}

func (t *TemplateConfigExtractorInputClassView) PropertyTemplateDescription() (ClassPropertyView, error) {
	return t.inner.Property("templateDescription")
}

func (t *TypeBuilder) TemplateConfigExtractorInput() (*TemplateConfigExtractorInputClassView, error) {
	bld, err := t.inner.Class("TemplateConfigExtractorInput")
	if err != nil {
		return nil, err
	}
	return &TemplateConfigExtractorInputClassView{inner: bld}, nil
}

func (t *TemplateConfigExtractorInputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TemplateConfigExtractorOutputClassView struct {
	inner baml.ClassBuilder
}

func (t *TemplateConfigExtractorOutputClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TemplateConfigExtractorOutputClassView) PropertyConfig() (ClassPropertyView, error) {
	return t.inner.Property("config")
}

func (t *TypeBuilder) TemplateConfigExtractorOutput() (*TemplateConfigExtractorOutputClassView, error) {
	bld, err := t.inner.Class("TemplateConfigExtractorOutput")
	if err != nil {
		return nil, err
	}
	return &TemplateConfigExtractorOutputClassView{inner: bld}, nil
}

func (t *TemplateConfigExtractorOutputClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type TemplateItemClassView struct {
	inner baml.ClassBuilder
}

func (t *TemplateItemClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *TemplateItemClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *TemplateItemClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) TemplateItem() (*TemplateItemClassView, error) {
	bld, err := t.inner.Class("TemplateItem")
	if err != nil {
		return nil, err
	}
	return &TemplateItemClassView{inner: bld}, nil
}

func (t *TemplateItemClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoBackgroundClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoBackgroundClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoBackgroundClassView) PropertyGradient() (ClassPropertyView, error) {
	return t.inner.Property("gradient")
}

func (t *TypeBuilder) VideoBackground() (*VideoBackgroundClassView, error) {
	bld, err := t.inner.Class("VideoBackground")
	if err != nil {
		return nil, err
	}
	return &VideoBackgroundClassView{inner: bld}, nil
}

func (t *VideoBackgroundClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoBrandingClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoBrandingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoBrandingClassView) PropertyColors() (ClassPropertyView, error) {
	return t.inner.Property("colors")
}

func (t *TypeBuilder) VideoBranding() (*VideoBrandingClassView, error) {
	bld, err := t.inner.Class("VideoBranding")
	if err != nil {
		return nil, err
	}
	return &VideoBrandingClassView{inner: bld}, nil
}

func (t *VideoBrandingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoGenerationPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoGenerationPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoGenerationPlanClassView) PropertyVideoName() (ClassPropertyView, error) {
	return t.inner.Property("videoName")
}

func (t *VideoGenerationPlanClassView) PropertySections() (ClassPropertyView, error) {
	return t.inner.Property("sections")
}

func (t *VideoGenerationPlanClassView) PropertyBackgroundStyle() (ClassPropertyView, error) {
	return t.inner.Property("backgroundStyle")
}

func (t *VideoGenerationPlanClassView) PropertyBranding() (ClassPropertyView, error) {
	return t.inner.Property("branding")
}

func (t *TypeBuilder) VideoGenerationPlan() (*VideoGenerationPlanClassView, error) {
	bld, err := t.inner.Class("VideoGenerationPlan")
	if err != nil {
		return nil, err
	}
	return &VideoGenerationPlanClassView{inner: bld}, nil
}

func (t *VideoGenerationPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoGenerationPlanRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoGenerationPlanRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoGenerationPlanRequestClassView) PropertyDuration() (ClassPropertyView, error) {
	return t.inner.Property("Duration")
}

func (t *VideoGenerationPlanRequestClassView) PropertyPrompt() (ClassPropertyView, error) {
	return t.inner.Property("Prompt")
}

func (t *VideoGenerationPlanRequestClassView) PropertyLanguage() (ClassPropertyView, error) {
	return t.inner.Property("Language")
}

func (t *VideoGenerationPlanRequestClassView) PropertyResolution() (ClassPropertyView, error) {
	return t.inner.Property("Resolution")
}

func (t *VideoGenerationPlanRequestClassView) PropertyScript() (ClassPropertyView, error) {
	return t.inner.Property("Script")
}

func (t *VideoGenerationPlanRequestClassView) PropertyEnableThinking() (ClassPropertyView, error) {
	return t.inner.Property("enableThinking")
}

func (t *TypeBuilder) VideoGenerationPlanRequest() (*VideoGenerationPlanRequestClassView, error) {
	bld, err := t.inner.Class("VideoGenerationPlanRequest")
	if err != nil {
		return nil, err
	}
	return &VideoGenerationPlanRequestClassView{inner: bld}, nil
}

func (t *VideoGenerationPlanRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
