// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AddSceneRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *AddSceneRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AddSceneRequestClassView) PropertyComponentList() (ClassPropertyView, error) {
	return t.inner.Property("ComponentList")
}

func (t *AddSceneRequestClassView) PropertyVideoBranding() (ClassPropertyView, error) {
	return t.inner.Property("VideoBranding")
}

func (t *TypeBuilder) AddSceneRequest() (*AddSceneRequestClassView, error) {
	bld, err := t.inner.Class("AddSceneRequest")
	if err != nil {
		return nil, err
	}
	return &AddSceneRequestClassView{inner: bld}, nil
}

func (t *AddSceneRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AddSceneResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *AddSceneResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AddSceneResponseClassView) PropertyScene() (ClassPropertyView, error) {
	return t.inner.Property("scene")
}

func (t *TypeBuilder) AddSceneResponse() (*AddSceneResponseClassView, error) {
	bld, err := t.inner.Class("AddSceneResponse")
	if err != nil {
		return nil, err
	}
	return &AddSceneResponseClassView{inner: bld}, nil
}

func (t *AddSceneResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AnimationCategoriesClassView struct {
	inner baml.ClassBuilder
}

func (t *AnimationCategoriesClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AnimationCategoriesClassView) PropertyEntranceAnimations() (ClassPropertyView, error) {
	return t.inner.Property("entranceAnimations")
}

func (t *TypeBuilder) AnimationCategories() (*AnimationCategoriesClassView, error) {
	bld, err := t.inner.Class("AnimationCategories")
	if err != nil {
		return nil, err
	}
	return &AnimationCategoriesClassView{inner: bld}, nil
}

func (t *AnimationCategoriesClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AskUserQuestionClassView struct {
	inner baml.ClassBuilder
}

func (t *AskUserQuestionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AskUserQuestionClassView) PropertyTool_name() (ClassPropertyView, error) {
	return t.inner.Property("tool_name")
}

func (t *AskUserQuestionClassView) PropertyQuestionType() (ClassPropertyView, error) {
	return t.inner.Property("questionType")
}

func (t *AskUserQuestionClassView) PropertyQuestion_text() (ClassPropertyView, error) {
	return t.inner.Property("question_text")
}

func (t *AskUserQuestionClassView) PropertyOptions() (ClassPropertyView, error) {
	return t.inner.Property("options")
}

func (t *AskUserQuestionClassView) PropertyAllow_custom_entry() (ClassPropertyView, error) {
	return t.inner.Property("allow_custom_entry")
}

func (t *AskUserQuestionClassView) PropertyAttachmentUrl() (ClassPropertyView, error) {
	return t.inner.Property("attachmentUrl")
}

func (t *AskUserQuestionClassView) PropertyThinkingSummary() (ClassPropertyView, error) {
	return t.inner.Property("thinkingSummary")
}

func (t *TypeBuilder) AskUserQuestion() (*AskUserQuestionClassView, error) {
	bld, err := t.inner.Class("AskUserQuestion")
	if err != nil {
		return nil, err
	}
	return &AskUserQuestionClassView{inner: bld}, nil
}

func (t *AskUserQuestionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AssetAnalysisClassView struct {
	inner baml.ClassBuilder
}

func (t *AssetAnalysisClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AssetAnalysisClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *AssetAnalysisClassView) PropertyTags() (ClassPropertyView, error) {
	return t.inner.Property("tags")
}

func (t *TypeBuilder) AssetAnalysis() (*AssetAnalysisClassView, error) {
	bld, err := t.inner.Class("AssetAnalysis")
	if err != nil {
		return nil, err
	}
	return &AssetAnalysisClassView{inner: bld}, nil
}

func (t *AssetAnalysisClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type CategoryClassView struct {
	inner baml.ClassBuilder
}

func (t *CategoryClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *CategoryClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *CategoryClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *TypeBuilder) Category() (*CategoryClassView, error) {
	bld, err := t.inner.Class("Category")
	if err != nil {
		return nil, err
	}
	return &CategoryClassView{inner: bld}, nil
}

func (t *CategoryClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EditAnimationCodeRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *EditAnimationCodeRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EditAnimationCodeRequestClassView) PropertyCode() (ClassPropertyView, error) {
	return t.inner.Property("code")
}

func (t *EditAnimationCodeRequestClassView) PropertyPrompt() (ClassPropertyView, error) {
	return t.inner.Property("prompt")
}

func (t *TypeBuilder) EditAnimationCodeRequest() (*EditAnimationCodeRequestClassView, error) {
	bld, err := t.inner.Class("EditAnimationCodeRequest")
	if err != nil {
		return nil, err
	}
	return &EditAnimationCodeRequestClassView{inner: bld}, nil
}

func (t *EditAnimationCodeRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EditAnimationCodeResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *EditAnimationCodeResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EditAnimationCodeResponseClassView) PropertyType() (ClassPropertyView, error) {
	return t.inner.Property("type")
}

func (t *EditAnimationCodeResponseClassView) PropertyEdits() (ClassPropertyView, error) {
	return t.inner.Property("edits")
}

func (t *TypeBuilder) EditAnimationCodeResponse() (*EditAnimationCodeResponseClassView, error) {
	bld, err := t.inner.Class("EditAnimationCodeResponse")
	if err != nil {
		return nil, err
	}
	return &EditAnimationCodeResponseClassView{inner: bld}, nil
}

func (t *EditAnimationCodeResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type EditStringClassView struct {
	inner baml.ClassBuilder
}

func (t *EditStringClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *EditStringClassView) PropertyDescription() (ClassPropertyView, error) {
	return t.inner.Property("description")
}

func (t *EditStringClassView) PropertyOldString() (ClassPropertyView, error) {
	return t.inner.Property("oldString")
}

func (t *EditStringClassView) PropertyNewString() (ClassPropertyView, error) {
	return t.inner.Property("newString")
}

func (t *TypeBuilder) EditString() (*EditStringClassView, error) {
	bld, err := t.inner.Class("EditString")
	if err != nil {
		return nil, err
	}
	return &EditStringClassView{inner: bld}, nil
}

func (t *EditStringClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationCodeRequestV2ClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationCodeRequestV2ClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationCodeRequestV2ClassView) PropertyScene() (ClassPropertyView, error) {
	return t.inner.Property("scene")
}

func (t *TypeBuilder) GenerateAnimationCodeRequestV2() (*GenerateAnimationCodeRequestV2ClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationCodeRequestV2")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationCodeRequestV2ClassView{inner: bld}, nil
}

func (t *GenerateAnimationCodeRequestV2ClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GenerateAnimationCodeResponseV2ClassView struct {
	inner baml.ClassBuilder
}

func (t *GenerateAnimationCodeResponseV2ClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GenerateAnimationCodeResponseV2ClassView) PropertyCode() (ClassPropertyView, error) {
	return t.inner.Property("code")
}

func (t *GenerateAnimationCodeResponseV2ClassView) PropertySettledFrame() (ClassPropertyView, error) {
	return t.inner.Property("settledFrame")
}

func (t *GenerateAnimationCodeResponseV2ClassView) PropertyThinkingSummary() (ClassPropertyView, error) {
	return t.inner.Property("thinkingSummary")
}

func (t *TypeBuilder) GenerateAnimationCodeResponseV2() (*GenerateAnimationCodeResponseV2ClassView, error) {
	bld, err := t.inner.Class("GenerateAnimationCodeResponseV2")
	if err != nil {
		return nil, err
	}
	return &GenerateAnimationCodeResponseV2ClassView{inner: bld}, nil
}

func (t *GenerateAnimationCodeResponseV2ClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type GeneratedVideoPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *GeneratedVideoPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *GeneratedVideoPlanClassView) PropertyVideoName() (ClassPropertyView, error) {
	return t.inner.Property("videoName")
}

func (t *GeneratedVideoPlanClassView) PropertySections() (ClassPropertyView, error) {
	return t.inner.Property("sections")
}

func (t *GeneratedVideoPlanClassView) PropertyThinkingSummary() (ClassPropertyView, error) {
	return t.inner.Property("thinkingSummary")
}

func (t *TypeBuilder) GeneratedVideoPlan() (*GeneratedVideoPlanClassView, error) {
	bld, err := t.inner.Class("GeneratedVideoPlan")
	if err != nil {
		return nil, err
	}
	return &GeneratedVideoPlanClassView{inner: bld}, nil
}

func (t *GeneratedVideoPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchCategoriesRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchCategoriesRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchCategoriesRequestClassView) PropertyCategories() (ClassPropertyView, error) {
	return t.inner.Property("categories")
}

func (t *MatchCategoriesRequestClassView) PropertyQuery() (ClassPropertyView, error) {
	return t.inner.Property("query")
}

func (t *TypeBuilder) MatchCategoriesRequest() (*MatchCategoriesRequestClassView, error) {
	bld, err := t.inner.Class("MatchCategoriesRequest")
	if err != nil {
		return nil, err
	}
	return &MatchCategoriesRequestClassView{inner: bld}, nil
}

func (t *MatchCategoriesRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MatchCategoriesResponseClassView struct {
	inner baml.ClassBuilder
}

func (t *MatchCategoriesResponseClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MatchCategoriesResponseClassView) PropertyCategories() (ClassPropertyView, error) {
	return t.inner.Property("categories")
}

func (t *TypeBuilder) MatchCategoriesResponse() (*MatchCategoriesResponseClassView, error) {
	bld, err := t.inner.Class("MatchCategoriesResponse")
	if err != nil {
		return nil, err
	}
	return &MatchCategoriesResponseClassView{inner: bld}, nil
}

func (t *MatchCategoriesResponseClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type MessageClassView struct {
	inner baml.ClassBuilder
}

func (t *MessageClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *MessageClassView) PropertyRole() (ClassPropertyView, error) {
	return t.inner.Property("role")
}

func (t *MessageClassView) PropertyContent() (ClassPropertyView, error) {
	return t.inner.Property("content")
}

func (t *MessageClassView) PropertyTool_call_id() (ClassPropertyView, error) {
	return t.inner.Property("tool_call_id")
}

func (t *TypeBuilder) Message() (*MessageClassView, error) {
	bld, err := t.inner.Class("Message")
	if err != nil {
		return nil, err
	}
	return &MessageClassView{inner: bld}, nil
}

func (t *MessageClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SceneClassView struct {
	inner baml.ClassBuilder
}

func (t *SceneClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SceneClassView) PropertyIndex() (ClassPropertyView, error) {
	return t.inner.Property("index")
}

func (t *SceneClassView) PropertyElements() (ClassPropertyView, error) {
	return t.inner.Property("elements")
}

func (t *SceneClassView) PropertyThinkingSummary() (ClassPropertyView, error) {
	return t.inner.Property("thinkingSummary")
}

func (t *TypeBuilder) Scene() (*SceneClassView, error) {
	bld, err := t.inner.Class("Scene")
	if err != nil {
		return nil, err
	}
	return &SceneClassView{inner: bld}, nil
}

func (t *SceneClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SceneElementClassView struct {
	inner baml.ClassBuilder
}

func (t *SceneElementClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SceneElementClassView) PropertyComponent() (ClassPropertyView, error) {
	return t.inner.Property("component")
}

func (t *SceneElementClassView) PropertyProps() (ClassPropertyView, error) {
	return t.inner.Property("props")
}

func (t *SceneElementClassView) PropertyChildren() (ClassPropertyView, error) {
	return t.inner.Property("children")
}

func (t *TypeBuilder) SceneElement() (*SceneElementClassView, error) {
	bld, err := t.inner.Class("SceneElement")
	if err != nil {
		return nil, err
	}
	return &SceneElementClassView{inner: bld}, nil
}

func (t *SceneElementClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type SceneSectionClassView struct {
	inner baml.ClassBuilder
}

func (t *SceneSectionClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *SceneSectionClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *SceneSectionClassView) PropertySlides() (ClassPropertyView, error) {
	return t.inner.Property("slides")
}

func (t *TypeBuilder) SceneSection() (*SceneSectionClassView, error) {
	bld, err := t.inner.Class("SceneSection")
	if err != nil {
		return nil, err
	}
	return &SceneSectionClassView{inner: bld}, nil
}

func (t *SceneSectionClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ScriptItemClassView struct {
	inner baml.ClassBuilder
}

func (t *ScriptItemClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ScriptItemClassView) PropertyName() (ClassPropertyView, error) {
	return t.inner.Property("name")
}

func (t *ScriptItemClassView) PropertyVoiceover() (ClassPropertyView, error) {
	return t.inner.Property("voiceover")
}

func (t *ScriptItemClassView) PropertyReference() (ClassPropertyView, error) {
	return t.inner.Property("reference")
}

func (t *TypeBuilder) ScriptItem() (*ScriptItemClassView, error) {
	bld, err := t.inner.Class("ScriptItem")
	if err != nil {
		return nil, err
	}
	return &ScriptItemClassView{inner: bld}, nil
}

func (t *ScriptItemClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoBrandingClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoBrandingClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoBrandingClassView) PropertyBrandGuideLines() (ClassPropertyView, error) {
	return t.inner.Property("brandGuideLines")
}

func (t *VideoBrandingClassView) PropertyAttachments() (ClassPropertyView, error) {
	return t.inner.Property("attachments")
}

func (t *TypeBuilder) VideoBranding() (*VideoBrandingClassView, error) {
	bld, err := t.inner.Class("VideoBranding")
	if err != nil {
		return nil, err
	}
	return &VideoBrandingClassView{inner: bld}, nil
}

func (t *VideoBrandingClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoGenerationPlanClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoGenerationPlanClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoGenerationPlanClassView) PropertyPlan() (ClassPropertyView, error) {
	return t.inner.Property("plan")
}

func (t *TypeBuilder) VideoGenerationPlan() (*VideoGenerationPlanClassView, error) {
	bld, err := t.inner.Class("VideoGenerationPlan")
	if err != nil {
		return nil, err
	}
	return &VideoGenerationPlanClassView{inner: bld}, nil
}

func (t *VideoGenerationPlanClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type VideoGenerationPlanRequestClassView struct {
	inner baml.ClassBuilder
}

func (t *VideoGenerationPlanRequestClassView) ListProperties() ([]ClassPropertyView, error) {
	result, err := t.inner.ListProperties()
	if err != nil {
		return nil, err
	}
	builders := make([]ClassPropertyView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *VideoGenerationPlanRequestClassView) PropertyDuration() (ClassPropertyView, error) {
	return t.inner.Property("Duration")
}

func (t *VideoGenerationPlanRequestClassView) PropertyPrompt() (ClassPropertyView, error) {
	return t.inner.Property("Prompt")
}

func (t *VideoGenerationPlanRequestClassView) PropertyLanguage() (ClassPropertyView, error) {
	return t.inner.Property("Language")
}

func (t *VideoGenerationPlanRequestClassView) PropertyResolution() (ClassPropertyView, error) {
	return t.inner.Property("Resolution")
}

func (t *VideoGenerationPlanRequestClassView) PropertyScript() (ClassPropertyView, error) {
	return t.inner.Property("Script")
}

func (t *VideoGenerationPlanRequestClassView) PropertyVideoBranding() (ClassPropertyView, error) {
	return t.inner.Property("VideoBranding")
}

func (t *VideoGenerationPlanRequestClassView) PropertyComponentList() (ClassPropertyView, error) {
	return t.inner.Property("ComponentList")
}

func (t *VideoGenerationPlanRequestClassView) PropertyAnimationCategories() (ClassPropertyView, error) {
	return t.inner.Property("AnimationCategories")
}

func (t *TypeBuilder) VideoGenerationPlanRequest() (*VideoGenerationPlanRequestClassView, error) {
	bld, err := t.inner.Class("VideoGenerationPlanRequest")
	if err != nil {
		return nil, err
	}
	return &VideoGenerationPlanRequestClassView{inner: bld}, nil
}

func (t *VideoGenerationPlanRequestClassView) Type() (baml.Type, error) {
	return t.inner.Type()
}
