// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package type_builder

import baml "github.com/boundaryml/baml/engine/language_client_go/pkg"

type AnimationCodeEditTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *AnimationCodeEditTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AnimationCodeEditTypeEnumView) ValueTARGETED_EDITS() (EnumValueView, error) {
	return t.inner.Value("TARGETED_EDITS")
}

func (t *AnimationCodeEditTypeEnumView) ValueFULL_REWRITE() (EnumValueView, error) {
	return t.inner.Value("FULL_REWRITE")
}

func (t *TypeBuilder) AnimationCodeEditType() (*AnimationCodeEditTypeEnumView, error) {
	bld, err := t.inner.Enum("AnimationCodeEditType")
	if err != nil {
		return nil, err
	}
	return &AnimationCodeEditTypeEnumView{inner: bld}, nil
}

func (t *AnimationCodeEditTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type AskUserQuestionTypeEnumView struct {
	inner baml.EnumBuilder
}

func (t *AskUserQuestionTypeEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *AskUserQuestionTypeEnumView) ValueGENERIC() (EnumValueView, error) {
	return t.inner.Value("GENERIC")
}

func (t *AskUserQuestionTypeEnumView) ValueATTACHMENT_CLARIFICATION() (EnumValueView, error) {
	return t.inner.Value("ATTACHMENT_CLARIFICATION")
}

func (t *AskUserQuestionTypeEnumView) ValueUPLOAD_ATTACHMENT() (EnumValueView, error) {
	return t.inner.Value("UPLOAD_ATTACHMENT")
}

func (t *TypeBuilder) AskUserQuestionType() (*AskUserQuestionTypeEnumView, error) {
	bld, err := t.inner.Enum("AskUserQuestionType")
	if err != nil {
		return nil, err
	}
	return &AskUserQuestionTypeEnumView{inner: bld}, nil
}

func (t *AskUserQuestionTypeEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}

type ColorTokenEnumView struct {
	inner baml.EnumBuilder
}

func (t *ColorTokenEnumView) ListValues() ([]EnumValueView, error) {
	result, err := t.inner.ListValues()
	if err != nil {
		return nil, err
	}
	builders := make([]EnumValueView, len(result))
	for i, p := range result {
		builders[i] = p
	}
	return builders, nil
}

func (t *ColorTokenEnumView) ValuePRIMARY() (EnumValueView, error) {
	return t.inner.Value("PRIMARY")
}

func (t *TypeBuilder) ColorToken() (*ColorTokenEnumView, error) {
	bld, err := t.inner.Enum("ColorToken")
	if err != nil {
		return nil, err
	}
	return &ColorTokenEnumView{inner: bld}, nil
}

func (t *ColorTokenEnumView) Type() (baml.Type, error) {
	return t.inner.Type()
}
