// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/audio.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file coasterai/core/v1/audio.proto.
 */
export const file_coasterai_core_v1_audio = /*@__PURE__*/
  fileDesc("Ch1jb2FzdGVyYWkvY29yZS92MS9hdWRpby5wcm90bxIRY29hc3RlcmFpLmNvcmUudjEiVAoPQmFja2dyb3VuZFRyYWNrEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSCwoDdXJsGAMgASgJEhEKBGljb24YBCABKAlIAIgBAUIHCgVfaWNvbkI7WjlnaXRodWIuY29tL3NoYW5rMzE4L2NvYXN0ZXJhaS9wYi9jb2FzdGVyYWkvY29yZS92MTtwYmNvcmViBnByb3RvMw", [file_google_protobuf_wrappers]);

/**
 * Describes the message coasterai.core.v1.BackgroundTrack.
 * Use `create(BackgroundTrackSchema)` to create a new message.
 */
export const BackgroundTrackSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_audio, 0);

