// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/brandkit.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";
import { file_coasterai_core_v1_media_asset } from "./media_asset_pb";

/**
 * Describes the file coasterai/core/v1/brandkit.proto.
 */
export const file_coasterai_core_v1_brandkit = /*@__PURE__*/
  fileDesc("CiBjb2FzdGVyYWkvY29yZS92MS9icmFuZGtpdC5wcm90bxIRY29hc3RlcmFpLmNvcmUudjEipAEKCkJyYW5kTWVkaWESLAoFYXNzZXQYASABKAsyHS5jb2FzdGVyYWkuY29yZS52MS5NZWRpYUFzc2V0EjcKCHByaW9yaXR5GAIgASgOMiUuY29hc3RlcmFpLmNvcmUudjEuQnJhbmRBc3NldFByaW9yaXR5Ei8KBHR5cGUYAyABKA4yIS5jb2FzdGVyYWkuY29yZS52MS5CcmFuZE1lZGlhVHlwZSJdCgpCcmFuZENvbG9yEhYKDmNvbG9yX2hleF9jb2RlGAEgASgJEjcKCHByaW9yaXR5GAIgASgOMiUuY29hc3RlcmFpLmNvcmUudjEuQnJhbmRBc3NldFByaW9yaXR5Ij0KEEJyYW5kU29jaWFsTWVkaWESCgoCaWQYASABKAkSEAoIcGxhdGZvcm0YAiABKAkSCwoDdXJsGAMgASgJIlIKCUJyYW5kRm9udBI3ChFnb29nbGVfZm9udHNfbmFtZRgBIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIMCgRuYW1lGAIgASgJIuACCg1CcmFuZElkZW50aXR5EgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSEwoLd2Vic2l0ZV91cmwYAyABKAkSLQoHdGFnbGluZRgEIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIxCgtkZXNjcmlwdGlvbhgFIAEoCzIcLmdvb2dsZS5wcm90b2J1Zi5TdHJpbmdWYWx1ZRIsCgVsb2dvcxgGIAMoCzIdLmNvYXN0ZXJhaS5jb3JlLnYxLkJyYW5kTWVkaWESNAoHc29jaWFscxgHIAMoCzIjLmNvYXN0ZXJhaS5jb3JlLnYxLkJyYW5kU29jaWFsTWVkaWESKwoFZm9udHMYCCADKAsyHC5jb2FzdGVyYWkuY29yZS52MS5CcmFuZEZvbnQSLQoGY29sb3JzGAkgAygLMh0uY29hc3RlcmFpLmNvcmUudjEuQnJhbmRDb2xvcirgAQoOQnJhbmRNZWRpYVR5cGUSIAocQlJBTkRfTUVESUFfVFlQRV9VTlNQRUNJRklFRBAAEhkKFUJSQU5EX01FRElBX1RZUEVfTE9HTxABEhkKFUJSQU5EX01FRElBX1RZUEVfSUNPThACEh0KGUJSQU5EX01FRElBX1RZUEVfV09SRE1BUksQAxIaChZCUkFORF9NRURJQV9UWVBFX0lNQUdFEAQSGgoWQlJBTkRfTUVESUFfVFlQRV9WSURFTxAFEh8KG0JSQU5EX01FRElBX1RZUEVfTU9PRF9CT0FSRBAGKpYCChJCcmFuZEFzc2V0UHJpb3JpdHkSJAogQlJBTkRfQVNTRVRfUFJJT1JJVFlfVU5TUEVDSUZJRUQQABIgChxCUkFORF9BU1NFVF9QUklPUklUWV9QUklNQVJZEAESIgoeQlJBTkRfQVNTRVRfUFJJT1JJVFlfU0VDT05EQVJZEAISHwobQlJBTkRfQVNTRVRfUFJJT1JJVFlfQUNDRU5UEAMSIwofQlJBTkRfQVNTRVRfUFJJT1JJVFlfQkFDS0dST1VORBAEEiUKIUJSQU5EX0FTU0VUX1BSSU9SSVRZX1RFWFRfUFJJTUFSWRAFEicKI0JSQU5EX0FTU0VUX1BSSU9SSVRZX1RFWFRfU0VDT05EQVJZEAZCO1o5Z2l0aHViLmNvbS9zaGFuazMxOC9jb2FzdGVyYWkvcGIvY29hc3RlcmFpL2NvcmUvdjE7cGJjb3JlYgZwcm90bzM", [file_google_protobuf_wrappers, file_coasterai_core_v1_media_asset]);

/**
 * Describes the message coasterai.core.v1.BrandMedia.
 * Use `create(BrandMediaSchema)` to create a new message.
 */
export const BrandMediaSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_brandkit, 0);

/**
 * Describes the message coasterai.core.v1.BrandColor.
 * Use `create(BrandColorSchema)` to create a new message.
 */
export const BrandColorSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_brandkit, 1);

/**
 * Describes the message coasterai.core.v1.BrandSocialMedia.
 * Use `create(BrandSocialMediaSchema)` to create a new message.
 */
export const BrandSocialMediaSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_brandkit, 2);

/**
 * Describes the message coasterai.core.v1.BrandFont.
 * Use `create(BrandFontSchema)` to create a new message.
 */
export const BrandFontSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_brandkit, 3);

/**
 * Describes the message coasterai.core.v1.BrandIdentity.
 * Use `create(BrandIdentitySchema)` to create a new message.
 */
export const BrandIdentitySchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_brandkit, 4);

/**
 * Describes the enum coasterai.core.v1.BrandMediaType.
 */
export const BrandMediaTypeSchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_brandkit, 0);

/**
 * @generated from enum coasterai.core.v1.BrandMediaType
 */
export const BrandMediaType = /*@__PURE__*/
  tsEnum(BrandMediaTypeSchema);

/**
 * Describes the enum coasterai.core.v1.BrandAssetPriority.
 */
export const BrandAssetPrioritySchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_brandkit, 1);

/**
 * @generated from enum coasterai.core.v1.BrandAssetPriority
 */
export const BrandAssetPriority = /*@__PURE__*/
  tsEnum(BrandAssetPrioritySchema);

