// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/chat.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file coasterai/core/v1/chat.proto.
 */
export declare const file_coasterai_core_v1_chat: GenFile;

/**
 * @generated from message coasterai.core.v1.ConversationMessage
 */
export declare type ConversationMessage = Message<"coasterai.core.v1.ConversationMessage"> & {
  /**
   * @generated from field: coasterai.core.v1.ConversationRole role = 1;
   */
  role: ConversationRole;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated string assetIds = 3;
   */
  assetIds: string[];

  /**
   * * Model used for generation 
   *
   * @generated from field: string model = 4;
   */
  model: string;

  /**
   * @generated from field: string codeSnapshot = 5;
   */
  codeSnapshot: string;

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 6;
   */
  createdAt?: Timestamp;
};

/**
 * Describes the message coasterai.core.v1.ConversationMessage.
 * Use `create(ConversationMessageSchema)` to create a new message.
 */
export declare const ConversationMessageSchema: GenMessage<ConversationMessage>;

/**
 * @generated from enum coasterai.core.v1.ConversationRole
 */
export enum ConversationRole {
  /**
   * @generated from enum value: CONVERSATION_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONVERSATION_ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: CONVERSATION_ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,

  /**
   * @generated from enum value: CONVERSATION_ROLE_TOOL = 3;
   */
  TOOL = 3,
}

/**
 * Describes the enum coasterai.core.v1.ConversationRole.
 */
export declare const ConversationRoleSchema: GenEnum<ConversationRole>;

