// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/chat.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { JsonObject, Message } from "@bufbuild/protobuf";
import type { Timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file coasterai/core/v1/chat.proto.
 */
export declare const file_coasterai_core_v1_chat: GenFile;

/**
 * @generated from message coasterai.core.v1.ConversationMessage
 */
export declare type ConversationMessage = Message<"coasterai.core.v1.ConversationMessage"> & {
  /**
   * @generated from field: coasterai.core.v1.ConversationRole role = 1;
   */
  role: ConversationRole;

  /**
   * @generated from field: string message = 2;
   */
  message: string;

  /**
   * @generated from field: repeated string assetIds = 3;
   */
  assetIds: string[];

  /**
   * * Model used for generation 
   *
   * @generated from field: optional coasterai.core.v1.AIModel aiModel = 4;
   */
  aiModel?: AIModel;

  /**
   * @generated from field: string codeSnapshot = 5;
   */
  codeSnapshot: string;

  /**
   * @generated from field: repeated string referenceIds = 6;
   */
  referenceIds: string[];

  /**
   * @generated from field: google.protobuf.Timestamp created_at = 7;
   */
  createdAt?: Timestamp;

  /**
   * @generated from field: coasterai.core.v1.ConversationMessageType type = 8;
   */
  type: ConversationMessageType;

  /**
   * @generated from field: optional google.protobuf.Struct defaultCodeData = 9;
   */
  defaultCodeData?: JsonObject;

  /**
   * @generated from field: optional int32 durationInFrames = 10;
   */
  durationInFrames?: number;

  /**
   * @generated from field: string id = 11;
   */
  id: string;

  /**
   * @generated from field: optional google.protobuf.Struct manualEdits = 12;
   */
  manualEdits?: JsonObject;
};

/**
 * Describes the message coasterai.core.v1.ConversationMessage.
 * Use `create(ConversationMessageSchema)` to create a new message.
 */
export declare const ConversationMessageSchema: GenMessage<ConversationMessage>;

/**
 * @generated from enum coasterai.core.v1.AIModel
 */
export enum AIModel {
  /**
   * @generated from enum value: AI_MODEL_UNSPECIFIED = 0;
   */
  AI_MODEL_UNSPECIFIED = 0,

  /**
   * @generated from enum value: AI_MODEL_GEMINI_3_PRO = 1;
   */
  AI_MODEL_GEMINI_3_PRO = 1,

  /**
   * @generated from enum value: AI_MODEL_GPT_5_5 = 2;
   */
  AI_MODEL_GPT_5_5 = 2,

  /**
   * @generated from enum value: AI_MODEL_GPT_5_6_SOL = 3;
   */
  AI_MODEL_GPT_5_6_SOL = 3,
}

/**
 * Describes the enum coasterai.core.v1.AIModel.
 */
export declare const AIModelSchema: GenEnum<AIModel>;

/**
 * @generated from enum coasterai.core.v1.ConversationRole
 */
export enum ConversationRole {
  /**
   * @generated from enum value: CONVERSATION_ROLE_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: CONVERSATION_ROLE_USER = 1;
   */
  USER = 1,

  /**
   * @generated from enum value: CONVERSATION_ROLE_ASSISTANT = 2;
   */
  ASSISTANT = 2,

  /**
   * @generated from enum value: CONVERSATION_ROLE_TOOL = 3;
   */
  TOOL = 3,
}

/**
 * Describes the enum coasterai.core.v1.ConversationRole.
 */
export declare const ConversationRoleSchema: GenEnum<ConversationRole>;

/**
 * @generated from enum coasterai.core.v1.ConversationMessageType
 */
export enum ConversationMessageType {
  /**
   * @generated from enum value: CONVERSATION_MESSAGE_TYPE_UNSPECIFIED = 0;
   */
  CONVERSATION_MESSAGE_TYPE_UNSPECIFIED = 0,

  /**
   * Thinking before the code, eg tool calls etc
   *
   * @generated from enum value: CONVERSATION_MESSAGE_THINKING = 1;
   */
  CONVERSATION_MESSAGE_THINKING = 1,

  /**
   * Thinking for the code is generated
   *
   * @generated from enum value: CONVERSATION_MESSAGE_FINAL_THINKING = 2;
   */
  CONVERSATION_MESSAGE_FINAL_THINKING = 2,

  /**
   * @generated from enum value: CONVERSATION_MESSAGE_MANUAL_EDITS = 3;
   */
  CONVERSATION_MESSAGE_MANUAL_EDITS = 3,

  /**
   * @generated from enum value: CONVERSATION_MESSAGE_TYPE_CHECKPOINT = 4;
   */
  CONVERSATION_MESSAGE_TYPE_CHECKPOINT = 4,
}

/**
 * Describes the enum coasterai.core.v1.ConversationMessageType.
 */
export declare const ConversationMessageTypeSchema: GenEnum<ConversationMessageType>;

