// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/credits.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import { fileDesc, messageDesc } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_struct, file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file coasterai/core/v1/credits.proto.
 */
export const file_coasterai_core_v1_credits = /*@__PURE__*/
  fileDesc("Ch9jb2FzdGVyYWkvY29yZS92MS9jcmVkaXRzLnByb3RvEhFjb2FzdGVyYWkuY29yZS52MSJvChFDcmVkaXRMZWRnZXJFbnRyeRIKCgJpZBgBIAEoCRIuCgpjcmVhdGVkX2F0GAIgASgLMhouZ29vZ2xlLnByb3RvYnVmLlRpbWVzdGFtcBIOCgZhbW91bnQYAyABKAUSDgoGYWN0aW9uGAQgASgJIk0KEUdldENyZWRpdHNSZXF1ZXN0EhgKC3JlZmVyZW5jZUlEGAEgASgJSACIAQESDgoGbGVkZ2VyGAIgASgIQg4KDF9yZWZlcmVuY2VJRCJeChJHZXRDcmVkaXRzUmVzcG9uc2USEQoJYXZhaWxhYmxlGAEgASgFEjUKB2VudHJpZXMYAiADKAsyJC5jb2FzdGVyYWkuY29yZS52MS5DcmVkaXRMZWRnZXJFbnRyeUI7WjlnaXRodWIuY29tL3NoYW5rMzE4L2NvYXN0ZXJhaS9wYi9jb2FzdGVyYWkvY29yZS92MTtwYmNvcmViBnByb3RvMw", [file_google_protobuf_timestamp, file_google_protobuf_struct]);

/**
 * Describes the message coasterai.core.v1.CreditLedgerEntry.
 * Use `create(CreditLedgerEntrySchema)` to create a new message.
 */
export const CreditLedgerEntrySchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_credits, 0);

/**
 * Describes the message coasterai.core.v1.GetCreditsRequest.
 * Use `create(GetCreditsRequestSchema)` to create a new message.
 */
export const GetCreditsRequestSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_credits, 1);

/**
 * Describes the message coasterai.core.v1.GetCreditsResponse.
 * Use `create(GetCreditsResponseSchema)` to create a new message.
 */
export const GetCreditsResponseSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_credits, 2);

