// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/media_asset.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_wrappers } from "@bufbuild/protobuf/wkt";

/**
 * Describes the file coasterai/core/v1/media_asset.proto.
 */
export const file_coasterai_core_v1_media_asset = /*@__PURE__*/
  fileDesc("CiNjb2FzdGVyYWkvY29yZS92MS9tZWRpYV9hc3NldC5wcm90bxIRY29hc3RlcmFpLmNvcmUudjEiQQoSU2VsZWN0ZWRNZWRpYUFzc2V0Eg8KB2Fzc2V0SUQYASABKAkSEQoEbm90ZRgCIAEoCUgAiAEBQgcKBV9ub3RlIt8BCgpNZWRpYUFzc2V0EgsKA3VybBgBIAEoCRIUCgx0aHVtYm5haWxVcmwYAiABKAkSDQoFd2lkdGgYAyABKAISDgoGaGVpZ2h0GAQgASgCEhAKCG1pbWVUeXBlGAUgASgJEgwKBHNpemUYBiABKAISDgoGZmlsZUlkGAcgASgJEhAKCGZpbGVOYW1lGAggASgJEgoKAmlkGAkgASgJEi8KCW1lZGlhVHlwZRgKIAEoDjIcLmNvYXN0ZXJhaS5jb3JlLnYxLk1lZGlhVHlwZRIQCghkdXJhdGlvbhgLIAEoAiqQAQoJTWVkaWFUeXBlEhgKFE1FRElBX1RZUEVfVU5ERUZJTkVEEAASFAoQTUVESUFfVFlQRV9JTUFHRRABEhQKEE1FRElBX1RZUEVfVklERU8QAhISCg5NRURJQV9UWVBFX1NWRxADEhMKD01FRElBX1RZUEVfQ09ERRAEEhQKEE1FRElBX1RZUEVfQVVESU8QBUI7WjlnaXRodWIuY29tL3NoYW5rMzE4L2NvYXN0ZXJhaS9wYi9jb2FzdGVyYWkvY29yZS92MTtwYmNvcmViBnByb3RvMw", [file_google_protobuf_wrappers]);

/**
 * Describes the message coasterai.core.v1.SelectedMediaAsset.
 * Use `create(SelectedMediaAssetSchema)` to create a new message.
 */
export const SelectedMediaAssetSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_media_asset, 0);

/**
 * Describes the message coasterai.core.v1.MediaAsset.
 * Use `create(MediaAssetSchema)` to create a new message.
 */
export const MediaAssetSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_media_asset, 1);

/**
 * Describes the enum coasterai.core.v1.MediaType.
 */
export const MediaTypeSchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_media_asset, 0);

/**
 * @generated from enum coasterai.core.v1.MediaType
 */
export const MediaType = /*@__PURE__*/
  tsEnum(MediaTypeSchema);

