// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/slide.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file coasterai/core/v1/slide.proto.
 */
export declare const file_coasterai_core_v1_slide: GenFile;

/**
 * @generated from message coasterai.core.v1.ImageSlideContent
 */
export declare type ImageSlideContent = Message<"coasterai.core.v1.ImageSlideContent"> & {
  /**
   * @generated from field: coasterai.core.v1.MetaData meta = 1;
   */
  meta?: MetaData;

  /**
   * @generated from field: string src = 2;
   */
  src: string;

  /**
   * @generated from field: google.protobuf.Struct style = 3;
   */
  style?: JsonObject;
};

/**
 * Describes the message coasterai.core.v1.ImageSlideContent.
 * Use `create(ImageSlideContentSchema)` to create a new message.
 */
export declare const ImageSlideContentSchema: GenMessage<ImageSlideContent>;

/**
 * @generated from message coasterai.core.v1.VideoSlideContent
 */
export declare type VideoSlideContent = Message<"coasterai.core.v1.VideoSlideContent"> & {
  /**
   * @generated from field: string src = 1;
   */
  src: string;

  /**
   * @generated from field: optional float startTime = 2;
   */
  startTime?: number;

  /**
   * @generated from field: optional float endTime = 3;
   */
  endTime?: number;
};

/**
 * Describes the message coasterai.core.v1.VideoSlideContent.
 * Use `create(VideoSlideContentSchema)` to create a new message.
 */
export declare const VideoSlideContentSchema: GenMessage<VideoSlideContent>;

/**
 * @generated from message coasterai.core.v1.MetaData
 */
export declare type MetaData = Message<"coasterai.core.v1.MetaData"> & {
  /**
   * @generated from field: optional float x = 2;
   */
  x?: number;

  /**
   * @generated from field: optional float y = 3;
   */
  y?: number;

  /**
   * @generated from field: optional float width = 4;
   */
  width?: number;

  /**
   * @generated from field: optional float height = 5;
   */
  height?: number;

  /**
   * @generated from field: optional float scale = 6;
   */
  scale?: number;

  /**
   * @generated from field: optional float rotation = 7;
   */
  rotation?: number;
};

/**
 * Describes the message coasterai.core.v1.MetaData.
 * Use `create(MetaDataSchema)` to create a new message.
 */
export declare const MetaDataSchema: GenMessage<MetaData>;

/**
 * @generated from message coasterai.core.v1.AnimationSlideContent
 */
export declare type AnimationSlideContent = Message<"coasterai.core.v1.AnimationSlideContent"> & {
  /**
   * @generated from field: string templateId = 1;
   */
  templateId: string;

  /**
   * @generated from field: google.protobuf.Struct templateConfig = 2;
   */
  templateConfig?: JsonObject;

  /**
   * @generated from field: coasterai.core.v1.MetaData meta = 3;
   */
  meta?: MetaData;
};

/**
 * Describes the message coasterai.core.v1.AnimationSlideContent.
 * Use `create(AnimationSlideContentSchema)` to create a new message.
 */
export declare const AnimationSlideContentSchema: GenMessage<AnimationSlideContent>;

/**
 * @generated from message coasterai.core.v1.StackSlideContent
 */
export declare type StackSlideContent = Message<"coasterai.core.v1.StackSlideContent"> & {
  /**
   * @generated from field: coasterai.core.v1.StackAnimationMode animationMode = 1;
   */
  animationMode: StackAnimationMode;

  /**
   * @generated from field: repeated coasterai.core.v1.Slide items = 2;
   */
  items: Slide[];
};

/**
 * Describes the message coasterai.core.v1.StackSlideContent.
 * Use `create(StackSlideContentSchema)` to create a new message.
 */
export declare const StackSlideContentSchema: GenMessage<StackSlideContent>;

/**
 * @generated from message coasterai.core.v1.SpotlightEffect
 */
export declare type SpotlightEffect = Message<"coasterai.core.v1.SpotlightEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float width = 4;
   */
  width: number;

  /**
   * @generated from field: float height = 5;
   */
  height: number;

  /**
   * @generated from field: float blurAmount = 6;
   */
  blurAmount: number;

  /**
   * @generated from field: float borderRadius = 7;
   */
  borderRadius: number;

  /**
   * @generated from field: float startTime = 8;
   */
  startTime: number;

  /**
   * @generated from field: float endTime = 9;
   */
  endTime: number;
};

/**
 * Describes the message coasterai.core.v1.SpotlightEffect.
 * Use `create(SpotlightEffectSchema)` to create a new message.
 */
export declare const SpotlightEffectSchema: GenMessage<SpotlightEffect>;

/**
 * @generated from message coasterai.core.v1.CalloutEffect
 */
export declare type CalloutEffect = Message<"coasterai.core.v1.CalloutEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float width = 4;
   */
  width: number;

  /**
   * @generated from field: float height = 5;
   */
  height: number;

  /**
   * @generated from field: float blurAmount = 6;
   */
  blurAmount: number;

  /**
   * @generated from field: float borderRadius = 7;
   */
  borderRadius: number;

  /**
   * @generated from field: float startTime = 8;
   */
  startTime: number;

  /**
   * @generated from field: float endTime = 9;
   */
  endTime: number;

  /**
   * @generated from field: string color = 10;
   */
  color: string;
};

/**
 * Describes the message coasterai.core.v1.CalloutEffect.
 * Use `create(CalloutEffectSchema)` to create a new message.
 */
export declare const CalloutEffectSchema: GenMessage<CalloutEffect>;

/**
 * @generated from message coasterai.core.v1.ZoomEffect
 */
export declare type ZoomEffect = Message<"coasterai.core.v1.ZoomEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float zoomLevel = 4;
   */
  zoomLevel: number;

  /**
   * @generated from field: float startTime = 5;
   */
  startTime: number;

  /**
   * @generated from field: float endTime = 6;
   */
  endTime: number;
};

/**
 * Describes the message coasterai.core.v1.ZoomEffect.
 * Use `create(ZoomEffectSchema)` to create a new message.
 */
export declare const ZoomEffectSchema: GenMessage<ZoomEffect>;

/**
 * @generated from message coasterai.core.v1.Slide
 */
export declare type Slide = Message<"coasterai.core.v1.Slide"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: coasterai.core.v1.SlideType type = 2;
   */
  type: SlideType;

  /**
   * @generated from field: string transcript = 3;
   */
  transcript: string;

  /**
   * @generated from field: float duration = 4;
   */
  duration: number;

  /**
   * @generated from field: coasterai.core.v1.TransitionType transition = 5;
   */
  transition: TransitionType;

  /**
   * @generated from field: optional float transitionDuration = 6;
   */
  transitionDuration?: number;

  /**
   * @generated from field: optional string backgroundColor = 7;
   */
  backgroundColor?: string;

  /**
   * @generated from oneof coasterai.core.v1.slide.content
   */
  content: {
    /**
     * @generated from field: coasterai.core.v1.ImageSlideContent image = 8;
     */
    value: ImageSlideContent;
    case: "image";
  } | {
    /**
     * @generated from field: coasterai.core.v1.VideoSlideContent video = 9;
     */
    value: VideoSlideContent;
    case: "video";
  } | {
    /**
     * @generated from field: coasterai.core.v1.AnimationSlideContent animation = 10;
     */
    value: AnimationSlideContent;
    case: "animation";
  } | {
    /**
     * @generated from field: coasterai.core.v1.StackSlideContent stack = 13;
     */
    value: StackSlideContent;
    case: "stack";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: optional bool voiceoverGenerated = 15;
   */
  voiceoverGenerated?: boolean;

  /**
   * @generated from field: optional bool isNested = 16;
   */
  isNested?: boolean;

  /**
   * @generated from field: repeated coasterai.core.v1.Slide subSlides = 17;
   */
  subSlides: Slide[];

  /**
   * @generated from field: repeated coasterai.core.v1.SpotlightEffect spotlights = 18;
   */
  spotlights: SpotlightEffect[];

  /**
   * @generated from field: repeated coasterai.core.v1.CalloutEffect callouts = 19;
   */
  callouts: CalloutEffect[];

  /**
   * @generated from field: repeated coasterai.core.v1.ZoomEffect zooms = 20;
   */
  zooms: ZoomEffect[];
};

/**
 * Describes the message coasterai.core.v1.Slide.
 * Use `create(SlideSchema)` to create a new message.
 */
export declare const SlideSchema: GenMessage<Slide>;

/**
 * @generated from message coasterai.core.v1.Section
 */
export declare type Section = Message<"coasterai.core.v1.Section"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * @generated from field: repeated coasterai.core.v1.Slide slides = 4;
   */
  slides: Slide[];

  /**
   * @generated from field: optional bool voiceoverGenerated = 5;
   */
  voiceoverGenerated?: boolean;
};

/**
 * Describes the message coasterai.core.v1.Section.
 * Use `create(SectionSchema)` to create a new message.
 */
export declare const SectionSchema: GenMessage<Section>;

/**
 * @generated from message coasterai.core.v1.Resolution
 */
export declare type Resolution = Message<"coasterai.core.v1.Resolution"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string name = 2;
   */
  name: string;

  /**
   * @generated from field: string aspect = 3;
   */
  aspect: string;

  /**
   * @generated from field: int32 width = 4;
   */
  width: number;

  /**
   * @generated from field: int32 height = 5;
   */
  height: number;
};

/**
 * Describes the message coasterai.core.v1.Resolution.
 * Use `create(ResolutionSchema)` to create a new message.
 */
export declare const ResolutionSchema: GenMessage<Resolution>;

/**
 * @generated from enum coasterai.core.v1.SlideType
 */
export enum SlideType {
  /**
   * @generated from enum value: SLIDE_TYPE_UNDEFINED = 0;
   */
  UNDEFINED = 0,

  /**
   * @generated from enum value: SLIDE_TYPE_IMAGE = 1;
   */
  IMAGE = 1,

  /**
   * @generated from enum value: SLIDE_TYPE_TEXT_ANIMATION = 2;
   */
  TEXT_ANIMATION = 2,

  /**
   * @generated from enum value: SLIDE_TYPE_INFOGRAPHIC = 3;
   */
  INFOGRAPHIC = 3,

  /**
   * @generated from enum value: SLIDE_TYPE_VISUAL_ANIMATION = 4;
   */
  VISUAL_ANIMATION = 4,

  /**
   * @generated from enum value: SLIDE_TYPE_VIDEO = 5;
   */
  VIDEO = 5,

  /**
   * @generated from enum value: SLIDE_TYPE_STACK = 6;
   */
  STACK = 6,
}

/**
 * Describes the enum coasterai.core.v1.SlideType.
 */
export declare const SlideTypeSchema: GenEnum<SlideType>;

/**
 * @generated from enum coasterai.core.v1.StackAnimationMode
 */
export enum StackAnimationMode {
  /**
   * @generated from enum value: STACK_ANIMATION_MODE_STACK = 0;
   */
  STACK = 0,

  /**
   * @generated from enum value: STACK_ANIMATION_MODE_REVEAL = 1;
   */
  REVEAL = 1,
}

/**
 * Describes the enum coasterai.core.v1.StackAnimationMode.
 */
export declare const StackAnimationModeSchema: GenEnum<StackAnimationMode>;

/**
 * @generated from enum coasterai.core.v1.TransitionType
 */
export enum TransitionType {
  /**
   * @generated from enum value: TRANSITION_NONE = 0;
   */
  TRANSITION_NONE = 0,

  /**
   * @generated from enum value: TRANSITION_FADE = 1;
   */
  TRANSITION_FADE = 1,

  /**
   * @generated from enum value: TRANSITION_SLIDE_LEFT = 2;
   */
  TRANSITION_SLIDE_LEFT = 2,

  /**
   * @generated from enum value: TRANSITION_SLIDE_RIGHT = 3;
   */
  TRANSITION_SLIDE_RIGHT = 3,

  /**
   * @generated from enum value: TRANSITION_SLIDE_UP = 4;
   */
  TRANSITION_SLIDE_UP = 4,
}

/**
 * Describes the enum coasterai.core.v1.TransitionType.
 */
export declare const TransitionTypeSchema: GenEnum<TransitionType>;

/**
 * @generated from enum coasterai.core.v1.EffectType
 */
export enum EffectType {
  /**
   * @generated from enum value: EFFECT_TYPE_UNDEFINED = 0;
   */
  UNDEFINED = 0,

  /**
   * @generated from enum value: EFFECT_TYPE_CALLOUT = 1;
   */
  CALLOUT = 1,

  /**
   * @generated from enum value: EFFECT_TYPE_SPOTLIGHT = 2;
   */
  SPOTLIGHT = 2,
}

/**
 * Describes the enum coasterai.core.v1.EffectType.
 */
export declare const EffectTypeSchema: GenEnum<EffectType>;

