// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/slide.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import type { GenEnum, GenFile, GenMessage } from "@bufbuild/protobuf/codegenv1";
import type { JsonObject, Message } from "@bufbuild/protobuf";

/**
 * Describes the file coasterai/core/v1/slide.proto.
 */
export declare const file_coasterai_core_v1_slide: GenFile;

/**
 * Mostly be used for debugging what AI created
 * Useful for rerunning the generation
 * selectedTemplateDescription is basically the prompt generated to created the animation
 * in case of existing template selectedTemplateDescription = template description
 *
 * @generated from message coasterai.core.v1.AnimationSlidePlan
 */
export declare type AnimationSlidePlan = Message<"coasterai.core.v1.AnimationSlidePlan"> & {
  /**
   * @generated from field: int64 index = 1;
   */
  index: bigint;

  /**
   * @generated from field: string beatDescription = 2;
   */
  beatDescription: string;

  /**
   * @generated from field: string animationType = 3;
   */
  animationType: string;

  /**
   * @generated from field: string categorySearcQquery = 4;
   */
  categorySearcQquery: string;

  /**
   * @generated from field: int64 durationInFrames = 5;
   */
  durationInFrames: bigint;

  /**
   * @generated from field: optional string voiceover = 6;
   */
  voiceover?: string;

  /**
   * @generated from field: optional string selectedTemplateDescription = 7;
   */
  selectedTemplateDescription?: string;

  /**
   * @generated from field: optional string thinking_summary = 8;
   */
  thinkingSummary?: string;
};

/**
 * Describes the message coasterai.core.v1.AnimationSlidePlan.
 * Use `create(AnimationSlidePlanSchema)` to create a new message.
 */
export declare const AnimationSlidePlanSchema: GenMessage<AnimationSlidePlan>;

/**
 * @generated from message coasterai.core.v1.MetaData
 */
export declare type MetaData = Message<"coasterai.core.v1.MetaData"> & {
  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float width = 4;
   */
  width: number;

  /**
   * @generated from field: float height = 5;
   */
  height: number;

  /**
   * @generated from field: optional float scale = 6;
   */
  scale?: number;

  /**
   * @generated from field: optional float rotation = 7;
   */
  rotation?: number;
};

/**
 * Describes the message coasterai.core.v1.MetaData.
 * Use `create(MetaDataSchema)` to create a new message.
 */
export declare const MetaDataSchema: GenMessage<MetaData>;

/**
 * @generated from message coasterai.core.v1.AnimationSlideContent
 */
export declare type AnimationSlideContent = Message<"coasterai.core.v1.AnimationSlideContent"> & {
  /**
   * @generated from field: coasterai.core.v1.CodeRegistry codeRegistry = 1;
   */
  codeRegistry?: CodeRegistry;

  /**
   * @generated from field: coasterai.core.v1.AnimationSlidePlan plan = 2;
   */
  plan?: AnimationSlidePlan;

  /**
   * @generated from field: google.protobuf.Struct edits = 3;
   */
  edits?: JsonObject;
};

/**
 * Describes the message coasterai.core.v1.AnimationSlideContent.
 * Use `create(AnimationSlideContentSchema)` to create a new message.
 */
export declare const AnimationSlideContentSchema: GenMessage<AnimationSlideContent>;

/**
 * @generated from message coasterai.core.v1.CodeRegistry
 */
export declare type CodeRegistry = Message<"coasterai.core.v1.CodeRegistry"> & {
  /**
   * @generated from field: string mUrl = 1;
   */
  mUrl: string;

  /**
   * @generated from field: string tUrl = 2;
   */
  tUrl: string;
};

/**
 * Describes the message coasterai.core.v1.CodeRegistry.
 * Use `create(CodeRegistrySchema)` to create a new message.
 */
export declare const CodeRegistrySchema: GenMessage<CodeRegistry>;

/**
 * @generated from message coasterai.core.v1.SpotlightEffect
 */
export declare type SpotlightEffect = Message<"coasterai.core.v1.SpotlightEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float width = 4;
   */
  width: number;

  /**
   * @generated from field: float height = 5;
   */
  height: number;

  /**
   * @generated from field: float blurAmount = 6;
   */
  blurAmount: number;

  /**
   * @generated from field: float borderRadius = 7;
   */
  borderRadius: number;

  /**
   * @generated from field: float startFrame = 8;
   */
  startFrame: number;

  /**
   * @generated from field: float endFrame = 9;
   */
  endFrame: number;
};

/**
 * Describes the message coasterai.core.v1.SpotlightEffect.
 * Use `create(SpotlightEffectSchema)` to create a new message.
 */
export declare const SpotlightEffectSchema: GenMessage<SpotlightEffect>;

/**
 * @generated from message coasterai.core.v1.CalloutEffect
 */
export declare type CalloutEffect = Message<"coasterai.core.v1.CalloutEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float width = 4;
   */
  width: number;

  /**
   * @generated from field: float height = 5;
   */
  height: number;

  /**
   * @generated from field: float blurAmount = 6;
   */
  blurAmount: number;

  /**
   * @generated from field: float borderRadius = 7;
   */
  borderRadius: number;

  /**
   * @generated from field: float startFrame = 8;
   */
  startFrame: number;

  /**
   * @generated from field: float endFrame = 9;
   */
  endFrame: number;

  /**
   * @generated from field: string color = 10;
   */
  color: string;
};

/**
 * Describes the message coasterai.core.v1.CalloutEffect.
 * Use `create(CalloutEffectSchema)` to create a new message.
 */
export declare const CalloutEffectSchema: GenMessage<CalloutEffect>;

/**
 * @generated from message coasterai.core.v1.ZoomEffect
 */
export declare type ZoomEffect = Message<"coasterai.core.v1.ZoomEffect"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: float x = 2;
   */
  x: number;

  /**
   * @generated from field: float y = 3;
   */
  y: number;

  /**
   * @generated from field: float zoomLevel = 4;
   */
  zoomLevel: number;

  /**
   * @generated from field: float startFrame = 5;
   */
  startFrame: number;

  /**
   * @generated from field: float endFrame = 6;
   */
  endFrame: number;
};

/**
 * Describes the message coasterai.core.v1.ZoomEffect.
 * Use `create(ZoomEffectSchema)` to create a new message.
 */
export declare const ZoomEffectSchema: GenMessage<ZoomEffect>;

/**
 * @generated from message coasterai.core.v1.Slide
 */
export declare type Slide = Message<"coasterai.core.v1.Slide"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string transcript = 3;
   */
  transcript: string;

  /**
   * @generated from field: coasterai.core.v1.TransitionType transition = 5;
   */
  transition: TransitionType;

  /**
   * @generated from field: optional int32 transitionDurationInFrames = 6;
   */
  transitionDurationInFrames?: number;

  /**
   * @generated from field: optional coasterai.core.v1.BackgroundStyle background_style = 7;
   */
  backgroundStyle?: BackgroundStyle;

  /**
   * @generated from field: optional coasterai.core.v1.TransitionDirection direction = 23;
   */
  direction?: TransitionDirection;

  /**
   * @generated from field: int32 durationInFrames = 25;
   */
  durationInFrames: number;

  /**
   * @generated from field: int32 settledFrame = 26;
   */
  settledFrame: number;

  /**
   * @generated from field: coasterai.core.v1.AnimationSlideContent content = 9;
   */
  content?: AnimationSlideContent;

  /**
   * @generated from field: optional bool voiceoverGenerated = 15;
   */
  voiceoverGenerated?: boolean;

  /**
   * @generated from field: optional bool isNested = 16;
   */
  isNested?: boolean;

  /**
   * @generated from field: repeated coasterai.core.v1.SpotlightEffect spotlights = 18;
   */
  spotlights: SpotlightEffect[];

  /**
   * @generated from field: repeated coasterai.core.v1.CalloutEffect callouts = 19;
   */
  callouts: CalloutEffect[];

  /**
   * @generated from field: repeated coasterai.core.v1.ZoomEffect zooms = 20;
   */
  zooms: ZoomEffect[];

  /**
   * @generated from field: google.protobuf.Struct plan = 21;
   */
  plan?: JsonObject;

  /**
   * @generated from field: coasterai.core.v1.SlideStatus slideStatus = 22;
   */
  slideStatus: SlideStatus;

  /**
   * @generated from field: int32 index = 24;
   */
  index: number;
};

/**
 * Describes the message coasterai.core.v1.Slide.
 * Use `create(SlideSchema)` to create a new message.
 */
export declare const SlideSchema: GenMessage<Slide>;

/**
 * @generated from message coasterai.core.v1.BackgroundStyle
 */
export declare type BackgroundStyle = Message<"coasterai.core.v1.BackgroundStyle"> & {
  /**
   * @generated from oneof coasterai.core.v1.BackgroundStyle.style
   */
  style: {
    /**
     * @generated from field: coasterai.core.v1.SolidColor solid = 1;
     */
    value: SolidColor;
    case: "solid";
  } | {
    /**
     * @generated from field: coasterai.core.v1.Gradient gradient = 2;
     */
    value: Gradient;
    case: "gradient";
  } | {
    /**
     * @generated from field: coasterai.core.v1.BackgroundImage image = 3;
     */
    value: BackgroundImage;
    case: "image";
  } | { case: undefined; value?: undefined };

  /**
   * @generated from field: bool apply_all = 4;
   */
  applyAll: boolean;

  /**
   * @generated from field: coasterai.core.v1.BackgroundPattern pattern = 5;
   */
  pattern: BackgroundPattern;

  /**
   * 0.0 to 1.0, defaults to 0.1
   *
   * @generated from field: optional float pattern_opacity = 6;
   */
  patternOpacity?: number;
};

/**
 * Describes the message coasterai.core.v1.BackgroundStyle.
 * Use `create(BackgroundStyleSchema)` to create a new message.
 */
export declare const BackgroundStyleSchema: GenMessage<BackgroundStyle>;

/**
 * @generated from message coasterai.core.v1.SolidColor
 */
export declare type SolidColor = Message<"coasterai.core.v1.SolidColor"> & {
  /**
   * Example: "#0f172a"
   *
   * @generated from field: string hex = 1;
   */
  hex: string;
};

/**
 * Describes the message coasterai.core.v1.SolidColor.
 * Use `create(SolidColorSchema)` to create a new message.
 */
export declare const SolidColorSchema: GenMessage<SolidColor>;

/**
 * @generated from message coasterai.core.v1.BackgroundImage
 */
export declare type BackgroundImage = Message<"coasterai.core.v1.BackgroundImage"> & {
  /**
   * CDN or storage URL
   *
   * @generated from field: string url = 1;
   */
  url: string;
};

/**
 * Describes the message coasterai.core.v1.BackgroundImage.
 * Use `create(BackgroundImageSchema)` to create a new message.
 */
export declare const BackgroundImageSchema: GenMessage<BackgroundImage>;

/**
 * @generated from message coasterai.core.v1.Gradient
 */
export declare type Gradient = Message<"coasterai.core.v1.Gradient"> & {
  /**
   * @generated from field: coasterai.core.v1.GradientType type = 1;
   */
  type: GradientType;

  /**
   * 0–360 degrees
   *
   * @generated from field: int32 angle = 2;
   */
  angle: number;

  /**
   * @generated from field: repeated coasterai.core.v1.GradientStop stops = 3;
   */
  stops: GradientStop[];
};

/**
 * Describes the message coasterai.core.v1.Gradient.
 * Use `create(GradientSchema)` to create a new message.
 */
export declare const GradientSchema: GenMessage<Gradient>;

/**
 * @generated from message coasterai.core.v1.GradientStop
 */
export declare type GradientStop = Message<"coasterai.core.v1.GradientStop"> & {
  /**
   * "#ffffff"
   *
   * @generated from field: string color = 1;
   */
  color: string;

  /**
   * 0–100 (%)
   *
   * @generated from field: int32 position = 2;
   */
  position: number;
};

/**
 * Describes the message coasterai.core.v1.GradientStop.
 * Use `create(GradientStopSchema)` to create a new message.
 */
export declare const GradientStopSchema: GenMessage<GradientStop>;

/**
 * @generated from message coasterai.core.v1.Section
 */
export declare type Section = Message<"coasterai.core.v1.Section"> & {
  /**
   * @generated from field: string id = 1;
   */
  id: string;

  /**
   * @generated from field: string title = 2;
   */
  title: string;

  /**
   * @generated from field: string color = 3;
   */
  color: string;

  /**
   * @generated from field: repeated coasterai.core.v1.Slide slides = 4;
   */
  slides: Slide[];

  /**
   * @generated from field: optional bool voiceoverGenerated = 5;
   */
  voiceoverGenerated?: boolean;

  /**
   * @generated from field: int32 index = 6;
   */
  index: number;
};

/**
 * Describes the message coasterai.core.v1.Section.
 * Use `create(SectionSchema)` to create a new message.
 */
export declare const SectionSchema: GenMessage<Section>;

/**
 * @generated from enum coasterai.core.v1.SlideStatus
 */
export enum SlideStatus {
  /**
   * @generated from enum value: SLIDE_STATUS_UNDEFINED = 0;
   */
  UNDEFINED = 0,

  /**
   * @generated from enum value: SLIDE_STATUS_GENERATED = 1;
   */
  GENERATED = 1,

  /**
   * @generated from enum value: SLIDE_STATUS_PENDING = 2;
   */
  PENDING = 2,
}

/**
 * Describes the enum coasterai.core.v1.SlideStatus.
 */
export declare const SlideStatusSchema: GenEnum<SlideStatus>;

/**
 * @generated from enum coasterai.core.v1.StackAnimationMode
 */
export enum StackAnimationMode {
  /**
   * @generated from enum value: STACK_ANIMATION_MODE_STACK = 0;
   */
  STACK = 0,

  /**
   * @generated from enum value: STACK_ANIMATION_MODE_REVEAL = 1;
   */
  REVEAL = 1,
}

/**
 * Describes the enum coasterai.core.v1.StackAnimationMode.
 */
export declare const StackAnimationModeSchema: GenEnum<StackAnimationMode>;

/**
 * @generated from enum coasterai.core.v1.TransitionType
 */
export enum TransitionType {
  /**
   * @generated from enum value: TRANSITION_NONE = 0;
   */
  TRANSITION_NONE = 0,

  /**
   * @generated from enum value: TRANSITION_FADE = 1;
   */
  TRANSITION_FADE = 1,

  /**
   * @generated from enum value: TRANSITION_SLIDE_LEFT = 2;
   */
  TRANSITION_SLIDE_LEFT = 2,

  /**
   * @generated from enum value: TRANSITION_SLIDE_RIGHT = 3;
   */
  TRANSITION_SLIDE_RIGHT = 3,

  /**
   * @generated from enum value: TRANSITION_SLIDE_UP = 4;
   */
  TRANSITION_SLIDE_UP = 4,

  /**
   * @generated from enum value: TRANSITION_SLIDE_DOWN = 5;
   */
  TRANSITION_SLIDE_DOWN = 5,

  /**
   * @generated from enum value: TRANSITION_WIPE_LEFT = 6;
   */
  TRANSITION_WIPE_LEFT = 6,

  /**
   * @generated from enum value: TRANSITION_WIPE_RIGHT = 7;
   */
  TRANSITION_WIPE_RIGHT = 7,

  /**
   * @generated from enum value: TRANSITION_WIPE_UP = 8;
   */
  TRANSITION_WIPE_UP = 8,

  /**
   * @generated from enum value: TRANSITION_WIPE_DOWN = 9;
   */
  TRANSITION_WIPE_DOWN = 9,

  /**
   * @generated from enum value: TRANSITION_FLIP_HORIZONTAL = 10;
   */
  TRANSITION_FLIP_HORIZONTAL = 10,

  /**
   * @generated from enum value: TRANSITION_FLIP_VERTICAL = 11;
   */
  TRANSITION_FLIP_VERTICAL = 11,

  /**
   * @generated from enum value: TRANSITION_CLOCK_WIPE = 12;
   */
  TRANSITION_CLOCK_WIPE = 12,

  /**
   * @generated from enum value: TRANSITION_FLIP_LEFT = 13;
   */
  TRANSITION_FLIP_LEFT = 13,

  /**
   * @generated from enum value: TRANSITION_FLIP_RIGHT = 14;
   */
  TRANSITION_FLIP_RIGHT = 14,

  /**
   * @generated from enum value: TRANSITION_FLIP_UP = 15;
   */
  TRANSITION_FLIP_UP = 15,

  /**
   * @generated from enum value: TRANSITION_FLIP_DOWN = 16;
   */
  TRANSITION_FLIP_DOWN = 16,

  /**
   * @generated from enum value: TRANSITION_IRIS = 17;
   */
  TRANSITION_IRIS = 17,
}

/**
 * Describes the enum coasterai.core.v1.TransitionType.
 */
export declare const TransitionTypeSchema: GenEnum<TransitionType>;

/**
 * @generated from enum coasterai.core.v1.TransitionDirection
 */
export enum TransitionDirection {
  /**
   * @generated from enum value: TRANSITION_DIRECTION_UNSPECIFIED = 0;
   */
  UNSPECIFIED = 0,

  /**
   * @generated from enum value: TRANSITION_DIRECTION_FROM_LEFT = 1;
   */
  FROM_LEFT = 1,

  /**
   * @generated from enum value: TRANSITION_DIRECTION_FROM_RIGHT = 2;
   */
  FROM_RIGHT = 2,

  /**
   * @generated from enum value: TRANSITION_DIRECTION_FROM_TOP = 3;
   */
  FROM_TOP = 3,

  /**
   * @generated from enum value: TRANSITION_DIRECTION_FROM_BOTTOM = 4;
   */
  FROM_BOTTOM = 4,
}

/**
 * Describes the enum coasterai.core.v1.TransitionDirection.
 */
export declare const TransitionDirectionSchema: GenEnum<TransitionDirection>;

/**
 * @generated from enum coasterai.core.v1.EffectType
 */
export enum EffectType {
  /**
   * @generated from enum value: EFFECT_TYPE_UNDEFINED = 0;
   */
  UNDEFINED = 0,

  /**
   * @generated from enum value: EFFECT_TYPE_CALLOUT = 1;
   */
  CALLOUT = 1,

  /**
   * @generated from enum value: EFFECT_TYPE_SPOTLIGHT = 2;
   */
  SPOTLIGHT = 2,

  /**
   * @generated from enum value: EFFECT_TYPE_ZOOM = 3;
   */
  ZOOM = 3,
}

/**
 * Describes the enum coasterai.core.v1.EffectType.
 */
export declare const EffectTypeSchema: GenEnum<EffectType>;

/**
 * @generated from enum coasterai.core.v1.GradientType
 */
export enum GradientType {
  /**
   * @generated from enum value: GRADIENT_TYPE_LINEAR = 0;
   */
  LINEAR = 0,

  /**
   * @generated from enum value: GRADIENT_TYPE_RADIAL = 1;
   */
  RADIAL = 1,
}

/**
 * Describes the enum coasterai.core.v1.GradientType.
 */
export declare const GradientTypeSchema: GenEnum<GradientType>;

/**
 * @generated from enum coasterai.core.v1.BackgroundPattern
 */
export enum BackgroundPattern {
  /**
   * @generated from enum value: BACKGROUND_PATTERN_NONE = 0;
   */
  NONE = 0,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_DOTS = 1;
   */
  DOTS = 1,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_GRID = 2;
   */
  GRID = 2,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_DIAGONAL_LINES = 3;
   */
  DIAGONAL_LINES = 3,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_CROSS_HATCH = 4;
   */
  CROSS_HATCH = 4,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_CIRCLES = 5;
   */
  CIRCLES = 5,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_HEXAGONS = 6;
   */
  HEXAGONS = 6,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_TRIANGLES = 7;
   */
  TRIANGLES = 7,

  /**
   * @generated from enum value: BACKGROUND_PATTERN_WAVES = 8;
   */
  WAVES = 8,
}

/**
 * Describes the enum coasterai.core.v1.BackgroundPattern.
 */
export declare const BackgroundPatternSchema: GenEnum<BackgroundPattern>;

