// @generated by protoc-gen-es v2.0.0 with parameter "target=js+dts"
// @generated from file coasterai/core/v1/video.proto (package coasterai.core.v1, syntax proto3)
/* eslint-disable */

import { enumDesc, fileDesc, messageDesc, tsEnum } from "@bufbuild/protobuf/codegenv1";
import { file_google_protobuf_timestamp } from "@bufbuild/protobuf/wkt";
import { file_coasterai_core_v1_slide } from "./slide_pb";

/**
 * Describes the file coasterai/core/v1/video.proto.
 */
export const file_coasterai_core_v1_video = /*@__PURE__*/
  fileDesc("Ch1jb2FzdGVyYWkvY29yZS92MS92aWRlby5wcm90bxIRY29hc3RlcmFpLmNvcmUudjEi0wIKDVZpZGVvTWV0YWRhdGESCwoDZnBzGAEgASgFEkEKEGJhY2tncm91bmRfc3R5bGUYAiABKAsyIi5jb2FzdGVyYWkuY29yZS52MS5CYWNrZ3JvdW5kU3R5bGVIAIgBARIxCgpyZXNvbHV0aW9uGAMgASgLMh0uY29hc3RlcmFpLmNvcmUudjEuUmVzb2x1dGlvbhIQCghkdXJhdGlvbhgEIAEoAhIOCgZwcm9tcHQYBSABKAkSGAoQYnJhbmRfbGlicmFyeV9pZBgGIAEoCRIyCghsYW5ndWFnZRgHIAEoDjIgLmNvYXN0ZXJhaS5jb3JlLnYxLlZpZGVvTGFuZ3VhZ2USIQoUYmFja2dyb3VuZF9hdWRpb191cmwYCCABKAlIAYgBAUITChFfYmFja2dyb3VuZF9zdHlsZUIXChVfYmFja2dyb3VuZF9hdWRpb191cmwi9gEKBVZpZGVvEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSLgoGY29uZmlnGAMgASgLMh4uY29hc3RlcmFpLmNvcmUudjEuVmlkZW9Db25maWcSMgoIbWV0YWRhdGEYBCABKAsyIC5jb2FzdGVyYWkuY29yZS52MS5WaWRlb01ldGFkYXRhEi4KCmNyZWF0ZWRfYXQYBSABKAsyGi5nb29nbGUucHJvdG9idWYuVGltZXN0YW1wEi4KBnN0YXR1cxgGIAEoDjIeLmNvYXN0ZXJhaS5jb3JlLnYxLlZpZGVvU3RhdHVzEg8KB3ZlcnNpb24YByABKAMiOwoLVmlkZW9Db25maWcSLAoIc2VjdGlvbnMYASADKAsyGi5jb2FzdGVyYWkuY29yZS52MS5TZWN0aW9uIjYKBlNjcmlwdBIsCgVpdGVtcxgBIAMoCzIdLmNvYXN0ZXJhaS5jb3JlLnYxLlNjcmlwdEl0ZW0iZgoKU2NyaXB0SXRlbRIMCgRuYW1lGAEgASgJEhYKCXZvaWNlb3ZlchgCIAEoCUgAiAEBEhYKCXJlZmVyZW5jZRgDIAEoCUgBiAEBQgwKCl92b2ljZW92ZXJCDAoKX3JlZmVyZW5jZSJVCgpSZXNvbHV0aW9uEgoKAmlkGAEgASgJEgwKBG5hbWUYAiABKAkSDgoGYXNwZWN0GAMgASgJEg0KBXdpZHRoGAQgASgFEg4KBmhlaWdodBgFIAEoBSreAQoLVmlkZW9TdGF0dXMSHAoYVklERU9fU1RBVFVTX1VOU1BFQ0lGSUVEEAASGwoXVklERU9fU1RBVFVTX1BST0NFU1NJTkcQARIaChZWSURFT19TVEFUVVNfQ09NUExFVEVEEAISFwoTVklERU9fU1RBVFVTX0ZBSUxFRBADEhkKFVZJREVPX1NUQVRVU19QTEFOTklORxAEEiMKH1ZJREVPX1NUQVRVU19QTEFOTklOR19DQU5DRUxMRUQQBRIfChtWSURFT19TVEFUVVNfVVNFUl9DQU5DRUxMRUQQBiolCg1WaWRlb0xhbmd1YWdlEhQKEFZJREVfTEFOR1VBR0VfRU4QACqDAQoOUmVzb2x1dGlvblR5cGUSHwobUkVTT0xVVElPTl9UWVBFX1VOU1BFQ0lGSUVEEAASEwoPUkVTT0xVVElPTl8xNl85EAESEgoOUkVTT0xVVElPTl80XzMQAhITCg9SRVNPTFVUSU9OXzlfMTYQAxISCg5SRVNPTFVUSU9OXzFfMRAEQjtaOWdpdGh1Yi5jb20vc2hhbmszMTgvY29hc3RlcmFpL3BiL2NvYXN0ZXJhaS9jb3JlL3YxO3BiY29yZWIGcHJvdG8z", [file_google_protobuf_timestamp, file_coasterai_core_v1_slide]);

/**
 * Describes the message coasterai.core.v1.VideoMetadata.
 * Use `create(VideoMetadataSchema)` to create a new message.
 */
export const VideoMetadataSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 0);

/**
 * Describes the message coasterai.core.v1.Video.
 * Use `create(VideoSchema)` to create a new message.
 */
export const VideoSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 1);

/**
 * Describes the message coasterai.core.v1.VideoConfig.
 * Use `create(VideoConfigSchema)` to create a new message.
 */
export const VideoConfigSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 2);

/**
 * Describes the message coasterai.core.v1.Script.
 * Use `create(ScriptSchema)` to create a new message.
 */
export const ScriptSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 3);

/**
 * Describes the message coasterai.core.v1.ScriptItem.
 * Use `create(ScriptItemSchema)` to create a new message.
 */
export const ScriptItemSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 4);

/**
 * Describes the message coasterai.core.v1.Resolution.
 * Use `create(ResolutionSchema)` to create a new message.
 */
export const ResolutionSchema = /*@__PURE__*/
  messageDesc(file_coasterai_core_v1_video, 5);

/**
 * Describes the enum coasterai.core.v1.VideoStatus.
 */
export const VideoStatusSchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_video, 0);

/**
 * @generated from enum coasterai.core.v1.VideoStatus
 */
export const VideoStatus = /*@__PURE__*/
  tsEnum(VideoStatusSchema);

/**
 * Describes the enum coasterai.core.v1.VideoLanguage.
 */
export const VideoLanguageSchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_video, 1);

/**
 * @generated from enum coasterai.core.v1.VideoLanguage
 */
export const VideoLanguage = /*@__PURE__*/
  tsEnum(VideoLanguageSchema);

/**
 * Describes the enum coasterai.core.v1.ResolutionType.
 */
export const ResolutionTypeSchema = /*@__PURE__*/
  enumDesc(file_coasterai_core_v1_video, 2);

/**
 * @generated from enum coasterai.core.v1.ResolutionType
 */
export const ResolutionType = /*@__PURE__*/
  tsEnum(ResolutionTypeSchema);

