// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: coasterai/core/v1/audio.proto

package pbcore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/wrapperspb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type BackgroundTrack struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Url           string                 `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Icon          *string                `protobuf:"bytes,4,opt,name=icon,proto3,oneof" json:"icon,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundTrack) Reset() {
	*x = BackgroundTrack{}
	mi := &file_coasterai_core_v1_audio_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundTrack) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundTrack) ProtoMessage() {}

func (x *BackgroundTrack) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_audio_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundTrack.ProtoReflect.Descriptor instead.
func (*BackgroundTrack) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_audio_proto_rawDescGZIP(), []int{0}
}

func (x *BackgroundTrack) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *BackgroundTrack) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *BackgroundTrack) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *BackgroundTrack) GetIcon() string {
	if x != nil && x.Icon != nil {
		return *x.Icon
	}
	return ""
}

var File_coasterai_core_v1_audio_proto protoreflect.FileDescriptor

const file_coasterai_core_v1_audio_proto_rawDesc = "" +
	"\n" +
	"\x1dcoasterai/core/v1/audio.proto\x12\x11coasterai.core.v1\x1a\x1egoogle/protobuf/wrappers.proto\"i\n" +
	"\x0fBackgroundTrack\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x10\n" +
	"\x03url\x18\x03 \x01(\tR\x03url\x12\x17\n" +
	"\x04icon\x18\x04 \x01(\tH\x00R\x04icon\x88\x01\x01B\a\n" +
	"\x05_iconB;Z9github.com/shank318/coasterai/pb/coasterai/core/v1;pbcoreb\x06proto3"

var (
	file_coasterai_core_v1_audio_proto_rawDescOnce sync.Once
	file_coasterai_core_v1_audio_proto_rawDescData []byte
)

func file_coasterai_core_v1_audio_proto_rawDescGZIP() []byte {
	file_coasterai_core_v1_audio_proto_rawDescOnce.Do(func() {
		file_coasterai_core_v1_audio_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_audio_proto_rawDesc), len(file_coasterai_core_v1_audio_proto_rawDesc)))
	})
	return file_coasterai_core_v1_audio_proto_rawDescData
}

var file_coasterai_core_v1_audio_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coasterai_core_v1_audio_proto_goTypes = []any{
	(*BackgroundTrack)(nil), // 0: coasterai.core.v1.BackgroundTrack
}
var file_coasterai_core_v1_audio_proto_depIdxs = []int32{
	0, // [0:0] is the sub-list for method output_type
	0, // [0:0] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_coasterai_core_v1_audio_proto_init() }
func file_coasterai_core_v1_audio_proto_init() {
	if File_coasterai_core_v1_audio_proto != nil {
		return
	}
	file_coasterai_core_v1_audio_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_audio_proto_rawDesc), len(file_coasterai_core_v1_audio_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coasterai_core_v1_audio_proto_goTypes,
		DependencyIndexes: file_coasterai_core_v1_audio_proto_depIdxs,
		MessageInfos:      file_coasterai_core_v1_audio_proto_msgTypes,
	}.Build()
	File_coasterai_core_v1_audio_proto = out.File
	file_coasterai_core_v1_audio_proto_goTypes = nil
	file_coasterai_core_v1_audio_proto_depIdxs = nil
}
