// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: coasterai/core/v1/chat.proto

package pbcore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AIModel int32

const (
	AIModel_AI_MODEL_UNSPECIFIED  AIModel = 0
	AIModel_AI_MODEL_GEMINI_3_PRO AIModel = 1
	AIModel_AI_MODEL_GPT_5_5      AIModel = 2
	AIModel_AI_MODEL_GPT_5_5_SOL  AIModel = 3
)

// Enum value maps for AIModel.
var (
	AIModel_name = map[int32]string{
		0: "AI_MODEL_UNSPECIFIED",
		1: "AI_MODEL_GEMINI_3_PRO",
		2: "AI_MODEL_GPT_5_5",
		3: "AI_MODEL_GPT_5_5_SOL",
	}
	AIModel_value = map[string]int32{
		"AI_MODEL_UNSPECIFIED":  0,
		"AI_MODEL_GEMINI_3_PRO": 1,
		"AI_MODEL_GPT_5_5":      2,
		"AI_MODEL_GPT_5_5_SOL":  3,
	}
)

func (x AIModel) Enum() *AIModel {
	p := new(AIModel)
	*p = x
	return p
}

func (x AIModel) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (AIModel) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_chat_proto_enumTypes[0].Descriptor()
}

func (AIModel) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_chat_proto_enumTypes[0]
}

func (x AIModel) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use AIModel.Descriptor instead.
func (AIModel) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_chat_proto_rawDescGZIP(), []int{0}
}

type ConversationRole int32

const (
	ConversationRole_CONVERSATION_ROLE_UNSPECIFIED ConversationRole = 0
	ConversationRole_CONVERSATION_ROLE_USER        ConversationRole = 1
	ConversationRole_CONVERSATION_ROLE_ASSISTANT   ConversationRole = 2
	ConversationRole_CONVERSATION_ROLE_TOOL        ConversationRole = 3
)

// Enum value maps for ConversationRole.
var (
	ConversationRole_name = map[int32]string{
		0: "CONVERSATION_ROLE_UNSPECIFIED",
		1: "CONVERSATION_ROLE_USER",
		2: "CONVERSATION_ROLE_ASSISTANT",
		3: "CONVERSATION_ROLE_TOOL",
	}
	ConversationRole_value = map[string]int32{
		"CONVERSATION_ROLE_UNSPECIFIED": 0,
		"CONVERSATION_ROLE_USER":        1,
		"CONVERSATION_ROLE_ASSISTANT":   2,
		"CONVERSATION_ROLE_TOOL":        3,
	}
)

func (x ConversationRole) Enum() *ConversationRole {
	p := new(ConversationRole)
	*p = x
	return p
}

func (x ConversationRole) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationRole) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_chat_proto_enumTypes[1].Descriptor()
}

func (ConversationRole) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_chat_proto_enumTypes[1]
}

func (x ConversationRole) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationRole.Descriptor instead.
func (ConversationRole) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_chat_proto_rawDescGZIP(), []int{1}
}

type ConversationMessageType int32

const (
	ConversationMessageType_CONVERSATION_MESSAGE_TYPE_UNSPECIFIED ConversationMessageType = 0
	ConversationMessageType_CONVERSATION_MESSAGE_THINKING         ConversationMessageType = 1 // Thinking before the code, eg tool calls etc
	ConversationMessageType_CONVERSATION_MESSAGE_FINAL_THINKING   ConversationMessageType = 2 // Thinking for the code is generated
	ConversationMessageType_CONVERSATION_MESSAGE_MANUAL_EDITS     ConversationMessageType = 3
	ConversationMessageType_CONVERSATION_MESSAGE_TYPE_CHECKPOINT  ConversationMessageType = 4
)

// Enum value maps for ConversationMessageType.
var (
	ConversationMessageType_name = map[int32]string{
		0: "CONVERSATION_MESSAGE_TYPE_UNSPECIFIED",
		1: "CONVERSATION_MESSAGE_THINKING",
		2: "CONVERSATION_MESSAGE_FINAL_THINKING",
		3: "CONVERSATION_MESSAGE_MANUAL_EDITS",
		4: "CONVERSATION_MESSAGE_TYPE_CHECKPOINT",
	}
	ConversationMessageType_value = map[string]int32{
		"CONVERSATION_MESSAGE_TYPE_UNSPECIFIED": 0,
		"CONVERSATION_MESSAGE_THINKING":         1,
		"CONVERSATION_MESSAGE_FINAL_THINKING":   2,
		"CONVERSATION_MESSAGE_MANUAL_EDITS":     3,
		"CONVERSATION_MESSAGE_TYPE_CHECKPOINT":  4,
	}
)

func (x ConversationMessageType) Enum() *ConversationMessageType {
	p := new(ConversationMessageType)
	*p = x
	return p
}

func (x ConversationMessageType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ConversationMessageType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_chat_proto_enumTypes[2].Descriptor()
}

func (ConversationMessageType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_chat_proto_enumTypes[2]
}

func (x ConversationMessageType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ConversationMessageType.Descriptor instead.
func (ConversationMessageType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_chat_proto_rawDescGZIP(), []int{2}
}

type ConversationMessage struct {
	state    protoimpl.MessageState `protogen:"open.v1"`
	Role     ConversationRole       `protobuf:"varint,1,opt,name=role,proto3,enum=coasterai.core.v1.ConversationRole" json:"role,omitempty"`
	Message  string                 `protobuf:"bytes,2,opt,name=message,proto3" json:"message,omitempty"`
	AssetIds []string               `protobuf:"bytes,3,rep,name=assetIds,proto3" json:"assetIds,omitempty"`
	// * Model used for generation
	AiModel          *AIModel                `protobuf:"varint,4,opt,name=aiModel,proto3,enum=coasterai.core.v1.AIModel,oneof" json:"aiModel,omitempty"`
	CodeSnapshot     string                  `protobuf:"bytes,5,opt,name=codeSnapshot,proto3" json:"codeSnapshot,omitempty"`
	ReferenceIds     []string                `protobuf:"bytes,6,rep,name=referenceIds,proto3" json:"referenceIds,omitempty"`
	CreatedAt        *timestamppb.Timestamp  `protobuf:"bytes,7,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Type             ConversationMessageType `protobuf:"varint,8,opt,name=type,proto3,enum=coasterai.core.v1.ConversationMessageType" json:"type,omitempty"`
	DefaultCodeData  *structpb.Struct        `protobuf:"bytes,9,opt,name=defaultCodeData,proto3,oneof" json:"defaultCodeData,omitempty"`
	DurationInFrames *int32                  `protobuf:"varint,10,opt,name=durationInFrames,proto3,oneof" json:"durationInFrames,omitempty"`
	Id               string                  `protobuf:"bytes,11,opt,name=id,proto3" json:"id,omitempty"`
	ManualEdits      *structpb.Struct        `protobuf:"bytes,12,opt,name=manualEdits,proto3,oneof" json:"manualEdits,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *ConversationMessage) Reset() {
	*x = ConversationMessage{}
	mi := &file_coasterai_core_v1_chat_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ConversationMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ConversationMessage) ProtoMessage() {}

func (x *ConversationMessage) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_chat_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ConversationMessage.ProtoReflect.Descriptor instead.
func (*ConversationMessage) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_chat_proto_rawDescGZIP(), []int{0}
}

func (x *ConversationMessage) GetRole() ConversationRole {
	if x != nil {
		return x.Role
	}
	return ConversationRole_CONVERSATION_ROLE_UNSPECIFIED
}

func (x *ConversationMessage) GetMessage() string {
	if x != nil {
		return x.Message
	}
	return ""
}

func (x *ConversationMessage) GetAssetIds() []string {
	if x != nil {
		return x.AssetIds
	}
	return nil
}

func (x *ConversationMessage) GetAiModel() AIModel {
	if x != nil && x.AiModel != nil {
		return *x.AiModel
	}
	return AIModel_AI_MODEL_UNSPECIFIED
}

func (x *ConversationMessage) GetCodeSnapshot() string {
	if x != nil {
		return x.CodeSnapshot
	}
	return ""
}

func (x *ConversationMessage) GetReferenceIds() []string {
	if x != nil {
		return x.ReferenceIds
	}
	return nil
}

func (x *ConversationMessage) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *ConversationMessage) GetType() ConversationMessageType {
	if x != nil {
		return x.Type
	}
	return ConversationMessageType_CONVERSATION_MESSAGE_TYPE_UNSPECIFIED
}

func (x *ConversationMessage) GetDefaultCodeData() *structpb.Struct {
	if x != nil {
		return x.DefaultCodeData
	}
	return nil
}

func (x *ConversationMessage) GetDurationInFrames() int32 {
	if x != nil && x.DurationInFrames != nil {
		return *x.DurationInFrames
	}
	return 0
}

func (x *ConversationMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ConversationMessage) GetManualEdits() *structpb.Struct {
	if x != nil {
		return x.ManualEdits
	}
	return nil
}

var File_coasterai_core_v1_chat_proto protoreflect.FileDescriptor

const file_coasterai_core_v1_chat_proto_rawDesc = "" +
	"\n" +
	"\x1ccoasterai/core/v1/chat.proto\x12\x11coasterai.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1cgoogle/protobuf/struct.proto\"\x90\x05\n" +
	"\x13ConversationMessage\x127\n" +
	"\x04role\x18\x01 \x01(\x0e2#.coasterai.core.v1.ConversationRoleR\x04role\x12\x18\n" +
	"\amessage\x18\x02 \x01(\tR\amessage\x12\x1a\n" +
	"\bassetIds\x18\x03 \x03(\tR\bassetIds\x129\n" +
	"\aaiModel\x18\x04 \x01(\x0e2\x1a.coasterai.core.v1.AIModelH\x00R\aaiModel\x88\x01\x01\x12\"\n" +
	"\fcodeSnapshot\x18\x05 \x01(\tR\fcodeSnapshot\x12\"\n" +
	"\freferenceIds\x18\x06 \x03(\tR\freferenceIds\x129\n" +
	"\n" +
	"created_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12>\n" +
	"\x04type\x18\b \x01(\x0e2*.coasterai.core.v1.ConversationMessageTypeR\x04type\x12F\n" +
	"\x0fdefaultCodeData\x18\t \x01(\v2\x17.google.protobuf.StructH\x01R\x0fdefaultCodeData\x88\x01\x01\x12/\n" +
	"\x10durationInFrames\x18\n" +
	" \x01(\x05H\x02R\x10durationInFrames\x88\x01\x01\x12\x0e\n" +
	"\x02id\x18\v \x01(\tR\x02id\x12>\n" +
	"\vmanualEdits\x18\f \x01(\v2\x17.google.protobuf.StructH\x03R\vmanualEdits\x88\x01\x01B\n" +
	"\n" +
	"\b_aiModelB\x12\n" +
	"\x10_defaultCodeDataB\x13\n" +
	"\x11_durationInFramesB\x0e\n" +
	"\f_manualEdits*n\n" +
	"\aAIModel\x12\x18\n" +
	"\x14AI_MODEL_UNSPECIFIED\x10\x00\x12\x19\n" +
	"\x15AI_MODEL_GEMINI_3_PRO\x10\x01\x12\x14\n" +
	"\x10AI_MODEL_GPT_5_5\x10\x02\x12\x18\n" +
	"\x14AI_MODEL_GPT_5_5_SOL\x10\x03*\x8e\x01\n" +
	"\x10ConversationRole\x12!\n" +
	"\x1dCONVERSATION_ROLE_UNSPECIFIED\x10\x00\x12\x1a\n" +
	"\x16CONVERSATION_ROLE_USER\x10\x01\x12\x1f\n" +
	"\x1bCONVERSATION_ROLE_ASSISTANT\x10\x02\x12\x1a\n" +
	"\x16CONVERSATION_ROLE_TOOL\x10\x03*\xe1\x01\n" +
	"\x17ConversationMessageType\x12)\n" +
	"%CONVERSATION_MESSAGE_TYPE_UNSPECIFIED\x10\x00\x12!\n" +
	"\x1dCONVERSATION_MESSAGE_THINKING\x10\x01\x12'\n" +
	"#CONVERSATION_MESSAGE_FINAL_THINKING\x10\x02\x12%\n" +
	"!CONVERSATION_MESSAGE_MANUAL_EDITS\x10\x03\x12(\n" +
	"$CONVERSATION_MESSAGE_TYPE_CHECKPOINT\x10\x04B;Z9github.com/shank318/coasterai/pb/coasterai/core/v1;pbcoreb\x06proto3"

var (
	file_coasterai_core_v1_chat_proto_rawDescOnce sync.Once
	file_coasterai_core_v1_chat_proto_rawDescData []byte
)

func file_coasterai_core_v1_chat_proto_rawDescGZIP() []byte {
	file_coasterai_core_v1_chat_proto_rawDescOnce.Do(func() {
		file_coasterai_core_v1_chat_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_chat_proto_rawDesc), len(file_coasterai_core_v1_chat_proto_rawDesc)))
	})
	return file_coasterai_core_v1_chat_proto_rawDescData
}

var file_coasterai_core_v1_chat_proto_enumTypes = make([]protoimpl.EnumInfo, 3)
var file_coasterai_core_v1_chat_proto_msgTypes = make([]protoimpl.MessageInfo, 1)
var file_coasterai_core_v1_chat_proto_goTypes = []any{
	(AIModel)(0),                  // 0: coasterai.core.v1.AIModel
	(ConversationRole)(0),         // 1: coasterai.core.v1.ConversationRole
	(ConversationMessageType)(0),  // 2: coasterai.core.v1.ConversationMessageType
	(*ConversationMessage)(nil),   // 3: coasterai.core.v1.ConversationMessage
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
	(*structpb.Struct)(nil),       // 5: google.protobuf.Struct
}
var file_coasterai_core_v1_chat_proto_depIdxs = []int32{
	1, // 0: coasterai.core.v1.ConversationMessage.role:type_name -> coasterai.core.v1.ConversationRole
	0, // 1: coasterai.core.v1.ConversationMessage.aiModel:type_name -> coasterai.core.v1.AIModel
	4, // 2: coasterai.core.v1.ConversationMessage.created_at:type_name -> google.protobuf.Timestamp
	2, // 3: coasterai.core.v1.ConversationMessage.type:type_name -> coasterai.core.v1.ConversationMessageType
	5, // 4: coasterai.core.v1.ConversationMessage.defaultCodeData:type_name -> google.protobuf.Struct
	5, // 5: coasterai.core.v1.ConversationMessage.manualEdits:type_name -> google.protobuf.Struct
	6, // [6:6] is the sub-list for method output_type
	6, // [6:6] is the sub-list for method input_type
	6, // [6:6] is the sub-list for extension type_name
	6, // [6:6] is the sub-list for extension extendee
	0, // [0:6] is the sub-list for field type_name
}

func init() { file_coasterai_core_v1_chat_proto_init() }
func file_coasterai_core_v1_chat_proto_init() {
	if File_coasterai_core_v1_chat_proto != nil {
		return
	}
	file_coasterai_core_v1_chat_proto_msgTypes[0].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_chat_proto_rawDesc), len(file_coasterai_core_v1_chat_proto_rawDesc)),
			NumEnums:      3,
			NumMessages:   1,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coasterai_core_v1_chat_proto_goTypes,
		DependencyIndexes: file_coasterai_core_v1_chat_proto_depIdxs,
		EnumInfos:         file_coasterai_core_v1_chat_proto_enumTypes,
		MessageInfos:      file_coasterai_core_v1_chat_proto_msgTypes,
	}.Build()
	File_coasterai_core_v1_chat_proto = out.File
	file_coasterai_core_v1_chat_proto_goTypes = nil
	file_coasterai_core_v1_chat_proto_depIdxs = nil
}
