// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: coasterai/core/v1/slide.proto

package pbcore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SlideStatus int32

const (
	SlideStatus_SLIDE_STATUS_UNDEFINED SlideStatus = 0
	SlideStatus_SLIDE_STATUS_GENERATED SlideStatus = 1
	SlideStatus_SLIDE_STATUS_PENDING   SlideStatus = 2
)

// Enum value maps for SlideStatus.
var (
	SlideStatus_name = map[int32]string{
		0: "SLIDE_STATUS_UNDEFINED",
		1: "SLIDE_STATUS_GENERATED",
		2: "SLIDE_STATUS_PENDING",
	}
	SlideStatus_value = map[string]int32{
		"SLIDE_STATUS_UNDEFINED": 0,
		"SLIDE_STATUS_GENERATED": 1,
		"SLIDE_STATUS_PENDING":   2,
	}
)

func (x SlideStatus) Enum() *SlideStatus {
	p := new(SlideStatus)
	*p = x
	return p
}

func (x SlideStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlideStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[0].Descriptor()
}

func (SlideStatus) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[0]
}

func (x SlideStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlideStatus.Descriptor instead.
func (SlideStatus) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{0}
}

type SlideType int32

const (
	SlideType_SLIDE_TYPE_UNDEFINED SlideType = 0
	SlideType_SLIDE_TYPE_ANIMATION SlideType = 1
	SlideType_SLIDE_TYPE_MEDIA     SlideType = 5
)

// Enum value maps for SlideType.
var (
	SlideType_name = map[int32]string{
		0: "SLIDE_TYPE_UNDEFINED",
		1: "SLIDE_TYPE_ANIMATION",
		5: "SLIDE_TYPE_MEDIA",
	}
	SlideType_value = map[string]int32{
		"SLIDE_TYPE_UNDEFINED": 0,
		"SLIDE_TYPE_ANIMATION": 1,
		"SLIDE_TYPE_MEDIA":     5,
	}
)

func (x SlideType) Enum() *SlideType {
	p := new(SlideType)
	*p = x
	return p
}

func (x SlideType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (SlideType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[1].Descriptor()
}

func (SlideType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[1]
}

func (x SlideType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use SlideType.Descriptor instead.
func (SlideType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{1}
}

type MediaType int32

const (
	MediaType_MEDIA_TYPE_UNDEFINED MediaType = 0
	MediaType_MEDIA_TYPE_IMAGE     MediaType = 1
	MediaType_MEDIA_TYPE_VIDEO     MediaType = 2
	MediaType_MEDIA_TYPE_SVG       MediaType = 3
	MediaType_MEDIA_TYPE_CODE      MediaType = 4
)

// Enum value maps for MediaType.
var (
	MediaType_name = map[int32]string{
		0: "MEDIA_TYPE_UNDEFINED",
		1: "MEDIA_TYPE_IMAGE",
		2: "MEDIA_TYPE_VIDEO",
		3: "MEDIA_TYPE_SVG",
		4: "MEDIA_TYPE_CODE",
	}
	MediaType_value = map[string]int32{
		"MEDIA_TYPE_UNDEFINED": 0,
		"MEDIA_TYPE_IMAGE":     1,
		"MEDIA_TYPE_VIDEO":     2,
		"MEDIA_TYPE_SVG":       3,
		"MEDIA_TYPE_CODE":      4,
	}
)

func (x MediaType) Enum() *MediaType {
	p := new(MediaType)
	*p = x
	return p
}

func (x MediaType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (MediaType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[2].Descriptor()
}

func (MediaType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[2]
}

func (x MediaType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use MediaType.Descriptor instead.
func (MediaType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{2}
}

type StackAnimationMode int32

const (
	StackAnimationMode_STACK_ANIMATION_MODE_STACK  StackAnimationMode = 0
	StackAnimationMode_STACK_ANIMATION_MODE_REVEAL StackAnimationMode = 1
)

// Enum value maps for StackAnimationMode.
var (
	StackAnimationMode_name = map[int32]string{
		0: "STACK_ANIMATION_MODE_STACK",
		1: "STACK_ANIMATION_MODE_REVEAL",
	}
	StackAnimationMode_value = map[string]int32{
		"STACK_ANIMATION_MODE_STACK":  0,
		"STACK_ANIMATION_MODE_REVEAL": 1,
	}
)

func (x StackAnimationMode) Enum() *StackAnimationMode {
	p := new(StackAnimationMode)
	*p = x
	return p
}

func (x StackAnimationMode) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StackAnimationMode) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[3].Descriptor()
}

func (StackAnimationMode) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[3]
}

func (x StackAnimationMode) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StackAnimationMode.Descriptor instead.
func (StackAnimationMode) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{3}
}

type TransitionType int32

const (
	TransitionType_TRANSITION_NONE            TransitionType = 0
	TransitionType_TRANSITION_FADE            TransitionType = 1
	TransitionType_TRANSITION_SLIDE_LEFT      TransitionType = 2
	TransitionType_TRANSITION_SLIDE_RIGHT     TransitionType = 3
	TransitionType_TRANSITION_SLIDE_UP        TransitionType = 4
	TransitionType_TRANSITION_SLIDE_DOWN      TransitionType = 5
	TransitionType_TRANSITION_WIPE_LEFT       TransitionType = 6
	TransitionType_TRANSITION_WIPE_RIGHT      TransitionType = 7
	TransitionType_TRANSITION_WIPE_UP         TransitionType = 8
	TransitionType_TRANSITION_WIPE_DOWN       TransitionType = 9
	TransitionType_TRANSITION_FLIP_HORIZONTAL TransitionType = 10
	TransitionType_TRANSITION_FLIP_VERTICAL   TransitionType = 11
	TransitionType_TRANSITION_CLOCK_WIPE      TransitionType = 12
	TransitionType_TRANSITION_FLIP_LEFT       TransitionType = 13
	TransitionType_TRANSITION_FLIP_RIGHT      TransitionType = 14
	TransitionType_TRANSITION_FLIP_UP         TransitionType = 15
	TransitionType_TRANSITION_FLIP_DOWN       TransitionType = 16
	TransitionType_TRANSITION_IRIS            TransitionType = 17
)

// Enum value maps for TransitionType.
var (
	TransitionType_name = map[int32]string{
		0:  "TRANSITION_NONE",
		1:  "TRANSITION_FADE",
		2:  "TRANSITION_SLIDE_LEFT",
		3:  "TRANSITION_SLIDE_RIGHT",
		4:  "TRANSITION_SLIDE_UP",
		5:  "TRANSITION_SLIDE_DOWN",
		6:  "TRANSITION_WIPE_LEFT",
		7:  "TRANSITION_WIPE_RIGHT",
		8:  "TRANSITION_WIPE_UP",
		9:  "TRANSITION_WIPE_DOWN",
		10: "TRANSITION_FLIP_HORIZONTAL",
		11: "TRANSITION_FLIP_VERTICAL",
		12: "TRANSITION_CLOCK_WIPE",
		13: "TRANSITION_FLIP_LEFT",
		14: "TRANSITION_FLIP_RIGHT",
		15: "TRANSITION_FLIP_UP",
		16: "TRANSITION_FLIP_DOWN",
		17: "TRANSITION_IRIS",
	}
	TransitionType_value = map[string]int32{
		"TRANSITION_NONE":            0,
		"TRANSITION_FADE":            1,
		"TRANSITION_SLIDE_LEFT":      2,
		"TRANSITION_SLIDE_RIGHT":     3,
		"TRANSITION_SLIDE_UP":        4,
		"TRANSITION_SLIDE_DOWN":      5,
		"TRANSITION_WIPE_LEFT":       6,
		"TRANSITION_WIPE_RIGHT":      7,
		"TRANSITION_WIPE_UP":         8,
		"TRANSITION_WIPE_DOWN":       9,
		"TRANSITION_FLIP_HORIZONTAL": 10,
		"TRANSITION_FLIP_VERTICAL":   11,
		"TRANSITION_CLOCK_WIPE":      12,
		"TRANSITION_FLIP_LEFT":       13,
		"TRANSITION_FLIP_RIGHT":      14,
		"TRANSITION_FLIP_UP":         15,
		"TRANSITION_FLIP_DOWN":       16,
		"TRANSITION_IRIS":            17,
	}
)

func (x TransitionType) Enum() *TransitionType {
	p := new(TransitionType)
	*p = x
	return p
}

func (x TransitionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransitionType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[4].Descriptor()
}

func (TransitionType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[4]
}

func (x TransitionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransitionType.Descriptor instead.
func (TransitionType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{4}
}

type TransitionDirection int32

const (
	TransitionDirection_TRANSITION_DIRECTION_UNSPECIFIED TransitionDirection = 0
	TransitionDirection_TRANSITION_DIRECTION_FROM_LEFT   TransitionDirection = 1
	TransitionDirection_TRANSITION_DIRECTION_FROM_RIGHT  TransitionDirection = 2
	TransitionDirection_TRANSITION_DIRECTION_FROM_TOP    TransitionDirection = 3
	TransitionDirection_TRANSITION_DIRECTION_FROM_BOTTOM TransitionDirection = 4
)

// Enum value maps for TransitionDirection.
var (
	TransitionDirection_name = map[int32]string{
		0: "TRANSITION_DIRECTION_UNSPECIFIED",
		1: "TRANSITION_DIRECTION_FROM_LEFT",
		2: "TRANSITION_DIRECTION_FROM_RIGHT",
		3: "TRANSITION_DIRECTION_FROM_TOP",
		4: "TRANSITION_DIRECTION_FROM_BOTTOM",
	}
	TransitionDirection_value = map[string]int32{
		"TRANSITION_DIRECTION_UNSPECIFIED": 0,
		"TRANSITION_DIRECTION_FROM_LEFT":   1,
		"TRANSITION_DIRECTION_FROM_RIGHT":  2,
		"TRANSITION_DIRECTION_FROM_TOP":    3,
		"TRANSITION_DIRECTION_FROM_BOTTOM": 4,
	}
)

func (x TransitionDirection) Enum() *TransitionDirection {
	p := new(TransitionDirection)
	*p = x
	return p
}

func (x TransitionDirection) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (TransitionDirection) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[5].Descriptor()
}

func (TransitionDirection) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[5]
}

func (x TransitionDirection) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use TransitionDirection.Descriptor instead.
func (TransitionDirection) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{5}
}

type EffectType int32

const (
	EffectType_EFFECT_TYPE_UNDEFINED EffectType = 0
	EffectType_EFFECT_TYPE_CALLOUT   EffectType = 1
	EffectType_EFFECT_TYPE_SPOTLIGHT EffectType = 2
	EffectType_EFFECT_TYPE_ZOOM      EffectType = 3
)

// Enum value maps for EffectType.
var (
	EffectType_name = map[int32]string{
		0: "EFFECT_TYPE_UNDEFINED",
		1: "EFFECT_TYPE_CALLOUT",
		2: "EFFECT_TYPE_SPOTLIGHT",
		3: "EFFECT_TYPE_ZOOM",
	}
	EffectType_value = map[string]int32{
		"EFFECT_TYPE_UNDEFINED": 0,
		"EFFECT_TYPE_CALLOUT":   1,
		"EFFECT_TYPE_SPOTLIGHT": 2,
		"EFFECT_TYPE_ZOOM":      3,
	}
)

func (x EffectType) Enum() *EffectType {
	p := new(EffectType)
	*p = x
	return p
}

func (x EffectType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (EffectType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[6].Descriptor()
}

func (EffectType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[6]
}

func (x EffectType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use EffectType.Descriptor instead.
func (EffectType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{6}
}

type GradientType int32

const (
	GradientType_GRADIENT_TYPE_LINEAR GradientType = 0
	GradientType_GRADIENT_TYPE_RADIAL GradientType = 1
)

// Enum value maps for GradientType.
var (
	GradientType_name = map[int32]string{
		0: "GRADIENT_TYPE_LINEAR",
		1: "GRADIENT_TYPE_RADIAL",
	}
	GradientType_value = map[string]int32{
		"GRADIENT_TYPE_LINEAR": 0,
		"GRADIENT_TYPE_RADIAL": 1,
	}
)

func (x GradientType) Enum() *GradientType {
	p := new(GradientType)
	*p = x
	return p
}

func (x GradientType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (GradientType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_slide_proto_enumTypes[7].Descriptor()
}

func (GradientType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_slide_proto_enumTypes[7]
}

func (x GradientType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use GradientType.Descriptor instead.
func (GradientType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{7}
}

// Mostly be used for debugging what AI created
// Useful for rerunning the generation
// selectedTemplateDescription is basically the prompt generated to created the animation
// in case of existing template selectedTemplateDescription = template description
type AnimationSlidePlan struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Index                       int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BeatDescription             string                 `protobuf:"bytes,2,opt,name=beatDescription,proto3" json:"beatDescription,omitempty"`
	AnimationType               string                 `protobuf:"bytes,3,opt,name=animationType,proto3" json:"animationType,omitempty"`
	CategorySearcQquery         string                 `protobuf:"bytes,4,opt,name=categorySearcQquery,proto3" json:"categorySearcQquery,omitempty"`
	Duration                    int64                  `protobuf:"varint,5,opt,name=duration,proto3" json:"duration,omitempty"`
	Voiceover                   *string                `protobuf:"bytes,6,opt,name=voiceover,proto3,oneof" json:"voiceover,omitempty"`
	SelectedTemplateDescription *string                `protobuf:"bytes,7,opt,name=selectedTemplateDescription,proto3,oneof" json:"selectedTemplateDescription,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *AnimationSlidePlan) Reset() {
	*x = AnimationSlidePlan{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimationSlidePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimationSlidePlan) ProtoMessage() {}

func (x *AnimationSlidePlan) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimationSlidePlan.ProtoReflect.Descriptor instead.
func (*AnimationSlidePlan) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{0}
}

func (x *AnimationSlidePlan) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *AnimationSlidePlan) GetBeatDescription() string {
	if x != nil {
		return x.BeatDescription
	}
	return ""
}

func (x *AnimationSlidePlan) GetAnimationType() string {
	if x != nil {
		return x.AnimationType
	}
	return ""
}

func (x *AnimationSlidePlan) GetCategorySearcQquery() string {
	if x != nil {
		return x.CategorySearcQquery
	}
	return ""
}

func (x *AnimationSlidePlan) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *AnimationSlidePlan) GetVoiceover() string {
	if x != nil && x.Voiceover != nil {
		return *x.Voiceover
	}
	return ""
}

func (x *AnimationSlidePlan) GetSelectedTemplateDescription() string {
	if x != nil && x.SelectedTemplateDescription != nil {
		return *x.SelectedTemplateDescription
	}
	return ""
}

type MediaSlidePlan struct {
	state                       protoimpl.MessageState `protogen:"open.v1"`
	Index                       int64                  `protobuf:"varint,1,opt,name=index,proto3" json:"index,omitempty"`
	BeatDescription             string                 `protobuf:"bytes,2,opt,name=beatDescription,proto3" json:"beatDescription,omitempty"`
	Duration                    int64                  `protobuf:"varint,3,opt,name=duration,proto3" json:"duration,omitempty"`
	SelectedTemplateDescription *string                `protobuf:"bytes,4,opt,name=selectedTemplateDescription,proto3,oneof" json:"selectedTemplateDescription,omitempty"`
	unknownFields               protoimpl.UnknownFields
	sizeCache                   protoimpl.SizeCache
}

func (x *MediaSlidePlan) Reset() {
	*x = MediaSlidePlan{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSlidePlan) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSlidePlan) ProtoMessage() {}

func (x *MediaSlidePlan) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSlidePlan.ProtoReflect.Descriptor instead.
func (*MediaSlidePlan) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{1}
}

func (x *MediaSlidePlan) GetIndex() int64 {
	if x != nil {
		return x.Index
	}
	return 0
}

func (x *MediaSlidePlan) GetBeatDescription() string {
	if x != nil {
		return x.BeatDescription
	}
	return ""
}

func (x *MediaSlidePlan) GetDuration() int64 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *MediaSlidePlan) GetSelectedTemplateDescription() string {
	if x != nil && x.SelectedTemplateDescription != nil {
		return *x.SelectedTemplateDescription
	}
	return ""
}

type MediaSlideStyle struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	BorderRadius  float32                `protobuf:"fixed32,1,opt,name=borderRadius,proto3" json:"borderRadius,omitempty"`
	ObjectFit     *string                `protobuf:"bytes,2,opt,name=objectFit,proto3,oneof" json:"objectFit,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSlideStyle) Reset() {
	*x = MediaSlideStyle{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSlideStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSlideStyle) ProtoMessage() {}

func (x *MediaSlideStyle) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSlideStyle.ProtoReflect.Descriptor instead.
func (*MediaSlideStyle) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{2}
}

func (x *MediaSlideStyle) GetBorderRadius() float32 {
	if x != nil {
		return x.BorderRadius
	}
	return 0
}

func (x *MediaSlideStyle) GetObjectFit() string {
	if x != nil && x.ObjectFit != nil {
		return *x.ObjectFit
	}
	return ""
}

type MediaSlideContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Meta          *MetaData              `protobuf:"bytes,1,opt,name=meta,proto3" json:"meta,omitempty"`
	Src           string                 `protobuf:"bytes,2,opt,name=src,proto3" json:"src,omitempty"`
	Style         *MediaSlideStyle       `protobuf:"bytes,3,opt,name=style,proto3" json:"style,omitempty"`
	MediaType     MediaType              `protobuf:"varint,4,opt,name=mediaType,proto3,enum=coasterai.core.v1.MediaType" json:"mediaType,omitempty"`
	UploadedMedia *MediaAsset            `protobuf:"bytes,5,opt,name=uploadedMedia,proto3,oneof" json:"uploadedMedia,omitempty"`
	Plan          *MediaSlidePlan        `protobuf:"bytes,6,opt,name=plan,proto3" json:"plan,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaSlideContent) Reset() {
	*x = MediaSlideContent{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaSlideContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaSlideContent) ProtoMessage() {}

func (x *MediaSlideContent) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaSlideContent.ProtoReflect.Descriptor instead.
func (*MediaSlideContent) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{3}
}

func (x *MediaSlideContent) GetMeta() *MetaData {
	if x != nil {
		return x.Meta
	}
	return nil
}

func (x *MediaSlideContent) GetSrc() string {
	if x != nil {
		return x.Src
	}
	return ""
}

func (x *MediaSlideContent) GetStyle() *MediaSlideStyle {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *MediaSlideContent) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_MEDIA_TYPE_UNDEFINED
}

func (x *MediaSlideContent) GetUploadedMedia() *MediaAsset {
	if x != nil {
		return x.UploadedMedia
	}
	return nil
}

func (x *MediaSlideContent) GetPlan() *MediaSlidePlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

type MetaData struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	Scale         *float32               `protobuf:"fixed32,6,opt,name=scale,proto3,oneof" json:"scale,omitempty"`
	Rotation      *float32               `protobuf:"fixed32,7,opt,name=rotation,proto3,oneof" json:"rotation,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MetaData) Reset() {
	*x = MetaData{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MetaData) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MetaData) ProtoMessage() {}

func (x *MetaData) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MetaData.ProtoReflect.Descriptor instead.
func (*MetaData) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{4}
}

func (x *MetaData) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *MetaData) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *MetaData) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MetaData) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MetaData) GetScale() float32 {
	if x != nil && x.Scale != nil {
		return *x.Scale
	}
	return 0
}

func (x *MetaData) GetRotation() float32 {
	if x != nil && x.Rotation != nil {
		return *x.Rotation
	}
	return 0
}

type AnimationSlideContent struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CodeRegistry  *CodeRegistry          `protobuf:"bytes,1,opt,name=codeRegistry,proto3" json:"codeRegistry,omitempty"`
	Plan          *AnimationSlidePlan    `protobuf:"bytes,2,opt,name=plan,proto3" json:"plan,omitempty"`
	Edits         *structpb.Struct       `protobuf:"bytes,3,opt,name=edits,proto3" json:"edits,omitempty"`
	Registry      *structpb.Struct       `protobuf:"bytes,4,opt,name=registry,proto3" json:"registry,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AnimationSlideContent) Reset() {
	*x = AnimationSlideContent{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AnimationSlideContent) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AnimationSlideContent) ProtoMessage() {}

func (x *AnimationSlideContent) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AnimationSlideContent.ProtoReflect.Descriptor instead.
func (*AnimationSlideContent) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{5}
}

func (x *AnimationSlideContent) GetCodeRegistry() *CodeRegistry {
	if x != nil {
		return x.CodeRegistry
	}
	return nil
}

func (x *AnimationSlideContent) GetPlan() *AnimationSlidePlan {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *AnimationSlideContent) GetEdits() *structpb.Struct {
	if x != nil {
		return x.Edits
	}
	return nil
}

func (x *AnimationSlideContent) GetRegistry() *structpb.Struct {
	if x != nil {
		return x.Registry
	}
	return nil
}

type CodeRegistry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MUrl          string                 `protobuf:"bytes,1,opt,name=mUrl,proto3" json:"mUrl,omitempty"`
	TUrl          string                 `protobuf:"bytes,2,opt,name=tUrl,proto3" json:"tUrl,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CodeRegistry) Reset() {
	*x = CodeRegistry{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CodeRegistry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CodeRegistry) ProtoMessage() {}

func (x *CodeRegistry) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CodeRegistry.ProtoReflect.Descriptor instead.
func (*CodeRegistry) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{6}
}

func (x *CodeRegistry) GetMUrl() string {
	if x != nil {
		return x.MUrl
	}
	return ""
}

func (x *CodeRegistry) GetTUrl() string {
	if x != nil {
		return x.TUrl
	}
	return ""
}

type MediaAsset struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"`
	ThumbnailUrl  string                 `protobuf:"bytes,2,opt,name=thumbnailUrl,proto3" json:"thumbnailUrl,omitempty"`
	Width         float32                `protobuf:"fixed32,3,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,4,opt,name=height,proto3" json:"height,omitempty"`
	MimeType      string                 `protobuf:"bytes,5,opt,name=mimeType,proto3" json:"mimeType,omitempty"`
	Size          float32                `protobuf:"fixed32,6,opt,name=size,proto3" json:"size,omitempty"`
	FileId        string                 `protobuf:"bytes,7,opt,name=fileId,proto3" json:"fileId,omitempty"`
	FileName      string                 `protobuf:"bytes,8,opt,name=fileName,proto3" json:"fileName,omitempty"`
	Id            string                 `protobuf:"bytes,9,opt,name=id,proto3" json:"id,omitempty"`
	MediaType     MediaType              `protobuf:"varint,10,opt,name=mediaType,proto3,enum=coasterai.core.v1.MediaType" json:"mediaType,omitempty"`
	Duration      *float32               `protobuf:"fixed32,11,opt,name=duration,proto3,oneof" json:"duration,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MediaAsset) Reset() {
	*x = MediaAsset{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MediaAsset) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MediaAsset) ProtoMessage() {}

func (x *MediaAsset) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MediaAsset.ProtoReflect.Descriptor instead.
func (*MediaAsset) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{7}
}

func (x *MediaAsset) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

func (x *MediaAsset) GetThumbnailUrl() string {
	if x != nil {
		return x.ThumbnailUrl
	}
	return ""
}

func (x *MediaAsset) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *MediaAsset) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *MediaAsset) GetMimeType() string {
	if x != nil {
		return x.MimeType
	}
	return ""
}

func (x *MediaAsset) GetSize() float32 {
	if x != nil {
		return x.Size
	}
	return 0
}

func (x *MediaAsset) GetFileId() string {
	if x != nil {
		return x.FileId
	}
	return ""
}

func (x *MediaAsset) GetFileName() string {
	if x != nil {
		return x.FileName
	}
	return ""
}

func (x *MediaAsset) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *MediaAsset) GetMediaType() MediaType {
	if x != nil {
		return x.MediaType
	}
	return MediaType_MEDIA_TYPE_UNDEFINED
}

func (x *MediaAsset) GetDuration() float32 {
	if x != nil && x.Duration != nil {
		return *x.Duration
	}
	return 0
}

type SpotlightEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	BlurAmount    float32                `protobuf:"fixed32,6,opt,name=blurAmount,proto3" json:"blurAmount,omitempty"`
	BorderRadius  float32                `protobuf:"fixed32,7,opt,name=borderRadius,proto3" json:"borderRadius,omitempty"`
	StartTime     float32                `protobuf:"fixed32,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       float32                `protobuf:"fixed32,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SpotlightEffect) Reset() {
	*x = SpotlightEffect{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SpotlightEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SpotlightEffect) ProtoMessage() {}

func (x *SpotlightEffect) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SpotlightEffect.ProtoReflect.Descriptor instead.
func (*SpotlightEffect) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{8}
}

func (x *SpotlightEffect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *SpotlightEffect) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *SpotlightEffect) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *SpotlightEffect) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *SpotlightEffect) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *SpotlightEffect) GetBlurAmount() float32 {
	if x != nil {
		return x.BlurAmount
	}
	return 0
}

func (x *SpotlightEffect) GetBorderRadius() float32 {
	if x != nil {
		return x.BorderRadius
	}
	return 0
}

func (x *SpotlightEffect) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *SpotlightEffect) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type CalloutEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	Width         float32                `protobuf:"fixed32,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        float32                `protobuf:"fixed32,5,opt,name=height,proto3" json:"height,omitempty"`
	BlurAmount    float32                `protobuf:"fixed32,6,opt,name=blurAmount,proto3" json:"blurAmount,omitempty"`
	BorderRadius  float32                `protobuf:"fixed32,7,opt,name=borderRadius,proto3" json:"borderRadius,omitempty"`
	StartTime     float32                `protobuf:"fixed32,8,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       float32                `protobuf:"fixed32,9,opt,name=endTime,proto3" json:"endTime,omitempty"`
	Color         string                 `protobuf:"bytes,10,opt,name=color,proto3" json:"color,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CalloutEffect) Reset() {
	*x = CalloutEffect{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CalloutEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CalloutEffect) ProtoMessage() {}

func (x *CalloutEffect) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CalloutEffect.ProtoReflect.Descriptor instead.
func (*CalloutEffect) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{9}
}

func (x *CalloutEffect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *CalloutEffect) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *CalloutEffect) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *CalloutEffect) GetWidth() float32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *CalloutEffect) GetHeight() float32 {
	if x != nil {
		return x.Height
	}
	return 0
}

func (x *CalloutEffect) GetBlurAmount() float32 {
	if x != nil {
		return x.BlurAmount
	}
	return 0
}

func (x *CalloutEffect) GetBorderRadius() float32 {
	if x != nil {
		return x.BorderRadius
	}
	return 0
}

func (x *CalloutEffect) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *CalloutEffect) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

func (x *CalloutEffect) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

type ZoomEffect struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	X             float32                `protobuf:"fixed32,2,opt,name=x,proto3" json:"x,omitempty"`
	Y             float32                `protobuf:"fixed32,3,opt,name=y,proto3" json:"y,omitempty"`
	ZoomLevel     float32                `protobuf:"fixed32,4,opt,name=zoomLevel,proto3" json:"zoomLevel,omitempty"`
	StartTime     float32                `protobuf:"fixed32,5,opt,name=startTime,proto3" json:"startTime,omitempty"`
	EndTime       float32                `protobuf:"fixed32,6,opt,name=endTime,proto3" json:"endTime,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ZoomEffect) Reset() {
	*x = ZoomEffect{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ZoomEffect) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ZoomEffect) ProtoMessage() {}

func (x *ZoomEffect) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ZoomEffect.ProtoReflect.Descriptor instead.
func (*ZoomEffect) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{10}
}

func (x *ZoomEffect) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *ZoomEffect) GetX() float32 {
	if x != nil {
		return x.X
	}
	return 0
}

func (x *ZoomEffect) GetY() float32 {
	if x != nil {
		return x.Y
	}
	return 0
}

func (x *ZoomEffect) GetZoomLevel() float32 {
	if x != nil {
		return x.ZoomLevel
	}
	return 0
}

func (x *ZoomEffect) GetStartTime() float32 {
	if x != nil {
		return x.StartTime
	}
	return 0
}

func (x *ZoomEffect) GetEndTime() float32 {
	if x != nil {
		return x.EndTime
	}
	return 0
}

type Slide struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Type               SlideType              `protobuf:"varint,2,opt,name=type,proto3,enum=coasterai.core.v1.SlideType" json:"type,omitempty"`
	Transcript         string                 `protobuf:"bytes,3,opt,name=transcript,proto3" json:"transcript,omitempty"`
	Transition         TransitionType         `protobuf:"varint,5,opt,name=transition,proto3,enum=coasterai.core.v1.TransitionType" json:"transition,omitempty"`
	TransitionDuration *float32               `protobuf:"fixed32,6,opt,name=transitionDuration,proto3,oneof" json:"transitionDuration,omitempty"`
	BackgroundStyle    *BackgroundStyle       `protobuf:"bytes,7,opt,name=background_style,json=backgroundStyle,proto3,oneof" json:"background_style,omitempty"`
	Direction          *TransitionDirection   `protobuf:"varint,23,opt,name=direction,proto3,enum=coasterai.core.v1.TransitionDirection,oneof" json:"direction,omitempty"`
	DurationInFrames   float32                `protobuf:"fixed32,25,opt,name=durationInFrames,proto3" json:"durationInFrames,omitempty"`
	SettledFrame       float32                `protobuf:"fixed32,26,opt,name=settledFrame,proto3" json:"settledFrame,omitempty"`
	// Types that are valid to be assigned to Content:
	//
	//	*Slide_Media
	//	*Slide_Animation
	Content            isSlide_Content    `protobuf_oneof:"content"`
	VoiceoverGenerated *bool              `protobuf:"varint,15,opt,name=voiceoverGenerated,proto3,oneof" json:"voiceoverGenerated,omitempty"`
	IsNested           *bool              `protobuf:"varint,16,opt,name=isNested,proto3,oneof" json:"isNested,omitempty"`
	SubSlides          []*Slide           `protobuf:"bytes,17,rep,name=subSlides,proto3" json:"subSlides,omitempty"`
	Spotlights         []*SpotlightEffect `protobuf:"bytes,18,rep,name=spotlights,proto3" json:"spotlights,omitempty"`
	Callouts           []*CalloutEffect   `protobuf:"bytes,19,rep,name=callouts,proto3" json:"callouts,omitempty"`
	Zooms              []*ZoomEffect      `protobuf:"bytes,20,rep,name=zooms,proto3" json:"zooms,omitempty"`
	Plan               *structpb.Struct   `protobuf:"bytes,21,opt,name=plan,proto3" json:"plan,omitempty"`
	SlideStatus        SlideStatus        `protobuf:"varint,22,opt,name=slideStatus,proto3,enum=coasterai.core.v1.SlideStatus" json:"slideStatus,omitempty"`
	Index              int32              `protobuf:"varint,24,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Slide) Reset() {
	*x = Slide{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Slide) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Slide) ProtoMessage() {}

func (x *Slide) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Slide.ProtoReflect.Descriptor instead.
func (*Slide) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{11}
}

func (x *Slide) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Slide) GetType() SlideType {
	if x != nil {
		return x.Type
	}
	return SlideType_SLIDE_TYPE_UNDEFINED
}

func (x *Slide) GetTranscript() string {
	if x != nil {
		return x.Transcript
	}
	return ""
}

func (x *Slide) GetTransition() TransitionType {
	if x != nil {
		return x.Transition
	}
	return TransitionType_TRANSITION_NONE
}

func (x *Slide) GetTransitionDuration() float32 {
	if x != nil && x.TransitionDuration != nil {
		return *x.TransitionDuration
	}
	return 0
}

func (x *Slide) GetBackgroundStyle() *BackgroundStyle {
	if x != nil {
		return x.BackgroundStyle
	}
	return nil
}

func (x *Slide) GetDirection() TransitionDirection {
	if x != nil && x.Direction != nil {
		return *x.Direction
	}
	return TransitionDirection_TRANSITION_DIRECTION_UNSPECIFIED
}

func (x *Slide) GetDurationInFrames() float32 {
	if x != nil {
		return x.DurationInFrames
	}
	return 0
}

func (x *Slide) GetSettledFrame() float32 {
	if x != nil {
		return x.SettledFrame
	}
	return 0
}

func (x *Slide) GetContent() isSlide_Content {
	if x != nil {
		return x.Content
	}
	return nil
}

func (x *Slide) GetMedia() *MediaSlideContent {
	if x != nil {
		if x, ok := x.Content.(*Slide_Media); ok {
			return x.Media
		}
	}
	return nil
}

func (x *Slide) GetAnimation() *AnimationSlideContent {
	if x != nil {
		if x, ok := x.Content.(*Slide_Animation); ok {
			return x.Animation
		}
	}
	return nil
}

func (x *Slide) GetVoiceoverGenerated() bool {
	if x != nil && x.VoiceoverGenerated != nil {
		return *x.VoiceoverGenerated
	}
	return false
}

func (x *Slide) GetIsNested() bool {
	if x != nil && x.IsNested != nil {
		return *x.IsNested
	}
	return false
}

func (x *Slide) GetSubSlides() []*Slide {
	if x != nil {
		return x.SubSlides
	}
	return nil
}

func (x *Slide) GetSpotlights() []*SpotlightEffect {
	if x != nil {
		return x.Spotlights
	}
	return nil
}

func (x *Slide) GetCallouts() []*CalloutEffect {
	if x != nil {
		return x.Callouts
	}
	return nil
}

func (x *Slide) GetZooms() []*ZoomEffect {
	if x != nil {
		return x.Zooms
	}
	return nil
}

func (x *Slide) GetPlan() *structpb.Struct {
	if x != nil {
		return x.Plan
	}
	return nil
}

func (x *Slide) GetSlideStatus() SlideStatus {
	if x != nil {
		return x.SlideStatus
	}
	return SlideStatus_SLIDE_STATUS_UNDEFINED
}

func (x *Slide) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

type isSlide_Content interface {
	isSlide_Content()
}

type Slide_Media struct {
	Media *MediaSlideContent `protobuf:"bytes,8,opt,name=media,proto3,oneof"`
}

type Slide_Animation struct {
	Animation *AnimationSlideContent `protobuf:"bytes,9,opt,name=animation,proto3,oneof"`
}

func (*Slide_Media) isSlide_Content() {}

func (*Slide_Animation) isSlide_Content() {}

type BackgroundStyle struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Style:
	//
	//	*BackgroundStyle_Solid
	//	*BackgroundStyle_Gradient
	//	*BackgroundStyle_Image
	Style         isBackgroundStyle_Style `protobuf_oneof:"style"`
	ApplyAll      bool                    `protobuf:"varint,4,opt,name=apply_all,json=applyAll,proto3" json:"apply_all,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundStyle) Reset() {
	*x = BackgroundStyle{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundStyle) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundStyle) ProtoMessage() {}

func (x *BackgroundStyle) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundStyle.ProtoReflect.Descriptor instead.
func (*BackgroundStyle) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{12}
}

func (x *BackgroundStyle) GetStyle() isBackgroundStyle_Style {
	if x != nil {
		return x.Style
	}
	return nil
}

func (x *BackgroundStyle) GetSolid() *SolidColor {
	if x != nil {
		if x, ok := x.Style.(*BackgroundStyle_Solid); ok {
			return x.Solid
		}
	}
	return nil
}

func (x *BackgroundStyle) GetGradient() *Gradient {
	if x != nil {
		if x, ok := x.Style.(*BackgroundStyle_Gradient); ok {
			return x.Gradient
		}
	}
	return nil
}

func (x *BackgroundStyle) GetImage() *BackgroundImage {
	if x != nil {
		if x, ok := x.Style.(*BackgroundStyle_Image); ok {
			return x.Image
		}
	}
	return nil
}

func (x *BackgroundStyle) GetApplyAll() bool {
	if x != nil {
		return x.ApplyAll
	}
	return false
}

type isBackgroundStyle_Style interface {
	isBackgroundStyle_Style()
}

type BackgroundStyle_Solid struct {
	Solid *SolidColor `protobuf:"bytes,1,opt,name=solid,proto3,oneof"`
}

type BackgroundStyle_Gradient struct {
	Gradient *Gradient `protobuf:"bytes,2,opt,name=gradient,proto3,oneof"`
}

type BackgroundStyle_Image struct {
	Image *BackgroundImage `protobuf:"bytes,3,opt,name=image,proto3,oneof"`
}

func (*BackgroundStyle_Solid) isBackgroundStyle_Style() {}

func (*BackgroundStyle_Gradient) isBackgroundStyle_Style() {}

func (*BackgroundStyle_Image) isBackgroundStyle_Style() {}

type SolidColor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hex           string                 `protobuf:"bytes,1,opt,name=hex,proto3" json:"hex,omitempty"` // Example: "#0f172a"
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SolidColor) Reset() {
	*x = SolidColor{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SolidColor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SolidColor) ProtoMessage() {}

func (x *SolidColor) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SolidColor.ProtoReflect.Descriptor instead.
func (*SolidColor) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{13}
}

func (x *SolidColor) GetHex() string {
	if x != nil {
		return x.Hex
	}
	return ""
}

type BackgroundImage struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Url           string                 `protobuf:"bytes,1,opt,name=url,proto3" json:"url,omitempty"` // CDN or storage URL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BackgroundImage) Reset() {
	*x = BackgroundImage{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BackgroundImage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BackgroundImage) ProtoMessage() {}

func (x *BackgroundImage) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BackgroundImage.ProtoReflect.Descriptor instead.
func (*BackgroundImage) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{14}
}

func (x *BackgroundImage) GetUrl() string {
	if x != nil {
		return x.Url
	}
	return ""
}

type Gradient struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Type          GradientType           `protobuf:"varint,1,opt,name=type,proto3,enum=coasterai.core.v1.GradientType" json:"type,omitempty"`
	Angle         int32                  `protobuf:"varint,2,opt,name=angle,proto3" json:"angle,omitempty"` // 0–360 degrees
	Stops         []*GradientStop        `protobuf:"bytes,3,rep,name=stops,proto3" json:"stops,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Gradient) Reset() {
	*x = Gradient{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Gradient) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Gradient) ProtoMessage() {}

func (x *Gradient) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Gradient.ProtoReflect.Descriptor instead.
func (*Gradient) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{15}
}

func (x *Gradient) GetType() GradientType {
	if x != nil {
		return x.Type
	}
	return GradientType_GRADIENT_TYPE_LINEAR
}

func (x *Gradient) GetAngle() int32 {
	if x != nil {
		return x.Angle
	}
	return 0
}

func (x *Gradient) GetStops() []*GradientStop {
	if x != nil {
		return x.Stops
	}
	return nil
}

type GradientStop struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Color         string                 `protobuf:"bytes,1,opt,name=color,proto3" json:"color,omitempty"`        // "#ffffff"
	Position      int32                  `protobuf:"varint,2,opt,name=position,proto3" json:"position,omitempty"` // 0–100 (%)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GradientStop) Reset() {
	*x = GradientStop{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GradientStop) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GradientStop) ProtoMessage() {}

func (x *GradientStop) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GradientStop.ProtoReflect.Descriptor instead.
func (*GradientStop) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{16}
}

func (x *GradientStop) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *GradientStop) GetPosition() int32 {
	if x != nil {
		return x.Position
	}
	return 0
}

type Section struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Title              string                 `protobuf:"bytes,2,opt,name=title,proto3" json:"title,omitempty"`
	Color              string                 `protobuf:"bytes,3,opt,name=color,proto3" json:"color,omitempty"`
	Slides             []*Slide               `protobuf:"bytes,4,rep,name=slides,proto3" json:"slides,omitempty"`
	VoiceoverGenerated *bool                  `protobuf:"varint,5,opt,name=voiceoverGenerated,proto3,oneof" json:"voiceoverGenerated,omitempty"`
	Index              int32                  `protobuf:"varint,6,opt,name=index,proto3" json:"index,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *Section) Reset() {
	*x = Section{}
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Section) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Section) ProtoMessage() {}

func (x *Section) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_slide_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Section.ProtoReflect.Descriptor instead.
func (*Section) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_slide_proto_rawDescGZIP(), []int{17}
}

func (x *Section) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Section) GetTitle() string {
	if x != nil {
		return x.Title
	}
	return ""
}

func (x *Section) GetColor() string {
	if x != nil {
		return x.Color
	}
	return ""
}

func (x *Section) GetSlides() []*Slide {
	if x != nil {
		return x.Slides
	}
	return nil
}

func (x *Section) GetVoiceoverGenerated() bool {
	if x != nil && x.VoiceoverGenerated != nil {
		return *x.VoiceoverGenerated
	}
	return false
}

func (x *Section) GetIndex() int32 {
	if x != nil {
		return x.Index
	}
	return 0
}

var File_coasterai_core_v1_slide_proto protoreflect.FileDescriptor

const file_coasterai_core_v1_slide_proto_rawDesc = "" +
	"\n" +
	"\x1dcoasterai/core/v1/slide.proto\x12\x11coasterai.core.v1\x1a\x1cgoogle/protobuf/struct.proto\"\xe0\x02\n" +
	"\x12AnimationSlidePlan\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12(\n" +
	"\x0fbeatDescription\x18\x02 \x01(\tR\x0fbeatDescription\x12$\n" +
	"\ranimationType\x18\x03 \x01(\tR\ranimationType\x120\n" +
	"\x13categorySearcQquery\x18\x04 \x01(\tR\x13categorySearcQquery\x12\x1a\n" +
	"\bduration\x18\x05 \x01(\x03R\bduration\x12!\n" +
	"\tvoiceover\x18\x06 \x01(\tH\x00R\tvoiceover\x88\x01\x01\x12E\n" +
	"\x1bselectedTemplateDescription\x18\a \x01(\tH\x01R\x1bselectedTemplateDescription\x88\x01\x01B\f\n" +
	"\n" +
	"_voiceoverB\x1e\n" +
	"\x1c_selectedTemplateDescription\"\xd3\x01\n" +
	"\x0eMediaSlidePlan\x12\x14\n" +
	"\x05index\x18\x01 \x01(\x03R\x05index\x12(\n" +
	"\x0fbeatDescription\x18\x02 \x01(\tR\x0fbeatDescription\x12\x1a\n" +
	"\bduration\x18\x03 \x01(\x03R\bduration\x12E\n" +
	"\x1bselectedTemplateDescription\x18\x04 \x01(\tH\x00R\x1bselectedTemplateDescription\x88\x01\x01B\x1e\n" +
	"\x1c_selectedTemplateDescription\"f\n" +
	"\x0fMediaSlideStyle\x12\"\n" +
	"\fborderRadius\x18\x01 \x01(\x02R\fborderRadius\x12!\n" +
	"\tobjectFit\x18\x02 \x01(\tH\x00R\tobjectFit\x88\x01\x01B\f\n" +
	"\n" +
	"_objectFit\"\xdf\x02\n" +
	"\x11MediaSlideContent\x12/\n" +
	"\x04meta\x18\x01 \x01(\v2\x1b.coasterai.core.v1.MetaDataR\x04meta\x12\x10\n" +
	"\x03src\x18\x02 \x01(\tR\x03src\x128\n" +
	"\x05style\x18\x03 \x01(\v2\".coasterai.core.v1.MediaSlideStyleR\x05style\x12:\n" +
	"\tmediaType\x18\x04 \x01(\x0e2\x1c.coasterai.core.v1.MediaTypeR\tmediaType\x12H\n" +
	"\ruploadedMedia\x18\x05 \x01(\v2\x1d.coasterai.core.v1.MediaAssetH\x00R\ruploadedMedia\x88\x01\x01\x125\n" +
	"\x04plan\x18\x06 \x01(\v2!.coasterai.core.v1.MediaSlidePlanR\x04planB\x10\n" +
	"\x0e_uploadedMedia\"\xa7\x01\n" +
	"\bMetaData\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x02R\x06height\x12\x19\n" +
	"\x05scale\x18\x06 \x01(\x02H\x00R\x05scale\x88\x01\x01\x12\x1f\n" +
	"\brotation\x18\a \x01(\x02H\x01R\brotation\x88\x01\x01B\b\n" +
	"\x06_scaleB\v\n" +
	"\t_rotation\"\xfb\x01\n" +
	"\x15AnimationSlideContent\x12C\n" +
	"\fcodeRegistry\x18\x01 \x01(\v2\x1f.coasterai.core.v1.CodeRegistryR\fcodeRegistry\x129\n" +
	"\x04plan\x18\x02 \x01(\v2%.coasterai.core.v1.AnimationSlidePlanR\x04plan\x12-\n" +
	"\x05edits\x18\x03 \x01(\v2\x17.google.protobuf.StructR\x05edits\x123\n" +
	"\bregistry\x18\x04 \x01(\v2\x17.google.protobuf.StructR\bregistry\"6\n" +
	"\fCodeRegistry\x12\x12\n" +
	"\x04mUrl\x18\x01 \x01(\tR\x04mUrl\x12\x12\n" +
	"\x04tUrl\x18\x02 \x01(\tR\x04tUrl\"\xce\x02\n" +
	"\n" +
	"MediaAsset\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\x12\"\n" +
	"\fthumbnailUrl\x18\x02 \x01(\tR\fthumbnailUrl\x12\x14\n" +
	"\x05width\x18\x03 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x04 \x01(\x02R\x06height\x12\x1a\n" +
	"\bmimeType\x18\x05 \x01(\tR\bmimeType\x12\x12\n" +
	"\x04size\x18\x06 \x01(\x02R\x04size\x12\x16\n" +
	"\x06fileId\x18\a \x01(\tR\x06fileId\x12\x1a\n" +
	"\bfileName\x18\b \x01(\tR\bfileName\x12\x0e\n" +
	"\x02id\x18\t \x01(\tR\x02id\x12:\n" +
	"\tmediaType\x18\n" +
	" \x01(\x0e2\x1c.coasterai.core.v1.MediaTypeR\tmediaType\x12\x1f\n" +
	"\bduration\x18\v \x01(\x02H\x00R\bduration\x88\x01\x01B\v\n" +
	"\t_duration\"\xe7\x01\n" +
	"\x0fSpotlightEffect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x02R\x06height\x12\x1e\n" +
	"\n" +
	"blurAmount\x18\x06 \x01(\x02R\n" +
	"blurAmount\x12\"\n" +
	"\fborderRadius\x18\a \x01(\x02R\fborderRadius\x12\x1c\n" +
	"\tstartTime\x18\b \x01(\x02R\tstartTime\x12\x18\n" +
	"\aendTime\x18\t \x01(\x02R\aendTime\"\xfb\x01\n" +
	"\rCalloutEffect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x02R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x02R\x06height\x12\x1e\n" +
	"\n" +
	"blurAmount\x18\x06 \x01(\x02R\n" +
	"blurAmount\x12\"\n" +
	"\fborderRadius\x18\a \x01(\x02R\fborderRadius\x12\x1c\n" +
	"\tstartTime\x18\b \x01(\x02R\tstartTime\x12\x18\n" +
	"\aendTime\x18\t \x01(\x02R\aendTime\x12\x14\n" +
	"\x05color\x18\n" +
	" \x01(\tR\x05color\"\x8e\x01\n" +
	"\n" +
	"ZoomEffect\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\f\n" +
	"\x01x\x18\x02 \x01(\x02R\x01x\x12\f\n" +
	"\x01y\x18\x03 \x01(\x02R\x01y\x12\x1c\n" +
	"\tzoomLevel\x18\x04 \x01(\x02R\tzoomLevel\x12\x1c\n" +
	"\tstartTime\x18\x05 \x01(\x02R\tstartTime\x12\x18\n" +
	"\aendTime\x18\x06 \x01(\x02R\aendTime\"\x8b\t\n" +
	"\x05Slide\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x120\n" +
	"\x04type\x18\x02 \x01(\x0e2\x1c.coasterai.core.v1.SlideTypeR\x04type\x12\x1e\n" +
	"\n" +
	"transcript\x18\x03 \x01(\tR\n" +
	"transcript\x12A\n" +
	"\n" +
	"transition\x18\x05 \x01(\x0e2!.coasterai.core.v1.TransitionTypeR\n" +
	"transition\x123\n" +
	"\x12transitionDuration\x18\x06 \x01(\x02H\x01R\x12transitionDuration\x88\x01\x01\x12R\n" +
	"\x10background_style\x18\a \x01(\v2\".coasterai.core.v1.BackgroundStyleH\x02R\x0fbackgroundStyle\x88\x01\x01\x12I\n" +
	"\tdirection\x18\x17 \x01(\x0e2&.coasterai.core.v1.TransitionDirectionH\x03R\tdirection\x88\x01\x01\x12*\n" +
	"\x10durationInFrames\x18\x19 \x01(\x02R\x10durationInFrames\x12\"\n" +
	"\fsettledFrame\x18\x1a \x01(\x02R\fsettledFrame\x12<\n" +
	"\x05media\x18\b \x01(\v2$.coasterai.core.v1.MediaSlideContentH\x00R\x05media\x12H\n" +
	"\tanimation\x18\t \x01(\v2(.coasterai.core.v1.AnimationSlideContentH\x00R\tanimation\x123\n" +
	"\x12voiceoverGenerated\x18\x0f \x01(\bH\x04R\x12voiceoverGenerated\x88\x01\x01\x12\x1f\n" +
	"\bisNested\x18\x10 \x01(\bH\x05R\bisNested\x88\x01\x01\x126\n" +
	"\tsubSlides\x18\x11 \x03(\v2\x18.coasterai.core.v1.SlideR\tsubSlides\x12B\n" +
	"\n" +
	"spotlights\x18\x12 \x03(\v2\".coasterai.core.v1.SpotlightEffectR\n" +
	"spotlights\x12<\n" +
	"\bcallouts\x18\x13 \x03(\v2 .coasterai.core.v1.CalloutEffectR\bcallouts\x123\n" +
	"\x05zooms\x18\x14 \x03(\v2\x1d.coasterai.core.v1.ZoomEffectR\x05zooms\x12+\n" +
	"\x04plan\x18\x15 \x01(\v2\x17.google.protobuf.StructR\x04plan\x12@\n" +
	"\vslideStatus\x18\x16 \x01(\x0e2\x1e.coasterai.core.v1.SlideStatusR\vslideStatus\x12\x14\n" +
	"\x05index\x18\x18 \x01(\x05R\x05indexB\t\n" +
	"\acontentB\x15\n" +
	"\x13_transitionDurationB\x13\n" +
	"\x11_background_styleB\f\n" +
	"\n" +
	"_directionB\x15\n" +
	"\x13_voiceoverGeneratedB\v\n" +
	"\t_isNested\"\xe5\x01\n" +
	"\x0fBackgroundStyle\x125\n" +
	"\x05solid\x18\x01 \x01(\v2\x1d.coasterai.core.v1.SolidColorH\x00R\x05solid\x129\n" +
	"\bgradient\x18\x02 \x01(\v2\x1b.coasterai.core.v1.GradientH\x00R\bgradient\x12:\n" +
	"\x05image\x18\x03 \x01(\v2\".coasterai.core.v1.BackgroundImageH\x00R\x05image\x12\x1b\n" +
	"\tapply_all\x18\x04 \x01(\bR\bapplyAllB\a\n" +
	"\x05style\"\x1e\n" +
	"\n" +
	"SolidColor\x12\x10\n" +
	"\x03hex\x18\x01 \x01(\tR\x03hex\"#\n" +
	"\x0fBackgroundImage\x12\x10\n" +
	"\x03url\x18\x01 \x01(\tR\x03url\"\x8c\x01\n" +
	"\bGradient\x123\n" +
	"\x04type\x18\x01 \x01(\x0e2\x1f.coasterai.core.v1.GradientTypeR\x04type\x12\x14\n" +
	"\x05angle\x18\x02 \x01(\x05R\x05angle\x125\n" +
	"\x05stops\x18\x03 \x03(\v2\x1f.coasterai.core.v1.GradientStopR\x05stops\"@\n" +
	"\fGradientStop\x12\x14\n" +
	"\x05color\x18\x01 \x01(\tR\x05color\x12\x1a\n" +
	"\bposition\x18\x02 \x01(\x05R\bposition\"\xd9\x01\n" +
	"\aSection\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x14\n" +
	"\x05title\x18\x02 \x01(\tR\x05title\x12\x14\n" +
	"\x05color\x18\x03 \x01(\tR\x05color\x120\n" +
	"\x06slides\x18\x04 \x03(\v2\x18.coasterai.core.v1.SlideR\x06slides\x123\n" +
	"\x12voiceoverGenerated\x18\x05 \x01(\bH\x00R\x12voiceoverGenerated\x88\x01\x01\x12\x14\n" +
	"\x05index\x18\x06 \x01(\x05R\x05indexB\x15\n" +
	"\x13_voiceoverGenerated*_\n" +
	"\vSlideStatus\x12\x1a\n" +
	"\x16SLIDE_STATUS_UNDEFINED\x10\x00\x12\x1a\n" +
	"\x16SLIDE_STATUS_GENERATED\x10\x01\x12\x18\n" +
	"\x14SLIDE_STATUS_PENDING\x10\x02*U\n" +
	"\tSlideType\x12\x18\n" +
	"\x14SLIDE_TYPE_UNDEFINED\x10\x00\x12\x18\n" +
	"\x14SLIDE_TYPE_ANIMATION\x10\x01\x12\x14\n" +
	"\x10SLIDE_TYPE_MEDIA\x10\x05*z\n" +
	"\tMediaType\x12\x18\n" +
	"\x14MEDIA_TYPE_UNDEFINED\x10\x00\x12\x14\n" +
	"\x10MEDIA_TYPE_IMAGE\x10\x01\x12\x14\n" +
	"\x10MEDIA_TYPE_VIDEO\x10\x02\x12\x12\n" +
	"\x0eMEDIA_TYPE_SVG\x10\x03\x12\x13\n" +
	"\x0fMEDIA_TYPE_CODE\x10\x04*U\n" +
	"\x12StackAnimationMode\x12\x1e\n" +
	"\x1aSTACK_ANIMATION_MODE_STACK\x10\x00\x12\x1f\n" +
	"\x1bSTACK_ANIMATION_MODE_REVEAL\x10\x01*\xe1\x03\n" +
	"\x0eTransitionType\x12\x13\n" +
	"\x0fTRANSITION_NONE\x10\x00\x12\x13\n" +
	"\x0fTRANSITION_FADE\x10\x01\x12\x19\n" +
	"\x15TRANSITION_SLIDE_LEFT\x10\x02\x12\x1a\n" +
	"\x16TRANSITION_SLIDE_RIGHT\x10\x03\x12\x17\n" +
	"\x13TRANSITION_SLIDE_UP\x10\x04\x12\x19\n" +
	"\x15TRANSITION_SLIDE_DOWN\x10\x05\x12\x18\n" +
	"\x14TRANSITION_WIPE_LEFT\x10\x06\x12\x19\n" +
	"\x15TRANSITION_WIPE_RIGHT\x10\a\x12\x16\n" +
	"\x12TRANSITION_WIPE_UP\x10\b\x12\x18\n" +
	"\x14TRANSITION_WIPE_DOWN\x10\t\x12\x1e\n" +
	"\x1aTRANSITION_FLIP_HORIZONTAL\x10\n" +
	"\x12\x1c\n" +
	"\x18TRANSITION_FLIP_VERTICAL\x10\v\x12\x19\n" +
	"\x15TRANSITION_CLOCK_WIPE\x10\f\x12\x18\n" +
	"\x14TRANSITION_FLIP_LEFT\x10\r\x12\x19\n" +
	"\x15TRANSITION_FLIP_RIGHT\x10\x0e\x12\x16\n" +
	"\x12TRANSITION_FLIP_UP\x10\x0f\x12\x18\n" +
	"\x14TRANSITION_FLIP_DOWN\x10\x10\x12\x13\n" +
	"\x0fTRANSITION_IRIS\x10\x11*\xcd\x01\n" +
	"\x13TransitionDirection\x12$\n" +
	" TRANSITION_DIRECTION_UNSPECIFIED\x10\x00\x12\"\n" +
	"\x1eTRANSITION_DIRECTION_FROM_LEFT\x10\x01\x12#\n" +
	"\x1fTRANSITION_DIRECTION_FROM_RIGHT\x10\x02\x12!\n" +
	"\x1dTRANSITION_DIRECTION_FROM_TOP\x10\x03\x12$\n" +
	" TRANSITION_DIRECTION_FROM_BOTTOM\x10\x04*q\n" +
	"\n" +
	"EffectType\x12\x19\n" +
	"\x15EFFECT_TYPE_UNDEFINED\x10\x00\x12\x17\n" +
	"\x13EFFECT_TYPE_CALLOUT\x10\x01\x12\x19\n" +
	"\x15EFFECT_TYPE_SPOTLIGHT\x10\x02\x12\x14\n" +
	"\x10EFFECT_TYPE_ZOOM\x10\x03*B\n" +
	"\fGradientType\x12\x18\n" +
	"\x14GRADIENT_TYPE_LINEAR\x10\x00\x12\x18\n" +
	"\x14GRADIENT_TYPE_RADIAL\x10\x01B;Z9github.com/shank318/coasterai/pb/coasterai/core/v1;pbcoreb\x06proto3"

var (
	file_coasterai_core_v1_slide_proto_rawDescOnce sync.Once
	file_coasterai_core_v1_slide_proto_rawDescData []byte
)

func file_coasterai_core_v1_slide_proto_rawDescGZIP() []byte {
	file_coasterai_core_v1_slide_proto_rawDescOnce.Do(func() {
		file_coasterai_core_v1_slide_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_slide_proto_rawDesc), len(file_coasterai_core_v1_slide_proto_rawDesc)))
	})
	return file_coasterai_core_v1_slide_proto_rawDescData
}

var file_coasterai_core_v1_slide_proto_enumTypes = make([]protoimpl.EnumInfo, 8)
var file_coasterai_core_v1_slide_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_coasterai_core_v1_slide_proto_goTypes = []any{
	(SlideStatus)(0),              // 0: coasterai.core.v1.SlideStatus
	(SlideType)(0),                // 1: coasterai.core.v1.SlideType
	(MediaType)(0),                // 2: coasterai.core.v1.MediaType
	(StackAnimationMode)(0),       // 3: coasterai.core.v1.StackAnimationMode
	(TransitionType)(0),           // 4: coasterai.core.v1.TransitionType
	(TransitionDirection)(0),      // 5: coasterai.core.v1.TransitionDirection
	(EffectType)(0),               // 6: coasterai.core.v1.EffectType
	(GradientType)(0),             // 7: coasterai.core.v1.GradientType
	(*AnimationSlidePlan)(nil),    // 8: coasterai.core.v1.AnimationSlidePlan
	(*MediaSlidePlan)(nil),        // 9: coasterai.core.v1.MediaSlidePlan
	(*MediaSlideStyle)(nil),       // 10: coasterai.core.v1.MediaSlideStyle
	(*MediaSlideContent)(nil),     // 11: coasterai.core.v1.MediaSlideContent
	(*MetaData)(nil),              // 12: coasterai.core.v1.MetaData
	(*AnimationSlideContent)(nil), // 13: coasterai.core.v1.AnimationSlideContent
	(*CodeRegistry)(nil),          // 14: coasterai.core.v1.CodeRegistry
	(*MediaAsset)(nil),            // 15: coasterai.core.v1.MediaAsset
	(*SpotlightEffect)(nil),       // 16: coasterai.core.v1.SpotlightEffect
	(*CalloutEffect)(nil),         // 17: coasterai.core.v1.CalloutEffect
	(*ZoomEffect)(nil),            // 18: coasterai.core.v1.ZoomEffect
	(*Slide)(nil),                 // 19: coasterai.core.v1.Slide
	(*BackgroundStyle)(nil),       // 20: coasterai.core.v1.BackgroundStyle
	(*SolidColor)(nil),            // 21: coasterai.core.v1.SolidColor
	(*BackgroundImage)(nil),       // 22: coasterai.core.v1.BackgroundImage
	(*Gradient)(nil),              // 23: coasterai.core.v1.Gradient
	(*GradientStop)(nil),          // 24: coasterai.core.v1.GradientStop
	(*Section)(nil),               // 25: coasterai.core.v1.Section
	(*structpb.Struct)(nil),       // 26: google.protobuf.Struct
}
var file_coasterai_core_v1_slide_proto_depIdxs = []int32{
	12, // 0: coasterai.core.v1.MediaSlideContent.meta:type_name -> coasterai.core.v1.MetaData
	10, // 1: coasterai.core.v1.MediaSlideContent.style:type_name -> coasterai.core.v1.MediaSlideStyle
	2,  // 2: coasterai.core.v1.MediaSlideContent.mediaType:type_name -> coasterai.core.v1.MediaType
	15, // 3: coasterai.core.v1.MediaSlideContent.uploadedMedia:type_name -> coasterai.core.v1.MediaAsset
	9,  // 4: coasterai.core.v1.MediaSlideContent.plan:type_name -> coasterai.core.v1.MediaSlidePlan
	14, // 5: coasterai.core.v1.AnimationSlideContent.codeRegistry:type_name -> coasterai.core.v1.CodeRegistry
	8,  // 6: coasterai.core.v1.AnimationSlideContent.plan:type_name -> coasterai.core.v1.AnimationSlidePlan
	26, // 7: coasterai.core.v1.AnimationSlideContent.edits:type_name -> google.protobuf.Struct
	26, // 8: coasterai.core.v1.AnimationSlideContent.registry:type_name -> google.protobuf.Struct
	2,  // 9: coasterai.core.v1.MediaAsset.mediaType:type_name -> coasterai.core.v1.MediaType
	1,  // 10: coasterai.core.v1.Slide.type:type_name -> coasterai.core.v1.SlideType
	4,  // 11: coasterai.core.v1.Slide.transition:type_name -> coasterai.core.v1.TransitionType
	20, // 12: coasterai.core.v1.Slide.background_style:type_name -> coasterai.core.v1.BackgroundStyle
	5,  // 13: coasterai.core.v1.Slide.direction:type_name -> coasterai.core.v1.TransitionDirection
	11, // 14: coasterai.core.v1.Slide.media:type_name -> coasterai.core.v1.MediaSlideContent
	13, // 15: coasterai.core.v1.Slide.animation:type_name -> coasterai.core.v1.AnimationSlideContent
	19, // 16: coasterai.core.v1.Slide.subSlides:type_name -> coasterai.core.v1.Slide
	16, // 17: coasterai.core.v1.Slide.spotlights:type_name -> coasterai.core.v1.SpotlightEffect
	17, // 18: coasterai.core.v1.Slide.callouts:type_name -> coasterai.core.v1.CalloutEffect
	18, // 19: coasterai.core.v1.Slide.zooms:type_name -> coasterai.core.v1.ZoomEffect
	26, // 20: coasterai.core.v1.Slide.plan:type_name -> google.protobuf.Struct
	0,  // 21: coasterai.core.v1.Slide.slideStatus:type_name -> coasterai.core.v1.SlideStatus
	21, // 22: coasterai.core.v1.BackgroundStyle.solid:type_name -> coasterai.core.v1.SolidColor
	23, // 23: coasterai.core.v1.BackgroundStyle.gradient:type_name -> coasterai.core.v1.Gradient
	22, // 24: coasterai.core.v1.BackgroundStyle.image:type_name -> coasterai.core.v1.BackgroundImage
	7,  // 25: coasterai.core.v1.Gradient.type:type_name -> coasterai.core.v1.GradientType
	24, // 26: coasterai.core.v1.Gradient.stops:type_name -> coasterai.core.v1.GradientStop
	19, // 27: coasterai.core.v1.Section.slides:type_name -> coasterai.core.v1.Slide
	28, // [28:28] is the sub-list for method output_type
	28, // [28:28] is the sub-list for method input_type
	28, // [28:28] is the sub-list for extension type_name
	28, // [28:28] is the sub-list for extension extendee
	0,  // [0:28] is the sub-list for field type_name
}

func init() { file_coasterai_core_v1_slide_proto_init() }
func file_coasterai_core_v1_slide_proto_init() {
	if File_coasterai_core_v1_slide_proto != nil {
		return
	}
	file_coasterai_core_v1_slide_proto_msgTypes[0].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[1].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[2].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[3].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[4].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[7].OneofWrappers = []any{}
	file_coasterai_core_v1_slide_proto_msgTypes[11].OneofWrappers = []any{
		(*Slide_Media)(nil),
		(*Slide_Animation)(nil),
	}
	file_coasterai_core_v1_slide_proto_msgTypes[12].OneofWrappers = []any{
		(*BackgroundStyle_Solid)(nil),
		(*BackgroundStyle_Gradient)(nil),
		(*BackgroundStyle_Image)(nil),
	}
	file_coasterai_core_v1_slide_proto_msgTypes[17].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_slide_proto_rawDesc), len(file_coasterai_core_v1_slide_proto_rawDesc)),
			NumEnums:      8,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coasterai_core_v1_slide_proto_goTypes,
		DependencyIndexes: file_coasterai_core_v1_slide_proto_depIdxs,
		EnumInfos:         file_coasterai_core_v1_slide_proto_enumTypes,
		MessageInfos:      file_coasterai_core_v1_slide_proto_msgTypes,
	}.Build()
	File_coasterai_core_v1_slide_proto = out.File
	file_coasterai_core_v1_slide_proto_goTypes = nil
	file_coasterai_core_v1_slide_proto_depIdxs = nil
}
