// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: coasterai/core/v1/video.proto

package pbcore

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VideoStatus int32

const (
	VideoStatus_VIDEO_STATUS_UNSPECIFIED        VideoStatus = 0
	VideoStatus_VIDEO_STATUS_PROCESSING         VideoStatus = 1
	VideoStatus_VIDEO_STATUS_COMPLETED          VideoStatus = 2
	VideoStatus_VIDEO_STATUS_FAILED             VideoStatus = 3
	VideoStatus_VIDEO_STATUS_PLANNING           VideoStatus = 4
	VideoStatus_VIDEO_STATUS_PLANNING_CANCELLED VideoStatus = 5
	VideoStatus_VIDEO_STATUS_USER_CANCELLED     VideoStatus = 6
)

// Enum value maps for VideoStatus.
var (
	VideoStatus_name = map[int32]string{
		0: "VIDEO_STATUS_UNSPECIFIED",
		1: "VIDEO_STATUS_PROCESSING",
		2: "VIDEO_STATUS_COMPLETED",
		3: "VIDEO_STATUS_FAILED",
		4: "VIDEO_STATUS_PLANNING",
		5: "VIDEO_STATUS_PLANNING_CANCELLED",
		6: "VIDEO_STATUS_USER_CANCELLED",
	}
	VideoStatus_value = map[string]int32{
		"VIDEO_STATUS_UNSPECIFIED":        0,
		"VIDEO_STATUS_PROCESSING":         1,
		"VIDEO_STATUS_COMPLETED":          2,
		"VIDEO_STATUS_FAILED":             3,
		"VIDEO_STATUS_PLANNING":           4,
		"VIDEO_STATUS_PLANNING_CANCELLED": 5,
		"VIDEO_STATUS_USER_CANCELLED":     6,
	}
)

func (x VideoStatus) Enum() *VideoStatus {
	p := new(VideoStatus)
	*p = x
	return p
}

func (x VideoStatus) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoStatus) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_video_proto_enumTypes[0].Descriptor()
}

func (VideoStatus) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_video_proto_enumTypes[0]
}

func (x VideoStatus) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoStatus.Descriptor instead.
func (VideoStatus) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{0}
}

type VideoLanguage int32

const (
	VideoLanguage_VIDE_LANGUAGE_EN VideoLanguage = 0
)

// Enum value maps for VideoLanguage.
var (
	VideoLanguage_name = map[int32]string{
		0: "VIDE_LANGUAGE_EN",
	}
	VideoLanguage_value = map[string]int32{
		"VIDE_LANGUAGE_EN": 0,
	}
)

func (x VideoLanguage) Enum() *VideoLanguage {
	p := new(VideoLanguage)
	*p = x
	return p
}

func (x VideoLanguage) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (VideoLanguage) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_video_proto_enumTypes[1].Descriptor()
}

func (VideoLanguage) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_video_proto_enumTypes[1]
}

func (x VideoLanguage) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use VideoLanguage.Descriptor instead.
func (VideoLanguage) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{1}
}

type ResolutionType int32

const (
	ResolutionType_RESOLUTION_TYPE_UNSPECIFIED ResolutionType = 0
	ResolutionType_RESOLUTION_16_9             ResolutionType = 1
	ResolutionType_RESOLUTION_4_3              ResolutionType = 2
	ResolutionType_RESOLUTION_9_16             ResolutionType = 3
	ResolutionType_RESOLUTION_1_1              ResolutionType = 4
)

// Enum value maps for ResolutionType.
var (
	ResolutionType_name = map[int32]string{
		0: "RESOLUTION_TYPE_UNSPECIFIED",
		1: "RESOLUTION_16_9",
		2: "RESOLUTION_4_3",
		3: "RESOLUTION_9_16",
		4: "RESOLUTION_1_1",
	}
	ResolutionType_value = map[string]int32{
		"RESOLUTION_TYPE_UNSPECIFIED": 0,
		"RESOLUTION_16_9":             1,
		"RESOLUTION_4_3":              2,
		"RESOLUTION_9_16":             3,
		"RESOLUTION_1_1":              4,
	}
)

func (x ResolutionType) Enum() *ResolutionType {
	p := new(ResolutionType)
	*p = x
	return p
}

func (x ResolutionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (ResolutionType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_video_proto_enumTypes[2].Descriptor()
}

func (ResolutionType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_video_proto_enumTypes[2]
}

func (x ResolutionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use ResolutionType.Descriptor instead.
func (ResolutionType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{2}
}

type StyleType int32

const (
	StyleType_STYLE_TYPE_UNDEFINED StyleType = 0
	StyleType_STYLE_TYPE_SIMPLE    StyleType = 1
)

// Enum value maps for StyleType.
var (
	StyleType_name = map[int32]string{
		0: "STYLE_TYPE_UNDEFINED",
		1: "STYLE_TYPE_SIMPLE",
	}
	StyleType_value = map[string]int32{
		"STYLE_TYPE_UNDEFINED": 0,
		"STYLE_TYPE_SIMPLE":    1,
	}
)

func (x StyleType) Enum() *StyleType {
	p := new(StyleType)
	*p = x
	return p
}

func (x StyleType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (StyleType) Descriptor() protoreflect.EnumDescriptor {
	return file_coasterai_core_v1_video_proto_enumTypes[3].Descriptor()
}

func (StyleType) Type() protoreflect.EnumType {
	return &file_coasterai_core_v1_video_proto_enumTypes[3]
}

func (x StyleType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use StyleType.Descriptor instead.
func (StyleType) EnumDescriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{3}
}

type GeneratedVideoBranding struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	BrandGuideLines string                 `protobuf:"bytes,1,opt,name=brandGuideLines,proto3" json:"brandGuideLines,omitempty"` // just for reference purpose, not used for logic
	Colors          *GeneratedBrandColors  `protobuf:"bytes,2,opt,name=colors,proto3" json:"colors,omitempty"`
	BrandLibraryID  *string                `protobuf:"bytes,3,opt,name=brandLibraryID,proto3,oneof" json:"brandLibraryID,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GeneratedVideoBranding) Reset() {
	*x = GeneratedVideoBranding{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedVideoBranding) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedVideoBranding) ProtoMessage() {}

func (x *GeneratedVideoBranding) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedVideoBranding.ProtoReflect.Descriptor instead.
func (*GeneratedVideoBranding) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{0}
}

func (x *GeneratedVideoBranding) GetBrandGuideLines() string {
	if x != nil {
		return x.BrandGuideLines
	}
	return ""
}

func (x *GeneratedVideoBranding) GetColors() *GeneratedBrandColors {
	if x != nil {
		return x.Colors
	}
	return nil
}

func (x *GeneratedVideoBranding) GetBrandLibraryID() string {
	if x != nil && x.BrandLibraryID != nil {
		return *x.BrandLibraryID
	}
	return ""
}

type GeneratedBrandColors struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Primary       string                 `protobuf:"bytes,1,opt,name=primary,proto3" json:"primary,omitempty"`
	Secondary     string                 `protobuf:"bytes,2,opt,name=secondary,proto3" json:"secondary,omitempty"`
	Accent        string                 `protobuf:"bytes,3,opt,name=accent,proto3" json:"accent,omitempty"`
	Text          string                 `protobuf:"bytes,4,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GeneratedBrandColors) Reset() {
	*x = GeneratedBrandColors{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GeneratedBrandColors) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GeneratedBrandColors) ProtoMessage() {}

func (x *GeneratedBrandColors) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GeneratedBrandColors.ProtoReflect.Descriptor instead.
func (*GeneratedBrandColors) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{1}
}

func (x *GeneratedBrandColors) GetPrimary() string {
	if x != nil {
		return x.Primary
	}
	return ""
}

func (x *GeneratedBrandColors) GetSecondary() string {
	if x != nil {
		return x.Secondary
	}
	return ""
}

func (x *GeneratedBrandColors) GetAccent() string {
	if x != nil {
		return x.Accent
	}
	return ""
}

func (x *GeneratedBrandColors) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

type VideoMetadata struct {
	state              protoimpl.MessageState  `protogen:"open.v1"`
	Fps                int32                   `protobuf:"varint,1,opt,name=fps,proto3" json:"fps,omitempty"`
	BackgroundStyle    *BackgroundStyle        `protobuf:"bytes,2,opt,name=background_style,json=backgroundStyle,proto3,oneof" json:"background_style,omitempty"`
	Resolution         *Resolution             `protobuf:"bytes,3,opt,name=resolution,proto3" json:"resolution,omitempty"`
	Duration           float32                 `protobuf:"fixed32,4,opt,name=duration,proto3" json:"duration,omitempty"`
	Prompt             string                  `protobuf:"bytes,5,opt,name=prompt,proto3" json:"prompt,omitempty"`
	Language           VideoLanguage           `protobuf:"varint,7,opt,name=language,proto3,enum=coasterai.core.v1.VideoLanguage" json:"language,omitempty"`
	BackgroundAudioUrl *string                 `protobuf:"bytes,8,opt,name=background_audio_url,json=backgroundAudioUrl,proto3,oneof" json:"background_audio_url,omitempty"`
	GeneratedBranding  *GeneratedVideoBranding `protobuf:"bytes,9,opt,name=generatedBranding,proto3,oneof" json:"generatedBranding,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *VideoMetadata) Reset() {
	*x = VideoMetadata{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoMetadata) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoMetadata) ProtoMessage() {}

func (x *VideoMetadata) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoMetadata.ProtoReflect.Descriptor instead.
func (*VideoMetadata) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{2}
}

func (x *VideoMetadata) GetFps() int32 {
	if x != nil {
		return x.Fps
	}
	return 0
}

func (x *VideoMetadata) GetBackgroundStyle() *BackgroundStyle {
	if x != nil {
		return x.BackgroundStyle
	}
	return nil
}

func (x *VideoMetadata) GetResolution() *Resolution {
	if x != nil {
		return x.Resolution
	}
	return nil
}

func (x *VideoMetadata) GetDuration() float32 {
	if x != nil {
		return x.Duration
	}
	return 0
}

func (x *VideoMetadata) GetPrompt() string {
	if x != nil {
		return x.Prompt
	}
	return ""
}

func (x *VideoMetadata) GetLanguage() VideoLanguage {
	if x != nil {
		return x.Language
	}
	return VideoLanguage_VIDE_LANGUAGE_EN
}

func (x *VideoMetadata) GetBackgroundAudioUrl() string {
	if x != nil && x.BackgroundAudioUrl != nil {
		return *x.BackgroundAudioUrl
	}
	return ""
}

func (x *VideoMetadata) GetGeneratedBranding() *GeneratedVideoBranding {
	if x != nil {
		return x.GeneratedBranding
	}
	return nil
}

type Video struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Config        *VideoConfig           `protobuf:"bytes,3,opt,name=config,proto3" json:"config,omitempty"`
	Metadata      *VideoMetadata         `protobuf:"bytes,4,opt,name=metadata,proto3" json:"metadata,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	Status        VideoStatus            `protobuf:"varint,6,opt,name=status,proto3,enum=coasterai.core.v1.VideoStatus" json:"status,omitempty"`
	Version       int64                  `protobuf:"varint,7,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Video) Reset() {
	*x = Video{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Video) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Video) ProtoMessage() {}

func (x *Video) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Video.ProtoReflect.Descriptor instead.
func (*Video) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{3}
}

func (x *Video) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Video) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Video) GetConfig() *VideoConfig {
	if x != nil {
		return x.Config
	}
	return nil
}

func (x *Video) GetMetadata() *VideoMetadata {
	if x != nil {
		return x.Metadata
	}
	return nil
}

func (x *Video) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Video) GetStatus() VideoStatus {
	if x != nil {
		return x.Status
	}
	return VideoStatus_VIDEO_STATUS_UNSPECIFIED
}

func (x *Video) GetVersion() int64 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VideoConfig struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sections      []*Section             `protobuf:"bytes,1,rep,name=sections,proto3" json:"sections,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VideoConfig) Reset() {
	*x = VideoConfig{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VideoConfig) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VideoConfig) ProtoMessage() {}

func (x *VideoConfig) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VideoConfig.ProtoReflect.Descriptor instead.
func (*VideoConfig) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{4}
}

func (x *VideoConfig) GetSections() []*Section {
	if x != nil {
		return x.Sections
	}
	return nil
}

type Script struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*ScriptItem          `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Script) Reset() {
	*x = Script{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Script) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Script) ProtoMessage() {}

func (x *Script) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Script.ProtoReflect.Descriptor instead.
func (*Script) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{5}
}

func (x *Script) GetItems() []*ScriptItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type ScriptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Name          string                 `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Voiceover     *string                `protobuf:"bytes,2,opt,name=voiceover,proto3,oneof" json:"voiceover,omitempty"`
	Reference     *string                `protobuf:"bytes,3,opt,name=reference,proto3,oneof" json:"reference,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ScriptItem) Reset() {
	*x = ScriptItem{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ScriptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ScriptItem) ProtoMessage() {}

func (x *ScriptItem) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ScriptItem.ProtoReflect.Descriptor instead.
func (*ScriptItem) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{6}
}

func (x *ScriptItem) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *ScriptItem) GetVoiceover() string {
	if x != nil && x.Voiceover != nil {
		return *x.Voiceover
	}
	return ""
}

func (x *ScriptItem) GetReference() string {
	if x != nil && x.Reference != nil {
		return *x.Reference
	}
	return ""
}

type Resolution struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Aspect        string                 `protobuf:"bytes,3,opt,name=aspect,proto3" json:"aspect,omitempty"`
	Width         int32                  `protobuf:"varint,4,opt,name=width,proto3" json:"width,omitempty"`
	Height        int32                  `protobuf:"varint,5,opt,name=height,proto3" json:"height,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Resolution) Reset() {
	*x = Resolution{}
	mi := &file_coasterai_core_v1_video_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Resolution) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Resolution) ProtoMessage() {}

func (x *Resolution) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_core_v1_video_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Resolution.ProtoReflect.Descriptor instead.
func (*Resolution) Descriptor() ([]byte, []int) {
	return file_coasterai_core_v1_video_proto_rawDescGZIP(), []int{7}
}

func (x *Resolution) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Resolution) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Resolution) GetAspect() string {
	if x != nil {
		return x.Aspect
	}
	return ""
}

func (x *Resolution) GetWidth() int32 {
	if x != nil {
		return x.Width
	}
	return 0
}

func (x *Resolution) GetHeight() int32 {
	if x != nil {
		return x.Height
	}
	return 0
}

var File_coasterai_core_v1_video_proto protoreflect.FileDescriptor

const file_coasterai_core_v1_video_proto_rawDesc = "" +
	"\n" +
	"\x1dcoasterai/core/v1/video.proto\x12\x11coasterai.core.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1dcoasterai/core/v1/slide.proto\"\xc3\x01\n" +
	"\x16GeneratedVideoBranding\x12(\n" +
	"\x0fbrandGuideLines\x18\x01 \x01(\tR\x0fbrandGuideLines\x12?\n" +
	"\x06colors\x18\x02 \x01(\v2'.coasterai.core.v1.GeneratedBrandColorsR\x06colors\x12+\n" +
	"\x0ebrandLibraryID\x18\x03 \x01(\tH\x00R\x0ebrandLibraryID\x88\x01\x01B\x11\n" +
	"\x0f_brandLibraryID\"z\n" +
	"\x14GeneratedBrandColors\x12\x18\n" +
	"\aprimary\x18\x01 \x01(\tR\aprimary\x12\x1c\n" +
	"\tsecondary\x18\x02 \x01(\tR\tsecondary\x12\x16\n" +
	"\x06accent\x18\x03 \x01(\tR\x06accent\x12\x12\n" +
	"\x04text\x18\x04 \x01(\tR\x04text\"\xff\x03\n" +
	"\rVideoMetadata\x12\x10\n" +
	"\x03fps\x18\x01 \x01(\x05R\x03fps\x12R\n" +
	"\x10background_style\x18\x02 \x01(\v2\".coasterai.core.v1.BackgroundStyleH\x00R\x0fbackgroundStyle\x88\x01\x01\x12=\n" +
	"\n" +
	"resolution\x18\x03 \x01(\v2\x1d.coasterai.core.v1.ResolutionR\n" +
	"resolution\x12\x1a\n" +
	"\bduration\x18\x04 \x01(\x02R\bduration\x12\x16\n" +
	"\x06prompt\x18\x05 \x01(\tR\x06prompt\x12<\n" +
	"\blanguage\x18\a \x01(\x0e2 .coasterai.core.v1.VideoLanguageR\blanguage\x125\n" +
	"\x14background_audio_url\x18\b \x01(\tH\x01R\x12backgroundAudioUrl\x88\x01\x01\x12\\\n" +
	"\x11generatedBranding\x18\t \x01(\v2).coasterai.core.v1.GeneratedVideoBrandingH\x02R\x11generatedBranding\x88\x01\x01B\x13\n" +
	"\x11_background_styleB\x17\n" +
	"\x15_background_audio_urlB\x14\n" +
	"\x12_generatedBranding\"\xae\x02\n" +
	"\x05Video\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x126\n" +
	"\x06config\x18\x03 \x01(\v2\x1e.coasterai.core.v1.VideoConfigR\x06config\x12<\n" +
	"\bmetadata\x18\x04 \x01(\v2 .coasterai.core.v1.VideoMetadataR\bmetadata\x129\n" +
	"\n" +
	"created_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x126\n" +
	"\x06status\x18\x06 \x01(\x0e2\x1e.coasterai.core.v1.VideoStatusR\x06status\x12\x18\n" +
	"\aversion\x18\a \x01(\x03R\aversion\"E\n" +
	"\vVideoConfig\x126\n" +
	"\bsections\x18\x01 \x03(\v2\x1a.coasterai.core.v1.SectionR\bsections\"=\n" +
	"\x06Script\x123\n" +
	"\x05items\x18\x01 \x03(\v2\x1d.coasterai.core.v1.ScriptItemR\x05items\"\x82\x01\n" +
	"\n" +
	"ScriptItem\x12\x12\n" +
	"\x04name\x18\x01 \x01(\tR\x04name\x12!\n" +
	"\tvoiceover\x18\x02 \x01(\tH\x00R\tvoiceover\x88\x01\x01\x12!\n" +
	"\treference\x18\x03 \x01(\tH\x01R\treference\x88\x01\x01B\f\n" +
	"\n" +
	"_voiceoverB\f\n" +
	"\n" +
	"_reference\"v\n" +
	"\n" +
	"Resolution\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x16\n" +
	"\x06aspect\x18\x03 \x01(\tR\x06aspect\x12\x14\n" +
	"\x05width\x18\x04 \x01(\x05R\x05width\x12\x16\n" +
	"\x06height\x18\x05 \x01(\x05R\x06height*\xde\x01\n" +
	"\vVideoStatus\x12\x1c\n" +
	"\x18VIDEO_STATUS_UNSPECIFIED\x10\x00\x12\x1b\n" +
	"\x17VIDEO_STATUS_PROCESSING\x10\x01\x12\x1a\n" +
	"\x16VIDEO_STATUS_COMPLETED\x10\x02\x12\x17\n" +
	"\x13VIDEO_STATUS_FAILED\x10\x03\x12\x19\n" +
	"\x15VIDEO_STATUS_PLANNING\x10\x04\x12#\n" +
	"\x1fVIDEO_STATUS_PLANNING_CANCELLED\x10\x05\x12\x1f\n" +
	"\x1bVIDEO_STATUS_USER_CANCELLED\x10\x06*%\n" +
	"\rVideoLanguage\x12\x14\n" +
	"\x10VIDE_LANGUAGE_EN\x10\x00*\x83\x01\n" +
	"\x0eResolutionType\x12\x1f\n" +
	"\x1bRESOLUTION_TYPE_UNSPECIFIED\x10\x00\x12\x13\n" +
	"\x0fRESOLUTION_16_9\x10\x01\x12\x12\n" +
	"\x0eRESOLUTION_4_3\x10\x02\x12\x13\n" +
	"\x0fRESOLUTION_9_16\x10\x03\x12\x12\n" +
	"\x0eRESOLUTION_1_1\x10\x04*<\n" +
	"\tStyleType\x12\x18\n" +
	"\x14STYLE_TYPE_UNDEFINED\x10\x00\x12\x15\n" +
	"\x11STYLE_TYPE_SIMPLE\x10\x01B;Z9github.com/shank318/coasterai/pb/coasterai/core/v1;pbcoreb\x06proto3"

var (
	file_coasterai_core_v1_video_proto_rawDescOnce sync.Once
	file_coasterai_core_v1_video_proto_rawDescData []byte
)

func file_coasterai_core_v1_video_proto_rawDescGZIP() []byte {
	file_coasterai_core_v1_video_proto_rawDescOnce.Do(func() {
		file_coasterai_core_v1_video_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_video_proto_rawDesc), len(file_coasterai_core_v1_video_proto_rawDesc)))
	})
	return file_coasterai_core_v1_video_proto_rawDescData
}

var file_coasterai_core_v1_video_proto_enumTypes = make([]protoimpl.EnumInfo, 4)
var file_coasterai_core_v1_video_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_coasterai_core_v1_video_proto_goTypes = []any{
	(VideoStatus)(0),               // 0: coasterai.core.v1.VideoStatus
	(VideoLanguage)(0),             // 1: coasterai.core.v1.VideoLanguage
	(ResolutionType)(0),            // 2: coasterai.core.v1.ResolutionType
	(StyleType)(0),                 // 3: coasterai.core.v1.StyleType
	(*GeneratedVideoBranding)(nil), // 4: coasterai.core.v1.GeneratedVideoBranding
	(*GeneratedBrandColors)(nil),   // 5: coasterai.core.v1.GeneratedBrandColors
	(*VideoMetadata)(nil),          // 6: coasterai.core.v1.VideoMetadata
	(*Video)(nil),                  // 7: coasterai.core.v1.Video
	(*VideoConfig)(nil),            // 8: coasterai.core.v1.VideoConfig
	(*Script)(nil),                 // 9: coasterai.core.v1.Script
	(*ScriptItem)(nil),             // 10: coasterai.core.v1.ScriptItem
	(*Resolution)(nil),             // 11: coasterai.core.v1.Resolution
	(*BackgroundStyle)(nil),        // 12: coasterai.core.v1.BackgroundStyle
	(*timestamppb.Timestamp)(nil),  // 13: google.protobuf.Timestamp
	(*Section)(nil),                // 14: coasterai.core.v1.Section
}
var file_coasterai_core_v1_video_proto_depIdxs = []int32{
	5,  // 0: coasterai.core.v1.GeneratedVideoBranding.colors:type_name -> coasterai.core.v1.GeneratedBrandColors
	12, // 1: coasterai.core.v1.VideoMetadata.background_style:type_name -> coasterai.core.v1.BackgroundStyle
	11, // 2: coasterai.core.v1.VideoMetadata.resolution:type_name -> coasterai.core.v1.Resolution
	1,  // 3: coasterai.core.v1.VideoMetadata.language:type_name -> coasterai.core.v1.VideoLanguage
	4,  // 4: coasterai.core.v1.VideoMetadata.generatedBranding:type_name -> coasterai.core.v1.GeneratedVideoBranding
	8,  // 5: coasterai.core.v1.Video.config:type_name -> coasterai.core.v1.VideoConfig
	6,  // 6: coasterai.core.v1.Video.metadata:type_name -> coasterai.core.v1.VideoMetadata
	13, // 7: coasterai.core.v1.Video.created_at:type_name -> google.protobuf.Timestamp
	0,  // 8: coasterai.core.v1.Video.status:type_name -> coasterai.core.v1.VideoStatus
	14, // 9: coasterai.core.v1.VideoConfig.sections:type_name -> coasterai.core.v1.Section
	10, // 10: coasterai.core.v1.Script.items:type_name -> coasterai.core.v1.ScriptItem
	11, // [11:11] is the sub-list for method output_type
	11, // [11:11] is the sub-list for method input_type
	11, // [11:11] is the sub-list for extension type_name
	11, // [11:11] is the sub-list for extension extendee
	0,  // [0:11] is the sub-list for field type_name
}

func init() { file_coasterai_core_v1_video_proto_init() }
func file_coasterai_core_v1_video_proto_init() {
	if File_coasterai_core_v1_video_proto != nil {
		return
	}
	file_coasterai_core_v1_slide_proto_init()
	file_coasterai_core_v1_video_proto_msgTypes[0].OneofWrappers = []any{}
	file_coasterai_core_v1_video_proto_msgTypes[2].OneofWrappers = []any{}
	file_coasterai_core_v1_video_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coasterai_core_v1_video_proto_rawDesc), len(file_coasterai_core_v1_video_proto_rawDesc)),
			NumEnums:      4,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coasterai_core_v1_video_proto_goTypes,
		DependencyIndexes: file_coasterai_core_v1_video_proto_depIdxs,
		EnumInfos:         file_coasterai_core_v1_video_proto_enumTypes,
		MessageInfos:      file_coasterai_core_v1_video_proto_msgTypes,
	}.Build()
	File_coasterai_core_v1_video_proto = out.File
	file_coasterai_core_v1_video_proto_goTypes = nil
	file_coasterai_core_v1_video_proto_depIdxs = nil
}
