// ----------------------------------------------------------------------------
//
//  Welcome to Baml! To use this generated code, please run the following:
//
//  $ go get github.com/boundaryml/baml
//
// ----------------------------------------------------------------------------

// This file was generated by BAML: please do not edit it. Instead, edit the
// BAML files and re-generate this code using: baml-cli generate
// You can install baml-cli with:
//  $ go install github.com/boundaryml/baml/baml-cli

package stream_types

import (
	"fmt"

	baml "github.com/boundaryml/baml/engine/language_client_go/pkg"
	"github.com/boundaryml/baml/engine/language_client_go/pkg/cffi"

	"github.com/shank318/coasterai/baml_client/types"
)

type AnimationCategories struct {
	EntranceAnimations []string `json:"entranceAnimations"`
}

func (c *AnimationCategories) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "AnimationCategories" {
		panic(fmt.Sprintf("expected AnimationCategories, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "entranceAnimations":
			c.EntranceAnimations = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class AnimationCategories", key))

		}
	}

}

func (c AnimationCategories) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["entranceAnimations"] = c.EntranceAnimations

	return baml.EncodeClass("AnimationCategories", fields, nil)
}

func (c AnimationCategories) BamlTypeName() string {
	return "AnimationCategories"
}

type AskUserQuestion struct {
	Tool_name          *string                    `json:"tool_name"`
	QuestionType       *types.AskUserQuestionType `json:"questionType"`
	Question_text      *string                    `json:"question_text"`
	Options            []string                   `json:"options"`
	Allow_custom_entry *bool                      `json:"allow_custom_entry"`
	AttachmentUrl      *string                    `json:"attachmentUrl"`
}

func (c *AskUserQuestion) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "AskUserQuestion" {
		panic(fmt.Sprintf("expected AskUserQuestion, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "tool_name":
			c.Tool_name = baml.Decode(valueHolder).Interface().(*string)

		case "questionType":
			c.QuestionType = baml.Decode(valueHolder).Interface().(*types.AskUserQuestionType)

		case "question_text":
			c.Question_text = baml.Decode(valueHolder).Interface().(*string)

		case "options":
			c.Options = baml.Decode(valueHolder).Interface().([]string)

		case "allow_custom_entry":
			c.Allow_custom_entry = baml.Decode(valueHolder).Interface().(*bool)

		case "attachmentUrl":
			c.AttachmentUrl = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class AskUserQuestion", key))

		}
	}

}

func (c AskUserQuestion) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["tool_name"] = c.Tool_name

	fields["questionType"] = c.QuestionType

	fields["question_text"] = c.Question_text

	fields["options"] = c.Options

	fields["allow_custom_entry"] = c.Allow_custom_entry

	fields["attachmentUrl"] = c.AttachmentUrl

	return baml.EncodeClass("AskUserQuestion", fields, nil)
}

func (c AskUserQuestion) BamlTypeName() string {
	return "AskUserQuestion"
}

type AssetAnalysis struct {
	Description *string  `json:"description"`
	Tags        []string `json:"tags"`
}

func (c *AssetAnalysis) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "AssetAnalysis" {
		panic(fmt.Sprintf("expected AssetAnalysis, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(*string)

		case "tags":
			c.Tags = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class AssetAnalysis", key))

		}
	}

}

func (c AssetAnalysis) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["description"] = c.Description

	fields["tags"] = c.Tags

	return baml.EncodeClass("AssetAnalysis", fields, nil)
}

func (c AssetAnalysis) BamlTypeName() string {
	return "AssetAnalysis"
}

type Background struct {
	Solid *types.Union2ColorTokenOrString `json:"solid"`
}

func (c *Background) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Background" {
		panic(fmt.Sprintf("expected Background, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "solid":
			c.Solid = baml.Decode(valueHolder).Interface().(*types.Union2ColorTokenOrString)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Background", key))

		}
	}

}

func (c Background) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["solid"] = c.Solid

	return baml.EncodeClass("Background", fields, nil)
}

func (c Background) BamlTypeName() string {
	return "Background"
}

type Category struct {
	Name        *string `json:"name"`
	Description *string `json:"description"`
}

func (c *Category) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Category" {
		panic(fmt.Sprintf("expected Category, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*string)

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Category", key))

		}
	}

}

func (c Category) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["description"] = c.Description

	return baml.EncodeClass("Category", fields, nil)
}

func (c Category) BamlTypeName() string {
	return "Category"
}

type ExtractTemplateConfigRequest struct {
	Content       *string        `json:"content"`
	Scenes        []SceneElement `json:"scenes"`
	VideoBranding *VideoBranding `json:"VideoBranding"`
}

func (c *ExtractTemplateConfigRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ExtractTemplateConfigRequest" {
		panic(fmt.Sprintf("expected ExtractTemplateConfigRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "content":
			c.Content = baml.Decode(valueHolder).Interface().(*string)

		case "scenes":
			c.Scenes = baml.Decode(valueHolder).Interface().([]SceneElement)

		case "VideoBranding":
			c.VideoBranding = baml.Decode(valueHolder).Interface().(*VideoBranding)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ExtractTemplateConfigRequest", key))

		}
	}

}

func (c ExtractTemplateConfigRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["content"] = c.Content

	fields["scenes"] = c.Scenes

	fields["VideoBranding"] = c.VideoBranding

	return baml.EncodeClass("ExtractTemplateConfigRequest", fields, nil)
}

func (c ExtractTemplateConfigRequest) BamlTypeName() string {
	return "ExtractTemplateConfigRequest"
}

type ExtractTemplateConfigResponse struct {
	Scenes []SceneElement `json:"scenes"`
}

func (c *ExtractTemplateConfigResponse) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ExtractTemplateConfigResponse" {
		panic(fmt.Sprintf("expected ExtractTemplateConfigResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "scenes":
			c.Scenes = baml.Decode(valueHolder).Interface().([]SceneElement)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ExtractTemplateConfigResponse", key))

		}
	}

}

func (c ExtractTemplateConfigResponse) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["scenes"] = c.Scenes

	return baml.EncodeClass("ExtractTemplateConfigResponse", fields, nil)
}

func (c ExtractTemplateConfigResponse) BamlTypeName() string {
	return "ExtractTemplateConfigResponse"
}

type GenerateAnimationCodeRequest struct {
	Prompt        *string        `json:"Prompt"`
	VideoBranding *VideoBranding `json:"VideoBranding"`
}

func (c *GenerateAnimationCodeRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GenerateAnimationCodeRequest" {
		panic(fmt.Sprintf("expected GenerateAnimationCodeRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "Prompt":
			c.Prompt = baml.Decode(valueHolder).Interface().(*string)

		case "VideoBranding":
			c.VideoBranding = baml.Decode(valueHolder).Interface().(*VideoBranding)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GenerateAnimationCodeRequest", key))

		}
	}

}

func (c GenerateAnimationCodeRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["Prompt"] = c.Prompt

	fields["VideoBranding"] = c.VideoBranding

	return baml.EncodeClass("GenerateAnimationCodeRequest", fields, nil)
}

func (c GenerateAnimationCodeRequest) BamlTypeName() string {
	return "GenerateAnimationCodeRequest"
}

type GenerateAnimationCodeResponse struct {
	Code            *string `json:"code"`
	Total_frames    *int64  `json:"total_frames"`
	ManualEdits     *string `json:"manualEdits"`
	ThinkingSummary *string `json:"thinkingSummary"`
}

func (c *GenerateAnimationCodeResponse) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GenerateAnimationCodeResponse" {
		panic(fmt.Sprintf("expected GenerateAnimationCodeResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "code":
			c.Code = baml.Decode(valueHolder).Interface().(*string)

		case "total_frames":
			c.Total_frames = baml.Decode(valueHolder).Interface().(*int64)

		case "manualEdits":
			c.ManualEdits = baml.Decode(valueHolder).Interface().(*string)

		case "thinkingSummary":
			c.ThinkingSummary = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GenerateAnimationCodeResponse", key))

		}
	}

}

func (c GenerateAnimationCodeResponse) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["code"] = c.Code

	fields["total_frames"] = c.Total_frames

	fields["manualEdits"] = c.ManualEdits

	fields["thinkingSummary"] = c.ThinkingSummary

	return baml.EncodeClass("GenerateAnimationCodeResponse", fields, nil)
}

func (c GenerateAnimationCodeResponse) BamlTypeName() string {
	return "GenerateAnimationCodeResponse"
}

type GenerateScriptPlan struct {
	Plan *Union2ListAskUserQuestionOrScript `json:"plan"`
}

func (c *GenerateScriptPlan) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GenerateScriptPlan" {
		panic(fmt.Sprintf("expected GenerateScriptPlan, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "plan":
			c.Plan = baml.Decode(valueHolder).Interface().(*Union2ListAskUserQuestionOrScript)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GenerateScriptPlan", key))

		}
	}

}

func (c GenerateScriptPlan) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["plan"] = c.Plan

	return baml.EncodeClass("GenerateScriptPlan", fields, nil)
}

func (c GenerateScriptPlan) BamlTypeName() string {
	return "GenerateScriptPlan"
}

type GenerateVideoNarrationRequest struct {
	Description *string `json:"description"`
}

func (c *GenerateVideoNarrationRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GenerateVideoNarrationRequest" {
		panic(fmt.Sprintf("expected GenerateVideoNarrationRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "description":
			c.Description = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GenerateVideoNarrationRequest", key))

		}
	}

}

func (c GenerateVideoNarrationRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["description"] = c.Description

	return baml.EncodeClass("GenerateVideoNarrationRequest", fields, nil)
}

func (c GenerateVideoNarrationRequest) BamlTypeName() string {
	return "GenerateVideoNarrationRequest"
}

type GeneratedVideoPlan struct {
	VideoName       *string        `json:"videoName"`
	Sections        []SceneSection `json:"sections"`
	ThinkingSummary *string        `json:"thinkingSummary"`
}

func (c *GeneratedVideoPlan) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "GeneratedVideoPlan" {
		panic(fmt.Sprintf("expected GeneratedVideoPlan, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "videoName":
			c.VideoName = baml.Decode(valueHolder).Interface().(*string)

		case "sections":
			c.Sections = baml.Decode(valueHolder).Interface().([]SceneSection)

		case "thinkingSummary":
			c.ThinkingSummary = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class GeneratedVideoPlan", key))

		}
	}

}

func (c GeneratedVideoPlan) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["videoName"] = c.VideoName

	fields["sections"] = c.Sections

	fields["thinkingSummary"] = c.ThinkingSummary

	return baml.EncodeClass("GeneratedVideoPlan", fields, nil)
}

func (c GeneratedVideoPlan) BamlTypeName() string {
	return "GeneratedVideoPlan"
}

type MatchCategoriesRequest struct {
	Categories []Category `json:"categories"`
	Content    *string    `json:"content"`
	Edits      *string    `json:"edits"`
}

func (c *MatchCategoriesRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MatchCategoriesRequest" {
		panic(fmt.Sprintf("expected MatchCategoriesRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "categories":
			c.Categories = baml.Decode(valueHolder).Interface().([]Category)

		case "content":
			c.Content = baml.Decode(valueHolder).Interface().(*string)

		case "edits":
			c.Edits = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MatchCategoriesRequest", key))

		}
	}

}

func (c MatchCategoriesRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["categories"] = c.Categories

	fields["content"] = c.Content

	fields["edits"] = c.Edits

	return baml.EncodeClass("MatchCategoriesRequest", fields, nil)
}

func (c MatchCategoriesRequest) BamlTypeName() string {
	return "MatchCategoriesRequest"
}

type MatchCategoriesResponse struct {
	Categories []string `json:"categories"`
}

func (c *MatchCategoriesResponse) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "MatchCategoriesResponse" {
		panic(fmt.Sprintf("expected MatchCategoriesResponse, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "categories":
			c.Categories = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class MatchCategoriesResponse", key))

		}
	}

}

func (c MatchCategoriesResponse) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["categories"] = c.Categories

	return baml.EncodeClass("MatchCategoriesResponse", fields, nil)
}

func (c MatchCategoriesResponse) BamlTypeName() string {
	return "MatchCategoriesResponse"
}

type Message struct {
	Role    *types.Union3KassistantOrKtoolOrKuser `json:"role"`
	Content *string                               `json:"content"`
	Images  []types.Image                         `json:"images"`
	Videos  []types.Video                         `json:"videos"`
}

func (c *Message) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Message" {
		panic(fmt.Sprintf("expected Message, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "role":
			c.Role = baml.Decode(valueHolder).Interface().(*types.Union3KassistantOrKtoolOrKuser)

		case "content":
			c.Content = baml.Decode(valueHolder).Interface().(*string)

		case "images":
			c.Images = baml.Decode(valueHolder).Interface().([]types.Image)

		case "videos":
			c.Videos = baml.Decode(valueHolder).Interface().([]types.Video)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Message", key))

		}
	}

}

func (c Message) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["role"] = c.Role

	fields["content"] = c.Content

	fields["images"] = c.Images

	fields["videos"] = c.Videos

	return baml.EncodeClass("Message", fields, nil)
}

func (c Message) BamlTypeName() string {
	return "Message"
}

type NarrationSegment struct {
	Text *string `json:"text"`
}

func (c *NarrationSegment) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "NarrationSegment" {
		panic(fmt.Sprintf("expected NarrationSegment, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "text":
			c.Text = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class NarrationSegment", key))

		}
	}

}

func (c NarrationSegment) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["text"] = c.Text

	return baml.EncodeClass("NarrationSegment", fields, nil)
}

func (c NarrationSegment) BamlTypeName() string {
	return "NarrationSegment"
}

type Scene struct {
	Element         *SceneElement `json:"element"`
	Voiceover       *string       `json:"voiceover"`
	ThinkingSummary *string       `json:"thinkingSummary"`
}

func (c *Scene) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Scene" {
		panic(fmt.Sprintf("expected Scene, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "element":
			c.Element = baml.Decode(valueHolder).Interface().(*SceneElement)

		case "voiceover":
			c.Voiceover = baml.Decode(valueHolder).Interface().(*string)

		case "thinkingSummary":
			c.ThinkingSummary = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Scene", key))

		}
	}

}

func (c Scene) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["element"] = c.Element

	fields["voiceover"] = c.Voiceover

	fields["thinkingSummary"] = c.ThinkingSummary

	return baml.EncodeClass("Scene", fields, nil)
}

func (c Scene) BamlTypeName() string {
	return "Scene"
}

type SceneElement struct {
	Component *string `json:"component"`
	Props     *string `json:"props"`
}

func (c *SceneElement) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SceneElement" {
		panic(fmt.Sprintf("expected SceneElement, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "component":
			c.Component = baml.Decode(valueHolder).Interface().(*string)

		case "props":
			c.Props = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SceneElement", key))

		}
	}

}

func (c SceneElement) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["component"] = c.Component

	fields["props"] = c.Props

	return baml.EncodeClass("SceneElement", fields, nil)
}

func (c SceneElement) BamlTypeName() string {
	return "SceneElement"
}

type SceneSection struct {
	Name   *string `json:"name"`
	Slides []Scene `json:"slides"`
}

func (c *SceneSection) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "SceneSection" {
		panic(fmt.Sprintf("expected SceneSection, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*string)

		case "slides":
			c.Slides = baml.Decode(valueHolder).Interface().([]Scene)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class SceneSection", key))

		}
	}

}

func (c SceneSection) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["slides"] = c.Slides

	return baml.EncodeClass("SceneSection", fields, nil)
}

func (c SceneSection) BamlTypeName() string {
	return "SceneSection"
}

type Script struct {
	Sections        []ScriptSection `json:"sections"`
	ThinkingSummary *string         `json:"thinkingSummary"`
}

func (c *Script) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "Script" {
		panic(fmt.Sprintf("expected Script, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "sections":
			c.Sections = baml.Decode(valueHolder).Interface().([]ScriptSection)

		case "thinkingSummary":
			c.ThinkingSummary = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class Script", key))

		}
	}

}

func (c Script) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["sections"] = c.Sections

	fields["thinkingSummary"] = c.ThinkingSummary

	return baml.EncodeClass("Script", fields, nil)
}

func (c Script) BamlTypeName() string {
	return "Script"
}

type ScriptPlannerRequest struct {
	Duration      *int64         `json:"Duration"`
	Prompt        *string        `json:"Prompt"`
	Language      *string        `json:"Language"`
	Resolution    *string        `json:"Resolution"`
	VideoBranding *VideoBranding `json:"VideoBranding"`
}

func (c *ScriptPlannerRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ScriptPlannerRequest" {
		panic(fmt.Sprintf("expected ScriptPlannerRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "Duration":
			c.Duration = baml.Decode(valueHolder).Interface().(*int64)

		case "Prompt":
			c.Prompt = baml.Decode(valueHolder).Interface().(*string)

		case "Language":
			c.Language = baml.Decode(valueHolder).Interface().(*string)

		case "Resolution":
			c.Resolution = baml.Decode(valueHolder).Interface().(*string)

		case "VideoBranding":
			c.VideoBranding = baml.Decode(valueHolder).Interface().(*VideoBranding)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ScriptPlannerRequest", key))

		}
	}

}

func (c ScriptPlannerRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["Duration"] = c.Duration

	fields["Prompt"] = c.Prompt

	fields["Language"] = c.Language

	fields["Resolution"] = c.Resolution

	fields["VideoBranding"] = c.VideoBranding

	return baml.EncodeClass("ScriptPlannerRequest", fields, nil)
}

func (c ScriptPlannerRequest) BamlTypeName() string {
	return "ScriptPlannerRequest"
}

type ScriptSection struct {
	Name      *types.VideoSection `json:"name"`
	Narration []string            `json:"narration"`
}

func (c *ScriptSection) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "ScriptSection" {
		panic(fmt.Sprintf("expected ScriptSection, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "name":
			c.Name = baml.Decode(valueHolder).Interface().(*types.VideoSection)

		case "narration":
			c.Narration = baml.Decode(valueHolder).Interface().([]string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class ScriptSection", key))

		}
	}

}

func (c ScriptSection) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["name"] = c.Name

	fields["narration"] = c.Narration

	return baml.EncodeClass("ScriptSection", fields, nil)
}

func (c ScriptSection) BamlTypeName() string {
	return "ScriptSection"
}

type VideoBranding struct {
	BrandGuideLines *string `json:"brandGuideLines"`
	BrandColors     *string `json:"brandColors"`
	Attachments     *string `json:"attachments"`
}

func (c *VideoBranding) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "VideoBranding" {
		panic(fmt.Sprintf("expected VideoBranding, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "brandGuideLines":
			c.BrandGuideLines = baml.Decode(valueHolder).Interface().(*string)

		case "brandColors":
			c.BrandColors = baml.Decode(valueHolder).Interface().(*string)

		case "attachments":
			c.Attachments = baml.Decode(valueHolder).Interface().(*string)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class VideoBranding", key))

		}
	}

}

func (c VideoBranding) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["brandGuideLines"] = c.BrandGuideLines

	fields["brandColors"] = c.BrandColors

	fields["attachments"] = c.Attachments

	return baml.EncodeClass("VideoBranding", fields, nil)
}

func (c VideoBranding) BamlTypeName() string {
	return "VideoBranding"
}

type VideoGenerationPlanRequest struct {
	Duration            *int64               `json:"Duration"`
	Prompt              *string              `json:"Prompt"`
	Language            *string              `json:"Language"`
	Resolution          *string              `json:"Resolution"`
	VideoBranding       *VideoBranding       `json:"VideoBranding"`
	ComponentList       *string              `json:"ComponentList"`
	AnimationCategories *AnimationCategories `json:"AnimationCategories"`
}

func (c *VideoGenerationPlanRequest) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "VideoGenerationPlanRequest" {
		panic(fmt.Sprintf("expected VideoGenerationPlanRequest, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "Duration":
			c.Duration = baml.Decode(valueHolder).Interface().(*int64)

		case "Prompt":
			c.Prompt = baml.Decode(valueHolder).Interface().(*string)

		case "Language":
			c.Language = baml.Decode(valueHolder).Interface().(*string)

		case "Resolution":
			c.Resolution = baml.Decode(valueHolder).Interface().(*string)

		case "VideoBranding":
			c.VideoBranding = baml.Decode(valueHolder).Interface().(*VideoBranding)

		case "ComponentList":
			c.ComponentList = baml.Decode(valueHolder).Interface().(*string)

		case "AnimationCategories":
			c.AnimationCategories = baml.Decode(valueHolder).Interface().(*AnimationCategories)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class VideoGenerationPlanRequest", key))

		}
	}

}

func (c VideoGenerationPlanRequest) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["Duration"] = c.Duration

	fields["Prompt"] = c.Prompt

	fields["Language"] = c.Language

	fields["Resolution"] = c.Resolution

	fields["VideoBranding"] = c.VideoBranding

	fields["ComponentList"] = c.ComponentList

	fields["AnimationCategories"] = c.AnimationCategories

	return baml.EncodeClass("VideoGenerationPlanRequest", fields, nil)
}

func (c VideoGenerationPlanRequest) BamlTypeName() string {
	return "VideoGenerationPlanRequest"
}

type VideoNarration struct {
	Segments []NarrationSegment `json:"segments"`
}

func (c *VideoNarration) Decode(holder *cffi.CFFIValueClass, typeMap baml.TypeMap) {
	typeName := holder.Name
	if typeName.Namespace != cffi.CFFITypeNamespace_STREAM_TYPES {
		panic(fmt.Sprintf("expected cffi.CFFITypeNamespace_STREAM_TYPES, got %s", string(typeName.Namespace.String())))
	}
	if typeName.Name != "VideoNarration" {
		panic(fmt.Sprintf("expected VideoNarration, got %s", typeName.Name))
	}

	for _, field := range holder.Fields {
		key := field.Key
		valueHolder := field.Value
		switch key {

		case "segments":
			c.Segments = baml.Decode(valueHolder).Interface().([]NarrationSegment)

		default:

			panic(fmt.Sprintf("unexpected field: %s in class VideoNarration", key))

		}
	}

}

func (c VideoNarration) Encode() (*cffi.HostValue, error) {
	fields := map[string]any{}

	fields["segments"] = c.Segments

	return baml.EncodeClass("VideoNarration", fields, nil)
}

func (c VideoNarration) BamlTypeName() string {
	return "VideoNarration"
}
