// Code generated by go-enum DO NOT EDIT.
// Version: v0.9.2

// Built By: go install

package models

import (
	"errors"
	"fmt"
)

const (
	// TemplateStatusCREATED is a TemplateStatus of type CREATED.
	TemplateStatusCREATED TemplateStatus = "CREATED"
	// TemplateStatusWAITING is a TemplateStatus of type WAITING.
	TemplateStatusWAITING TemplateStatus = "WAITING"
	// TemplateStatusAVAILABLE is a TemplateStatus of type AVAILABLE.
	TemplateStatusAVAILABLE TemplateStatus = "AVAILABLE"
)

var ErrInvalidTemplateStatus = errors.New("not a valid TemplateStatus")

// String implements the Stringer interface.
func (x TemplateStatus) String() string {
	return string(x)
}

// IsValid provides a quick way to determine if the typed value is
// part of the allowed enumerated values
func (x TemplateStatus) IsValid() bool {
	_, err := ParseTemplateStatus(string(x))
	return err == nil
}

var _TemplateStatusValue = map[string]TemplateStatus{
	"CREATED":   TemplateStatusCREATED,
	"WAITING":   TemplateStatusWAITING,
	"AVAILABLE": TemplateStatusAVAILABLE,
}

// ParseTemplateStatus attempts to convert a string to a TemplateStatus.
func ParseTemplateStatus(name string) (TemplateStatus, error) {
	if x, ok := _TemplateStatusValue[name]; ok {
		return x, nil
	}
	return TemplateStatus(""), fmt.Errorf("%s is %w", name, ErrInvalidTemplateStatus)
}
