// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        (unknown)
// source: coasterai/portal/v1/voiceover.proto

package pbportal

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	_ "google.golang.org/protobuf/types/known/emptypb"
	_ "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateNarrationResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Segments      []*NarrationSegment    `protobuf:"bytes,1,rep,name=segments,proto3" json:"segments,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateNarrationResponse) Reset() {
	*x = GenerateNarrationResponse{}
	mi := &file_coasterai_portal_v1_voiceover_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateNarrationResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateNarrationResponse) ProtoMessage() {}

func (x *GenerateNarrationResponse) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_portal_v1_voiceover_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateNarrationResponse.ProtoReflect.Descriptor instead.
func (*GenerateNarrationResponse) Descriptor() ([]byte, []int) {
	return file_coasterai_portal_v1_voiceover_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateNarrationResponse) GetSegments() []*NarrationSegment {
	if x != nil {
		return x.Segments
	}
	return nil
}

type NarrationSegment struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Text          string                 `protobuf:"bytes,1,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NarrationSegment) Reset() {
	*x = NarrationSegment{}
	mi := &file_coasterai_portal_v1_voiceover_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NarrationSegment) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NarrationSegment) ProtoMessage() {}

func (x *NarrationSegment) ProtoReflect() protoreflect.Message {
	mi := &file_coasterai_portal_v1_voiceover_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NarrationSegment.ProtoReflect.Descriptor instead.
func (*NarrationSegment) Descriptor() ([]byte, []int) {
	return file_coasterai_portal_v1_voiceover_proto_rawDescGZIP(), []int{1}
}

func (x *NarrationSegment) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

var File_coasterai_portal_v1_voiceover_proto protoreflect.FileDescriptor

const file_coasterai_portal_v1_voiceover_proto_rawDesc = "" +
	"\n" +
	"#coasterai/portal/v1/voiceover.proto\x12\x13coasterai.portal.v1\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"^\n" +
	"\x19GenerateNarrationResponse\x12A\n" +
	"\bsegments\x18\x01 \x03(\v2%.coasterai.portal.v1.NarrationSegmentR\bsegments\"&\n" +
	"\x10NarrationSegment\x12\x12\n" +
	"\x04text\x18\x01 \x01(\tR\x04textB?Z=github.com/shank318/coasterai/pb/coasterai/portal/v1;pbportalb\x06proto3"

var (
	file_coasterai_portal_v1_voiceover_proto_rawDescOnce sync.Once
	file_coasterai_portal_v1_voiceover_proto_rawDescData []byte
)

func file_coasterai_portal_v1_voiceover_proto_rawDescGZIP() []byte {
	file_coasterai_portal_v1_voiceover_proto_rawDescOnce.Do(func() {
		file_coasterai_portal_v1_voiceover_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_coasterai_portal_v1_voiceover_proto_rawDesc), len(file_coasterai_portal_v1_voiceover_proto_rawDesc)))
	})
	return file_coasterai_portal_v1_voiceover_proto_rawDescData
}

var file_coasterai_portal_v1_voiceover_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_coasterai_portal_v1_voiceover_proto_goTypes = []any{
	(*GenerateNarrationResponse)(nil), // 0: coasterai.portal.v1.GenerateNarrationResponse
	(*NarrationSegment)(nil),          // 1: coasterai.portal.v1.NarrationSegment
}
var file_coasterai_portal_v1_voiceover_proto_depIdxs = []int32{
	1, // 0: coasterai.portal.v1.GenerateNarrationResponse.segments:type_name -> coasterai.portal.v1.NarrationSegment
	1, // [1:1] is the sub-list for method output_type
	1, // [1:1] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_coasterai_portal_v1_voiceover_proto_init() }
func file_coasterai_portal_v1_voiceover_proto_init() {
	if File_coasterai_portal_v1_voiceover_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_coasterai_portal_v1_voiceover_proto_rawDesc), len(file_coasterai_portal_v1_voiceover_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_coasterai_portal_v1_voiceover_proto_goTypes,
		DependencyIndexes: file_coasterai_portal_v1_voiceover_proto_depIdxs,
		MessageInfos:      file_coasterai_portal_v1_voiceover_proto_msgTypes,
	}.Build()
	File_coasterai_portal_v1_voiceover_proto = out.File
	file_coasterai_portal_v1_voiceover_proto_goTypes = nil
	file_coasterai_portal_v1_voiceover_proto_depIdxs = nil
}
